// Vibrant color themes inspired by Orbit
// const COLOR_THEMES = [
//     { bg: '#F47E60', fg: '#1A1A1A', name: 'Orbit Orange' },
//     { bg: '#FF6B6B', fg: '#1A1A1A', name: 'Coral Red' },
//     { bg: '#3498DB', fg: '#FFFFFF', name: 'Ocean Blue' },
//     { bg: '#5a06ef', fg: '#ffffff', name: 'Blue/Purple' },
//     { bg: '#0a481e', fg: '#ffffff', name: 'Pine Green' },
//     { bg: '#cdc50a', fg: '#FFFFFF', name: 'Dirty Yellow' },
//     { bg: '#F39C12', fg: '#1A1A1A', name: 'Warm Amber' },
// ];

// https://xkcd.com/color/rgb/
const COLOR_THEMES = [
    { bg: '#ACC2D9', fg: '#FFFFFF', name: 'Cloudy Blue' },
    { bg: '#56AE57', fg: '#FFFFFF', name: 'Dark Pastel Green' },
    { bg: '#B2996E', fg: '#FFFFFF', name: 'Dust' },
    { bg: '#A8FF04', fg: '#000000', name: 'Electric Lime' },
    { bg: '#69D84F', fg: '#FFFFFF', name: 'Fresh Green' },
    { bg: '#894585', fg: '#FFFFFF', name: 'Light Eggplant' },
    { bg: '#70B23F', fg: '#FFFFFF', name: 'Nasty Green' },
    { bg: '#D4FFFF', fg: '#000000', name: 'Really Light Blue' },
    { bg: '#65AB7C', fg: '#FFFFFF', name: 'Tea' },
    { bg: '#952E8F', fg: '#FFFFFF', name: 'Warm Purple' },
    { bg: '#FCFC81', fg: '#000000', name: 'Yellowish Tan' },
    { bg: '#A5A391', fg: '#FFFFFF', name: 'Cement' },
    { bg: '#388004', fg: '#FFFFFF', name: 'Dark Grass Green' },
    { bg: '#4C9085', fg: '#FFFFFF', name: 'Dusty Teal' },
    { bg: '#5E9B8A', fg: '#FFFFFF', name: 'Grey Teal' },
    { bg: '#EFB435', fg: '#FFFFFF', name: 'Macaroni And Cheese' },
    { bg: '#D99B82', fg: '#FFFFFF', name: 'Pinkish Tan' },
    { bg: '#0A5F38', fg: '#FFFFFF', name: 'Spruce' },
    { bg: '#0C06F7', fg: '#FFFFFF', name: 'Strong Blue' },
    { bg: '#61DE2A', fg: '#FFFFFF', name: 'Toxic Green' },
    { bg: '#3778BF', fg: '#FFFFFF', name: 'Windows Blue' },
    { bg: '#2242C7', fg: '#FFFFFF', name: 'Blue Blue' },
    { bg: '#533CC6', fg: '#FFFFFF', name: 'Blue With A Hint Of Purple' },
    { bg: '#9BB53C', fg: '#FFFFFF', name: 'Booger' },
    { bg: '#05FFA6', fg: '#FFFFFF', name: 'Bright Sea Green' },
    { bg: '#1F6357', fg: '#FFFFFF', name: 'Dark Green Blue' },
    { bg: '#017374', fg: '#FFFFFF', name: 'Deep Turquoise' },
    { bg: '#0CB577', fg: '#FFFFFF', name: 'Green Teal' },
    { bg: '#FF0789', fg: '#FFFFFF', name: 'Strong Pink' },
    { bg: '#AFA88B', fg: '#FFFFFF', name: 'Bland' },
    { bg: '#08787F', fg: '#FFFFFF', name: 'Deep Aqua' },
    { bg: '#DD85D7', fg: '#FFFFFF', name: 'Lavender Pink' },
    { bg: '#A6C875', fg: '#FFFFFF', name: 'Light Moss Green' },
    { bg: '#A7FFB5', fg: '#000000', name: 'Light Seafoam Green' },
    { bg: '#C2B709', fg: '#FFFFFF', name: 'Olive Yellow' },
    { bg: '#E78EA5', fg: '#FFFFFF', name: 'Pig Pink' },
    { bg: '#966EBD', fg: '#FFFFFF', name: 'Deep Lilac' },
    { bg: '#CCAD60', fg: '#FFFFFF', name: 'Desert' },
    { bg: '#AC86A8', fg: '#FFFFFF', name: 'Dusty Lavender' },
    { bg: '#947E94', fg: '#FFFFFF', name: 'Purpley Grey' },
    { bg: '#983FB2', fg: '#FFFFFF', name: 'Purply' },
    { bg: '#FF63E9', fg: '#FFFFFF', name: 'Candy Pink' },
    { bg: '#B2FBA5', fg: '#000000', name: 'Light Pastel Green' },
    { bg: '#63B365', fg: '#FFFFFF', name: 'Boring Green' },
    // { bg: '#8EE53F', fg: '#FFFFFF', name: 'Kiwi Green' },
    { bg: '#B7E1A1', fg: '#000000', name: 'Light Grey Green' },
    { bg: '#FF6F52', fg: '#FFFFFF', name: 'Orange Pink' },
    { bg: '#BDF8A3', fg: '#000000', name: 'Tea Green' },
    { bg: '#D3B683', fg: '#FFFFFF', name: 'Very Light Brown' },
    { bg: '#430541', fg: '#FFFFFF', name: 'Eggplant Purple' },
    { bg: '#FFB2D0', fg: '#000000', name: 'Powder Pink' },
    { bg: '#997570', fg: '#FFFFFF', name: 'Reddish Grey' },
    { bg: '#AD900D', fg: '#FFFFFF', name: 'Baby Shit Brown' },
    { bg: '#C48EFD', fg: '#FFFFFF', name: 'Liliac' },
    { bg: '#507B9C', fg: '#FFFFFF', name: 'Stormy Blue' },
    { bg: '#7D7103', fg: '#FFFFFF', name: 'Ugly Brown' },
    { bg: '#FFFD78', fg: '#000000', name: 'Custard' },
    { bg: '#DA467D', fg: '#FFFFFF', name: 'Darkish Pink' },
    { bg: '#410200', fg: '#FFFFFF', name: 'Deep Brown' },
    { bg: '#C9D179', fg: '#FFFFFF', name: 'Greenish Beige' },
    { bg: '#FFFA86', fg: '#000000', name: 'Manilla' },
    { bg: '#5684AE', fg: '#FFFFFF', name: 'Off Blue' },
    { bg: '#6B7C85', fg: '#FFFFFF', name: 'Battleship Grey' },
    { bg: '#6F6C0A', fg: '#FFFFFF', name: 'Browny Green' },
    { bg: '#7E4071', fg: '#FFFFFF', name: 'Bruise' },
    { bg: '#009337', fg: '#FFFFFF', name: 'Kelley Green' },
    { bg: '#D0E429', fg: '#000000', name: 'Sickly Yellow' },
    { bg: '#FFF917', fg: '#000000', name: 'Sunny Yellow' },
    { bg: '#1D5DEC', fg: '#FFFFFF', name: 'Azul' },
    { bg: '#054907', fg: '#FFFFFF', name: 'Darkgreen' },
    { bg: '#B5CE08', fg: '#FFFFFF', name: 'Green/Yellow' },
    { bg: '#8FB67B', fg: '#FFFFFF', name: 'Lichen' },
    { bg: '#C8FFB0', fg: '#000000', name: 'Light Light Green' },
    { bg: '#FDDE6C', fg: '#000000', name: 'Pale Gold' },
    { bg: '#FFDF22', fg: '#000000', name: 'Sun Yellow' },
    { bg: '#A9BE70', fg: '#FFFFFF', name: 'Tan Green' },
    { bg: '#6832E3', fg: '#FFFFFF', name: 'Burple' },
    { bg: '#FDB147', fg: '#FFFFFF', name: 'Butterscotch' },
    { bg: '#C7AC7D', fg: '#FFFFFF', name: 'Toupe' },
    { bg: '#FFF39A', fg: '#000000', name: 'Dark Cream' },
    { bg: '#850E04', fg: '#FFFFFF', name: 'Indian Red' },
    { bg: '#EFC0FE', fg: '#000000', name: 'Light Lavendar' },
    // { bg: '#40FD14', fg: '#FFFFFF', name: 'Poison Green' },
    { bg: '#B6C406', fg: '#FFFFFF', name: 'Baby Puke Green' },
    // { bg: '#9DFF00', fg: '#FFFFFF', name: 'Bright Yellow Green' },
    { bg: '#3C4142', fg: '#FFFFFF', name: 'Charcoal Grey' },
    { bg: '#F2AB15', fg: '#FFFFFF', name: 'Squash' },
    { bg: '#AC4F06', fg: '#FFFFFF', name: 'Cinnamon' },
    { bg: '#C4FE82', fg: '#000000', name: 'Light Pea Green' },
    { bg: '#2CFA1F', fg: '#FFFFFF', name: 'Radioactive Green' },
    { bg: '#9A6200', fg: '#FFFFFF', name: 'Raw Sienna' },
    { bg: '#CA9BF7', fg: '#FFFFFF', name: 'Baby Purple' },
    { bg: '#875F42', fg: '#FFFFFF', name: 'Cocoa' },
    { bg: '#3A2EFE', fg: '#FFFFFF', name: 'Light Royal Blue' },
    { bg: '#FD8D49', fg: '#FFFFFF', name: 'Orangeish' },
    { bg: '#8B3103', fg: '#FFFFFF', name: 'Rust Brown' },
    { bg: '#CBA560', fg: '#FFFFFF', name: 'Sand Brown' },
    { bg: '#698339', fg: '#FFFFFF', name: 'Swamp' },
    { bg: '#0CDC73', fg: '#FFFFFF', name: 'Tealish Green' },
    { bg: '#B75203', fg: '#FFFFFF', name: 'Burnt Siena' },
    { bg: '#7F8F4E', fg: '#FFFFFF', name: 'Camo' },
    { bg: '#26538D', fg: '#FFFFFF', name: 'Dusk Blue' },
    { bg: '#63A950', fg: '#FFFFFF', name: 'Fern' },
    { bg: '#C87F89', fg: '#FFFFFF', name: 'Old Rose' },
    { bg: '#B1FC99', fg: '#000000', name: 'Pale Light Green' },
    { bg: '#FF9A8A', fg: '#FFFFFF', name: 'Peachy Pink' },
    { bg: '#F6688E', fg: '#FFFFFF', name: 'Rosy Pink' },
    { bg: '#76FDA8', fg: '#000000', name: 'Light Bluish Green' },
    { bg: '#53FE5C', fg: '#FFFFFF', name: 'Light Bright Green' },
    { bg: '#4EFD54', fg: '#FFFFFF', name: 'Light Neon Green' },
    { bg: '#A0FEBF', fg: '#000000', name: 'Light Seafoam' },
    { bg: '#7BF2DA', fg: '#000000', name: 'Tiffany Blue' },
    { bg: '#BCF5A6', fg: '#000000', name: 'Washed Out Green' },
    { bg: '#CA6B02', fg: '#FFFFFF', name: 'Browny Orange' },
    { bg: '#107AB0', fg: '#FFFFFF', name: 'Nice Blue' },
    { bg: '#2138AB', fg: '#FFFFFF', name: 'Sapphire' },
    { bg: '#719F91', fg: '#FFFFFF', name: 'Greyish Teal' },
    { bg: '#FDB915', fg: '#FFFFFF', name: 'Orangey Yellow' },
    { bg: '#FEFCAF', fg: '#000000', name: 'Parchment' },
    { bg: '#FCF679', fg: '#000000', name: 'Straw' },
    { bg: '#CB6843', fg: '#FFFFFF', name: 'Terracota' },
    { bg: '#31668A', fg: '#FFFFFF', name: 'Ugly Blue' },
    { bg: '#247AFD', fg: '#FFFFFF', name: 'Clear Blue' },
    { bg: '#90FDA9', fg: '#000000', name: 'Foam Green' },
    { bg: '#86A17D', fg: '#FFFFFF', name: 'Grey/Green' },
    { bg: '#FDDC5C', fg: '#000000', name: 'Light Gold' },
    { bg: '#78D1B6', fg: '#FFFFFF', name: 'Seafoam Blue' },
    { bg: '#13BBAF', fg: '#FFFFFF', name: 'Topaz' },
    { bg: '#FB5FFC', fg: '#FFFFFF', name: 'Violet Pink' },
    { bg: '#20F986', fg: '#FFFFFF', name: 'Wintergreen' },
    { bg: '#FFE36E', fg: '#000000', name: 'Yellow Tan' },
    { bg: '#9D0759', fg: '#FFFFFF', name: 'Dark Fuchsia' },
    { bg: '#3A18B1', fg: '#FFFFFF', name: 'Indigo Blue' },
    { bg: '#C2FF89', fg: '#000000', name: 'Light Yellowish Green' },
    { bg: '#D767AD', fg: '#FFFFFF', name: 'Pale Magenta' },
    { bg: '#720058', fg: '#FFFFFF', name: 'Rich Purple' },
    { bg: '#FFDA03', fg: '#000000', name: 'Sunflower Yellow' },
    { bg: '#01C08D', fg: '#FFFFFF', name: 'Green/Blue' },
    { bg: '#AC7434', fg: '#FFFFFF', name: 'Leather' },
    { bg: '#014600', fg: '#FFFFFF', name: 'Racing Green' },
    { bg: '#9900FA', fg: '#FFFFFF', name: 'Vivid Purple' },
    { bg: '#02066F', fg: '#FFFFFF', name: 'Dark Royal Blue' },
    { bg: '#8E7618', fg: '#FFFFFF', name: 'Hazel' },
    { bg: '#D1768F', fg: '#FFFFFF', name: 'Muted Pink' },
    { bg: '#96B403', fg: '#FFFFFF', name: 'Booger Green' },
    { bg: '#FDFF63', fg: '#000000', name: 'Canary' },
    { bg: '#95A3A6', fg: '#FFFFFF', name: 'Cool Grey' },
    { bg: '#7F684E', fg: '#FFFFFF', name: 'Dark Taupe' },
    { bg: '#751973', fg: '#FFFFFF', name: 'Darkish Purple' },
    { bg: '#089404', fg: '#FFFFFF', name: 'True Green' },
    { bg: '#FF6163', fg: '#FFFFFF', name: 'Coral Pink' },
    { bg: '#598556', fg: '#FFFFFF', name: 'Dark Sage' },
    { bg: '#214761', fg: '#FFFFFF', name: 'Dark Slate Blue' },
    { bg: '#3C73A8', fg: '#FFFFFF', name: 'Flat Blue' },
    { bg: '#BA9E88', fg: '#FFFFFF', name: 'Mushroom' },
    { bg: '#021BF9', fg: '#FFFFFF', name: 'Rich Blue' },
    { bg: '#734A65', fg: '#FFFFFF', name: 'Dirty Purple' },
    { bg: '#23C48B', fg: '#FFFFFF', name: 'Greenblue' },
    { bg: '#8FAE22', fg: '#FFFFFF', name: 'Icky Green' },
    { bg: '#E6F2A2', fg: '#000000', name: 'Light Khaki' },
    { bg: '#4B57DB', fg: '#FFFFFF', name: 'Warm Blue' },
    { bg: '#D90166', fg: '#FFFFFF', name: 'Dark Hot Pink' },
    { bg: '#015482', fg: '#FFFFFF', name: 'Deep Sea Blue' },
    { bg: '#9D0216', fg: '#FFFFFF', name: 'Carmine' },
    { bg: '#728F02', fg: '#FFFFFF', name: 'Dark Yellow Green' },
    { bg: '#FFE5AD', fg: '#000000', name: 'Pale Peach' },
    { bg: '#4E0550', fg: '#FFFFFF', name: 'Plum Purple' },
    { bg: '#F9BC08', fg: '#FFFFFF', name: 'Golden Rod' },
    { bg: '#FF073A', fg: '#FFFFFF', name: 'Neon Red' },
    { bg: '#C77986', fg: '#FFFFFF', name: 'Old Pink' },
    { bg: '#D6FFFE', fg: '#000000', name: 'Very Pale Blue' },
    { bg: '#FE4B03', fg: '#FFFFFF', name: 'Blood Orange' },
    { bg: '#FD5956', fg: '#FFFFFF', name: 'Grapefruit' },
    { bg: '#FCE166', fg: '#000000', name: 'Sand Yellow' },
    { bg: '#B2713D', fg: '#FFFFFF', name: 'Clay Brown' },
    { bg: '#1F3B4D', fg: '#FFFFFF', name: 'Dark Blue Grey' },
    { bg: '#699D4C', fg: '#FFFFFF', name: 'Flat Green' },
    { bg: '#56FCA2', fg: '#FFFFFF', name: 'Light Green Blue' },
    { bg: '#FB5581', fg: '#FFFFFF', name: 'Warm Pink' },
    { bg: '#3E82FC', fg: '#FFFFFF', name: 'Dodger Blue' },
    { bg: '#A0BF16', fg: '#FFFFFF', name: 'Gross Green' },
    { bg: '#D6FFFA', fg: '#000000', name: 'Ice' },
    { bg: '#4F738E', fg: '#FFFFFF', name: 'Metallic Blue' },
    { bg: '#FFB19A', fg: '#FFFFFF', name: 'Pale Salmon' },
    { bg: '#5C8B15', fg: '#FFFFFF', name: 'Sap Green' },
    { bg: '#54AC68', fg: '#FFFFFF', name: 'Algae' },
    { bg: '#89A0B0', fg: '#FFFFFF', name: 'Bluey Grey' },
    { bg: '#7EA07A', fg: '#FFFFFF', name: 'Greeny Grey' },
    { bg: '#1BFC06', fg: '#FFFFFF', name: 'Highlighter Green' },
    { bg: '#CAFFFB', fg: '#000000', name: 'Light Light Blue' },
    { bg: '#B6FFBB', fg: '#000000', name: 'Light Mint' },
    { bg: '#A75E09', fg: '#FFFFFF', name: 'Raw Umber' },
    { bg: '#152EFF', fg: '#FFFFFF', name: 'Vivid Blue' },
    { bg: '#8D5EB7', fg: '#FFFFFF', name: 'Deep Lavender' },
    { bg: '#5F9E8F', fg: '#FFFFFF', name: 'Dull Teal' },
    // { bg: '#63F7B4', fg: '#FFFFFF', name: 'Light Greenish Blue' },
    { bg: '#606602', fg: '#FFFFFF', name: 'Mud Green' },
    { bg: '#FC86AA', fg: '#FFFFFF', name: 'Pinky' },
    { bg: '#8C0034', fg: '#FFFFFF', name: 'Red Wine' },
    { bg: '#758000', fg: '#FFFFFF', name: 'Shit Green' },
    { bg: '#AB7E4C', fg: '#FFFFFF', name: 'Tan Brown' },
    { bg: '#030764', fg: '#FFFFFF', name: 'Darkblue' },
    { bg: '#FE86A4', fg: '#FFFFFF', name: 'Rosa' },
    { bg: '#D5174E', fg: '#FFFFFF', name: 'Lipstick' },
    { bg: '#FED0FC', fg: '#000000', name: 'Pale Mauve' },
    { bg: '#680018', fg: '#FFFFFF', name: 'Claret' },
    { bg: '#FEDF08', fg: '#000000', name: 'Dandelion' },
    { bg: '#FE420F', fg: '#FFFFFF', name: 'Orangered' },
    { bg: '#6F7C00', fg: '#FFFFFF', name: 'Poop Green' },
    { bg: '#CA0147', fg: '#FFFFFF', name: 'Ruby' },
    { bg: '#1B2431', fg: '#FFFFFF', name: 'Dark' },
    // { bg: '#00FBB0', fg: '#FFFFFF', name: 'Greenish Turquoise' },
    { bg: '#DB5856', fg: '#FFFFFF', name: 'Pastel Red' },
    { bg: '#DDD618', fg: '#FFFFFF', name: 'Piss Yellow' },
    // { bg: '#41FDFE', fg: '#FFFFFF', name: 'Bright Cyan' },
    { bg: '#CF524E', fg: '#FFFFFF', name: 'Dark Coral' },
    { bg: '#21C36F', fg: '#FFFFFF', name: 'Algae Green' },
    { bg: '#A90308', fg: '#FFFFFF', name: 'Darkish Red' },
    { bg: '#6E1005', fg: '#FFFFFF', name: 'Reddy Brown' },
    { bg: '#FE828C', fg: '#FFFFFF', name: 'Blush Pink' },
    { bg: '#4B6113', fg: '#FFFFFF', name: 'Camouflage Green' },
    { bg: '#4DA409', fg: '#FFFFFF', name: 'Lawn Green' },
    { bg: '#BEAE8A', fg: '#FFFFFF', name: 'Putty' },
    { bg: '#0339F8', fg: '#FFFFFF', name: 'Vibrant Blue' },
    { bg: '#A88F59', fg: '#FFFFFF', name: 'Dark Sand' },
    { bg: '#5D21D0', fg: '#FFFFFF', name: 'Purple/Blue' },
    { bg: '#FEB209', fg: '#FFFFFF', name: 'Saffron' },
    { bg: '#4E518B', fg: '#FFFFFF', name: 'Twilight' },
    { bg: '#964E02', fg: '#FFFFFF', name: 'Warm Brown' },
    { bg: '#85A3B2', fg: '#FFFFFF', name: 'Bluegrey' },
    { bg: '#FF69AF', fg: '#FFFFFF', name: 'Bubble Gum Pink' },
    { bg: '#C3FBF4', fg: '#000000', name: 'Duck Egg Blue' },
    { bg: '#2AFEB7', fg: '#FFFFFF', name: 'Greenish Cyan' },
    { bg: '#005F6A', fg: '#FFFFFF', name: 'Petrol' },
    { bg: '#0C1793', fg: '#FFFFFF', name: 'Royal' },
    { bg: '#FFFF81', fg: '#000000', name: 'Butter' },
    { bg: '#F0833A', fg: '#FFFFFF', name: 'Dusty Orange' },
    { bg: '#F1F33F', fg: '#000000', name: 'Off Yellow' },
    { bg: '#B1D27B', fg: '#FFFFFF', name: 'Pale Olive Green' },
    { bg: '#FC824A', fg: '#FFFFFF', name: 'Orangish' },
    { bg: '#71AA34', fg: '#FFFFFF', name: 'Leaf' },
    { bg: '#B7C9E2', fg: '#FFFFFF', name: 'Light Blue Grey' },
    { bg: '#4B0101', fg: '#FFFFFF', name: 'Dried Blood' },
    { bg: '#A552E6', fg: '#FFFFFF', name: 'Lightish Purple' },
    { bg: '#AF2F0D', fg: '#FFFFFF', name: 'Rusty Red' },
    { bg: '#8B88F8', fg: '#FFFFFF', name: 'Lavender Blue' },
    { bg: '#9AF764', fg: '#000000', name: 'Light Grass Green' },
    { bg: '#A6FBB2', fg: '#000000', name: 'Light Mint Green' },
    { bg: '#FFC512', fg: '#FFFFFF', name: 'Sunflower' },
    { bg: '#750851', fg: '#FFFFFF', name: 'Velvet' },
    { bg: '#C14A09', fg: '#FFFFFF', name: 'Brick Orange' },
    { bg: '#FE2F4A', fg: '#FFFFFF', name: 'Lightish Red' },
    { bg: '#0203E2', fg: '#FFFFFF', name: 'Pure Blue' },
    { bg: '#0A437A', fg: '#FFFFFF', name: 'Twilight Blue' },
    { bg: '#A50055', fg: '#FFFFFF', name: 'Violet Red' },
    { bg: '#AE8B0C', fg: '#FFFFFF', name: 'Yellowy Brown' },
    { bg: '#FD798F', fg: '#FFFFFF', name: 'Carnation' },
    { bg: '#BFAC05', fg: '#FFFFFF', name: 'Muddy Yellow' },
    { bg: '#3EAF76', fg: '#FFFFFF', name: 'Dark Seafoam Green' },
    { bg: '#C74767', fg: '#FFFFFF', name: 'Deep Rose' },
    { bg: '#B9484E', fg: '#FFFFFF', name: 'Dusty Red' },
    { bg: '#647D8E', fg: '#FFFFFF', name: 'Grey/Blue' },
    { bg: '#BFFE28', fg: '#000000', name: 'Lemon Lime' },
    { bg: '#D725DE', fg: '#FFFFFF', name: 'Purple/Pink' },
    { bg: '#B29705', fg: '#FFFFFF', name: 'Brown Yellow' },
    { bg: '#673A3F', fg: '#FFFFFF', name: 'Purple Brown' },
    { bg: '#A87DC2', fg: '#FFFFFF', name: 'Wisteria' },
    { bg: '#FAFE4B', fg: '#000000', name: 'Banana Yellow' },
    { bg: '#C0022F', fg: '#FFFFFF', name: 'Lipstick Red' },
    { bg: '#0E87CC', fg: '#FFFFFF', name: 'Water Blue' },
    { bg: '#8D8468', fg: '#FFFFFF', name: 'Brown Grey' },
    { bg: '#AD03DE', fg: '#FFFFFF', name: 'Vibrant Purple' },
    { bg: '#8CFF9E', fg: '#000000', name: 'Baby Green' },
    { bg: '#94AC02', fg: '#FFFFFF', name: 'Barf Green' },
    { bg: '#C4FFF7', fg: '#000000', name: 'Eggshell Blue' },
    { bg: '#FDEE73', fg: '#000000', name: 'Sandy Yellow' },
    { bg: '#33B864', fg: '#FFFFFF', name: 'Cool Green' },
    { bg: '#758DA3', fg: '#FFFFFF', name: 'Blue/Grey' },
    { bg: '#F504C9', fg: '#FFFFFF', name: 'Hot Magenta' },
    { bg: '#77A1B5', fg: '#FFFFFF', name: 'Greyblue' },
    { bg: '#8756E4', fg: '#FFFFFF', name: 'Purpley' },
    { bg: '#889717', fg: '#FFFFFF', name: 'Baby Shit Green' },
    { bg: '#C27E79', fg: '#FFFFFF', name: 'Brownish Pink' },
    { bg: '#017371', fg: '#FFFFFF', name: 'Dark Aquamarine' },
    { bg: '#9F8303', fg: '#FFFFFF', name: 'Diarrhea' },
    { bg: '#F7D560', fg: '#000000', name: 'Light Mustard' },
    { bg: '#BDF6FE', fg: '#000000', name: 'Pale Sky Blue' },
    { bg: '#75B84F', fg: '#FFFFFF', name: 'Turtle Green' },
    { bg: '#9CBB04', fg: '#FFFFFF', name: 'Bright Olive' },
    { bg: '#29465B', fg: '#FFFFFF', name: 'Dark Grey Blue' },
    { bg: '#696006', fg: '#FFFFFF', name: 'Greeny Brown' },
    // { bg: '#ADF802', fg: '#FFFFFF', name: 'Lemon Green' },
    { bg: '#C1C6FC', fg: '#000000', name: 'Light Periwinkle' },
    { bg: '#35AD6B', fg: '#FFFFFF', name: 'Seaweed Green' },
    { bg: '#FFFD37', fg: '#000000', name: 'Sunshine Yellow' },
    { bg: '#A442A0', fg: '#FFFFFF', name: 'Ugly Purple' },
    { bg: '#F36196', fg: '#FFFFFF', name: 'Medium Pink' },
    { bg: '#947706', fg: '#FFFFFF', name: 'Puke Brown' },
    { bg: '#1E9167', fg: '#FFFFFF', name: 'Viridian' },
    { bg: '#B5C306', fg: '#FFFFFF', name: 'Bile' },
    { bg: '#FEFF7F', fg: '#000000', name: 'Faded Yellow' },
    { bg: '#CFFDBC', fg: '#000000', name: 'Very Pale Green' },
    { bg: '#0ADD08', fg: '#FFFFFF', name: 'Vibrant Green' },
    { bg: '#87FD05', fg: '#FFFFFF', name: 'Bright Lime' },
    { bg: '#1EF876', fg: '#FFFFFF', name: 'Spearmint' },
    { bg: '#7BFDC7', fg: '#000000', name: 'Light Aquamarine' },
    { bg: '#BCECAC', fg: '#000000', name: 'Light Sage' },
    { bg: '#BBF90F', fg: '#000000', name: 'Yellowgreen' },
    { bg: '#AB9004', fg: '#FFFFFF', name: 'Baby Poo' },
    { bg: '#1FB57A', fg: '#FFFFFF', name: 'Dark Seafoam' },
    { bg: '#00555A', fg: '#FFFFFF', name: 'Deep Teal' },
    { bg: '#A484AC', fg: '#FFFFFF', name: 'Heather' },
    { bg: '#C45508', fg: '#FFFFFF', name: 'Rust Orange' },
    { bg: '#3F829D', fg: '#FFFFFF', name: 'Dirty Blue' },
    { bg: '#548D44', fg: '#FFFFFF', name: 'Fern Green' },
    { bg: '#C95EFB', fg: '#FFFFFF', name: 'Bright Lilac' },
    { bg: '#3AE57F', fg: '#FFFFFF', name: 'Weird Green' },
    { bg: '#016795', fg: '#FFFFFF', name: 'Peacock Blue' },
    { bg: '#87A922', fg: '#FFFFFF', name: 'Avocado Green' },
    { bg: '#F0944D', fg: '#FFFFFF', name: 'Faded Orange' },
    { bg: '#5D1451', fg: '#FFFFFF', name: 'Grape Purple' },
    // { bg: '#25FF29', fg: '#FFFFFF', name: 'Hot Green' },
    { bg: '#D0FE1D', fg: '#000000', name: 'Lime Yellow' },
    { bg: '#FFA62B', fg: '#FFFFFF', name: 'Mango' },
    { bg: '#01B44C', fg: '#FFFFFF', name: 'Shamrock' },
    { bg: '#FF6CB5', fg: '#FFFFFF', name: 'Bubblegum' },
    { bg: '#6B4247', fg: '#FFFFFF', name: 'Purplish Brown' },
    { bg: '#C7C10C', fg: '#FFFFFF', name: 'Vomit Yellow' },
    { bg: '#B7FFFA', fg: '#000000', name: 'Pale Cyan' },
    { bg: '#AEFF6E', fg: '#000000', name: 'Key Lime' },
    { bg: '#EC2D01', fg: '#FFFFFF', name: 'Tomato Red' },
    { bg: '#76FF7B', fg: '#FFFFFF', name: 'Lightgreen' },
    { bg: '#730039', fg: '#FFFFFF', name: 'Merlot' },
    { bg: '#040348', fg: '#FFFFFF', name: 'Night Blue' },
    { bg: '#DF4EC8', fg: '#FFFFFF', name: 'Purpleish Pink' },
    { bg: '#6ECB3C', fg: '#FFFFFF', name: 'Apple' },
    { bg: '#8F9805', fg: '#FFFFFF', name: 'Baby Poop Green' },
    { bg: '#5EDC1F', fg: '#FFFFFF', name: 'Green Apple' },
    { bg: '#D94FF5', fg: '#FFFFFF', name: 'Heliotrope' },
    { bg: '#C8FD3D', fg: '#000000', name: 'Yellow/Green' },
    { bg: '#070D0D', fg: '#FFFFFF', name: 'Almost Black' },
    { bg: '#4984B8', fg: '#FFFFFF', name: 'Cool Blue' },
    { bg: '#51B73B', fg: '#FFFFFF', name: 'Leafy Green' },
    { bg: '#AC7E04', fg: '#FFFFFF', name: 'Mustard Brown' },
    { bg: '#4E5481', fg: '#FFFFFF', name: 'Dusk' },
    { bg: '#876E4B', fg: '#FFFFFF', name: 'Dull Brown' },
    { bg: '#58BC08', fg: '#FFFFFF', name: 'Frog Green' },
    { bg: '#2FEF10', fg: '#FFFFFF', name: 'Vivid Green' },
    { bg: '#2DFE54', fg: '#FFFFFF', name: 'Bright Light Green' },
    // { bg: '#0AFF02', fg: '#FFFFFF', name: 'Fluro Green' },
    { bg: '#9CEF43', fg: '#FFFFFF', name: 'Kiwi' },
    { bg: '#18D17B', fg: '#FFFFFF', name: 'Seaweed' },
    { bg: '#35530A', fg: '#FFFFFF', name: 'Navy Green' },
    { bg: '#1805DB', fg: '#FFFFFF', name: 'Ultramarine Blue' },
    { bg: '#6258C4', fg: '#FFFFFF', name: 'Iris' },
    { bg: '#FF964F', fg: '#FFFFFF', name: 'Pastel Orange' },
    { bg: '#FFAB0F', fg: '#FFFFFF', name: 'Yellowish Orange' },
    { bg: '#8F8CE7', fg: '#FFFFFF', name: 'Perrywinkle' },
    { bg: '#24BCA8', fg: '#FFFFFF', name: 'Tealish' },
    { bg: '#3F012C', fg: '#FFFFFF', name: 'Dark Plum' },
    { bg: '#CBF85F', fg: '#000000', name: 'Pear' },
    { bg: '#FF724C', fg: '#FFFFFF', name: 'Pinkish Orange' },
    { bg: '#280137', fg: '#FFFFFF', name: 'Midnight Purple' },
    { bg: '#B36FF6', fg: '#FFFFFF', name: 'Light Urple' },
    { bg: '#48C072', fg: '#FFFFFF', name: 'Dark Mint' },
    { bg: '#BCCB7A', fg: '#FFFFFF', name: 'Greenish Tan' },
    { bg: '#A8415B', fg: '#FFFFFF', name: 'Light Burgundy' },
    { bg: '#06B1C4', fg: '#FFFFFF', name: 'Turquoise Blue' },
    { bg: '#CD7584', fg: '#FFFFFF', name: 'Ugly Pink' },
    { bg: '#F1DA7A', fg: '#000000', name: 'Sandy' },
    { bg: '#FF0490', fg: '#FFFFFF', name: 'Electric Pink' },
    { bg: '#805B87', fg: '#FFFFFF', name: 'Muted Purple' },
    { bg: '#50A747', fg: '#FFFFFF', name: 'Mid Green' },
    { bg: '#A8A495', fg: '#FFFFFF', name: 'Greyish' },
    { bg: '#CFFF04', fg: '#000000', name: 'Neon Yellow' },
    { bg: '#FFFF7E', fg: '#000000', name: 'Banana' },
    { bg: '#FF7FA7', fg: '#FFFFFF', name: 'Carnation Pink' },
    { bg: '#EF4026', fg: '#FFFFFF', name: 'Tomato' },
    { bg: '#3C9992', fg: '#FFFFFF', name: 'Sea' },
    { bg: '#886806', fg: '#FFFFFF', name: 'Muddy Brown' },
    { bg: '#04F489', fg: '#FFFFFF', name: 'Turquoise Green' },
    { bg: '#FEF69E', fg: '#000000', name: 'Buff' },
    { bg: '#CFAF7B', fg: '#FFFFFF', name: 'Fawn' },
    { bg: '#3B719F', fg: '#FFFFFF', name: 'Muted Blue' },
    { bg: '#FDC1C5', fg: '#000000', name: 'Pale Rose' },
    { bg: '#20C073', fg: '#FFFFFF', name: 'Dark Mint Green' },
    { bg: '#9B5FC0', fg: '#FFFFFF', name: 'Amethyst' },
    { bg: '#0F9B8E', fg: '#FFFFFF', name: 'Blue/Green' },
    { bg: '#742802', fg: '#FFFFFF', name: 'Chestnut' },
    { bg: '#9DB92C', fg: '#FFFFFF', name: 'Sick Green' },
    { bg: '#A4BF20', fg: '#FFFFFF', name: 'Pea' },
    { bg: '#CD5909', fg: '#FFFFFF', name: 'Rusty Orange' },
    { bg: '#ADA587', fg: '#FFFFFF', name: 'Stone' },
    { bg: '#BE013C', fg: '#FFFFFF', name: 'Rose Red' },
    { bg: '#B8FFEB', fg: '#000000', name: 'Pale Aqua' },
    { bg: '#DC4D01', fg: '#FFFFFF', name: 'Deep Orange' },
    { bg: '#A2653E', fg: '#FFFFFF', name: 'Earth' },
    { bg: '#638B27', fg: '#FFFFFF', name: 'Mossy Green' },
    { bg: '#419C03', fg: '#FFFFFF', name: 'Grassy Green' },
    { bg: '#B1FF65', fg: '#000000', name: 'Pale Lime Green' },
    { bg: '#9DBCD4', fg: '#FFFFFF', name: 'Light Grey Blue' },
    { bg: '#77AB56', fg: '#FFFFFF', name: 'Asparagus' },
    { bg: '#464196', fg: '#FFFFFF', name: 'Blueberry' },
    { bg: '#990147', fg: '#FFFFFF', name: 'Purple Red' },
    { bg: '#BEFD73', fg: '#000000', name: 'Pale Lime' },
    { bg: '#32BF84', fg: '#FFFFFF', name: 'Greenish Teal' },
    { bg: '#AF6F09', fg: '#FFFFFF', name: 'Caramel' },
    { bg: '#A0025C', fg: '#FFFFFF', name: 'Deep Magenta' },
    { bg: '#FFD8B1', fg: '#000000', name: 'Light Peach' },
    { bg: '#7F4E1E', fg: '#FFFFFF', name: 'Milk Chocolate' },
    { bg: '#BF9B0C', fg: '#FFFFFF', name: 'Ocher' },
    { bg: '#6BA353', fg: '#FFFFFF', name: 'Off Green' },
    { bg: '#F075E6', fg: '#FFFFFF', name: 'Purply Pink' },
    { bg: '#7BC8F6', fg: '#FFFFFF', name: 'Lightblue' },
    { bg: '#475F94', fg: '#FFFFFF', name: 'Dusky Blue' },
    { bg: '#F5BF03', fg: '#FFFFFF', name: 'Golden' },
    { bg: '#FFFD74', fg: '#000000', name: 'Butter Yellow' },
    { bg: '#895B7B', fg: '#FFFFFF', name: 'Dusky Purple' },
    { bg: '#436BAD', fg: '#FFFFFF', name: 'French Blue' },
    { bg: '#D0C101', fg: '#FFFFFF', name: 'Ugly Yellow' },
    { bg: '#C6F808', fg: '#000000', name: 'Greeny Yellow' },
    { bg: '#F43605', fg: '#FFFFFF', name: 'Orangish Red' },
    { bg: '#02C14D', fg: '#FFFFFF', name: 'Shamrock Green' },
    { bg: '#B25F03', fg: '#FFFFFF', name: 'Orangish Brown' },
    { bg: '#2A7E19', fg: '#FFFFFF', name: 'Tree Green' },
    { bg: '#490648', fg: '#FFFFFF', name: 'Deep Violet' },
    { bg: '#536267', fg: '#FFFFFF', name: 'Gunmetal' },
    { bg: '#5A06EF', fg: '#FFFFFF', name: 'Blue/Purple' },
    { bg: '#CF0234', fg: '#FFFFFF', name: 'Cherry' },
    { bg: '#C4A661', fg: '#FFFFFF', name: 'Sandy Brown' },
    { bg: '#978A84', fg: '#FFFFFF', name: 'Warm Grey' },
    { bg: '#1F0954', fg: '#FFFFFF', name: 'Dark Indigo' },
    { bg: '#2BB179', fg: '#FFFFFF', name: 'Bluey Green' },
    { bg: '#C3909B', fg: '#FFFFFF', name: 'Grey Pink' },
    { bg: '#A66FB5', fg: '#FFFFFF', name: 'Soft Purple' },
    { bg: '#770001', fg: '#FFFFFF', name: 'Blood' },
    { bg: '#922B05', fg: '#FFFFFF', name: 'Brown Red' },
    { bg: '#7D7F7C', fg: '#FFFFFF', name: 'Medium Grey' },
    { bg: '#990F4B', fg: '#FFFFFF', name: 'Berry' },
    { bg: '#8F7303', fg: '#FFFFFF', name: 'Poo' },
    { bg: '#C83CB9', fg: '#FFFFFF', name: 'Purpley Pink' },
    { bg: '#FEA993', fg: '#FFFFFF', name: 'Light Salmon' },
    { bg: '#ACBB0D', fg: '#FFFFFF', name: 'Snot' },
    { bg: '#C071FE', fg: '#FFFFFF', name: 'Easter Purple' },
    { bg: '#CCFD7F', fg: '#000000', name: 'Light Yellow Green' },
    { bg: '#828344', fg: '#FFFFFF', name: 'Drab' },
    { bg: '#FFC5CB', fg: '#000000', name: 'Light Rose' },
    { bg: '#AB1239', fg: '#FFFFFF', name: 'Rouge' },
    { bg: '#B0054B', fg: '#FFFFFF', name: 'Purplish Red' },
    { bg: '#99CC04', fg: '#FFFFFF', name: 'Slime Green' },
    { bg: '#937C00', fg: '#FFFFFF', name: 'Baby Poop' },
    { bg: '#019529', fg: '#FFFFFF', name: 'Irish Green' },
    { bg: '#EF1DE7', fg: '#FFFFFF', name: 'Pink/Purple' },
    { bg: '#42B395', fg: '#FFFFFF', name: 'Greeny Blue' },
    { bg: '#9D5783', fg: '#FFFFFF', name: 'Light Plum' },
    { bg: '#C8ACA9', fg: '#FFFFFF', name: 'Pinkish Grey' },
    { bg: '#C87606', fg: '#FFFFFF', name: 'Dirty Orange' },
    { bg: '#AA2704', fg: '#FFFFFF', name: 'Rust Red' },
    { bg: '#E4CBFF', fg: '#000000', name: 'Pale Lilac' },
    { bg: '#FA4224', fg: '#FFFFFF', name: 'Orangey Red' },
    { bg: '#0804F9', fg: '#FFFFFF', name: 'Primary Blue' },
    { bg: '#5CB200', fg: '#FFFFFF', name: 'Kermit Green' },
    { bg: '#76424E', fg: '#FFFFFF', name: 'Brownish Purple' },
    { bg: '#6C7A0E', fg: '#FFFFFF', name: 'Murky Green' },
    { bg: '#FBDD7E', fg: '#000000', name: 'Wheat' },
    { bg: '#2A0134', fg: '#FFFFFF', name: 'Very Dark Purple' },
    { bg: '#044A05', fg: '#FFFFFF', name: 'Bottle Green' },
    { bg: '#FD4659', fg: '#FFFFFF', name: 'Watermelon' },
    { bg: '#0D75F8', fg: '#FFFFFF', name: 'Deep Sky Blue' },
    { bg: '#FE0002', fg: '#FFFFFF', name: 'Fire Engine Red' },
    { bg: '#CB9D06', fg: '#FFFFFF', name: 'Yellow Ochre' },
    { bg: '#FB7D07', fg: '#FFFFFF', name: 'Pumpkin Orange' },
    { bg: '#B9CC81', fg: '#FFFFFF', name: 'Pale Olive' },
    { bg: '#EDC8FF', fg: '#000000', name: 'Light Lilac' },
    { bg: '#61E160', fg: '#FFFFFF', name: 'Lightish Green' },
    { bg: '#8AB8FE', fg: '#FFFFFF', name: 'Carolina Blue' },
    { bg: '#920A4E', fg: '#FFFFFF', name: 'Mulberry' },
    { bg: '#FE02A2', fg: '#FFFFFF', name: 'Shocking Pink' },
    { bg: '#9A3001', fg: '#FFFFFF', name: 'Auburn' },
    { bg: '#65FE08', fg: '#FFFFFF', name: 'Bright Lime Green' },
    { bg: '#BEFDB7', fg: '#000000', name: 'Celadon' },
    { bg: '#B17261', fg: '#FFFFFF', name: 'Pinkish Brown' },
    { bg: '#885F01', fg: '#FFFFFF', name: 'Poo Brown' },
    { bg: '#02CCFE', fg: '#FFFFFF', name: 'Bright Sky Blue' },
    { bg: '#C1FD95', fg: '#000000', name: 'Celery' },
    { bg: '#836539', fg: '#FFFFFF', name: 'Dirt Brown' },
    { bg: '#FB2943', fg: '#FFFFFF', name: 'Strawberry' },
    { bg: '#84B701', fg: '#FFFFFF', name: 'Dark Lime' },
    { bg: '#B66325', fg: '#FFFFFF', name: 'Copper' },
    { bg: '#7F5112', fg: '#FFFFFF', name: 'Medium Brown' },
    { bg: '#5FA052', fg: '#FFFFFF', name: 'Muted Green' },
    { bg: '#6DEDFD', fg: '#000000', name: 'robins Egg' },
    { bg: '#0BF9EA', fg: '#FFFFFF', name: 'Bright Aqua' },
    { bg: '#C760FF', fg: '#FFFFFF', name: 'Bright Lavender' },
    { bg: '#F6CEFC', fg: '#000000', name: 'Very Light Purple' },
    { bg: '#155084', fg: '#FFFFFF', name: 'Light Navy' },
    { bg: '#F5054F', fg: '#FFFFFF', name: 'Pink Red' },
    { bg: '#645403', fg: '#FFFFFF', name: 'Olive Brown' },
    { bg: '#7A5901', fg: '#FFFFFF', name: 'Poop Brown' },
    { bg: '#A8B504', fg: '#FFFFFF', name: 'Mustard Green' },
    { bg: '#3D9973', fg: '#FFFFFF', name: 'Ocean Green' },
    { bg: '#76A973', fg: '#FFFFFF', name: 'Dusty Green' },
    { bg: '#2E5A88', fg: '#FFFFFF', name: 'Light Navy Blue' },
    { bg: '#0BF77D', fg: '#FFFFFF', name: 'Minty Green' },
    { bg: '#BD6C48', fg: '#FFFFFF', name: 'Adobe' },
    { bg: '#AC1DB8', fg: '#FFFFFF', name: 'Barney' },
    { bg: '#2BAF6A', fg: '#FFFFFF', name: 'Jade Green' },
    { bg: '#26F7FD', fg: '#FFFFFF', name: 'Bright Light Blue' },
    { bg: '#AEFD6C', fg: '#000000', name: 'Light Lime' },
    { bg: '#9B8F55', fg: '#FFFFFF', name: 'Dark Khaki' },
    { bg: '#FFAD01', fg: '#FFFFFF', name: 'Orange Yellow' },
    { bg: '#C69C04', fg: '#FFFFFF', name: 'Ocre' },
    { bg: '#F4D054', fg: '#000000', name: 'Maize' },
    { bg: '#DE9DAC', fg: '#FFFFFF', name: 'Faded Pink' },
    { bg: '#05480D', fg: '#FFFFFF', name: 'British Racing Green' },
    { bg: '#C9AE74', fg: '#FFFFFF', name: 'Sandstone' },
    { bg: '#60460F', fg: '#FFFFFF', name: 'Mud Brown' },
    { bg: '#98F6B0', fg: '#000000', name: 'Light Sea Green' },
    { bg: '#8AF1FE', fg: '#000000', name: 'Robin Egg Blue' },
    { bg: '#2EE8BB', fg: '#FFFFFF', name: 'Aqua Marine' },
    { bg: '#11875D', fg: '#FFFFFF', name: 'Dark Sea Green' },
    { bg: '#FDB0C0', fg: '#000000', name: 'Soft Pink' },
    { bg: '#B16002', fg: '#FFFFFF', name: 'Orangey Brown' },
    { bg: '#F7022A', fg: '#FFFFFF', name: 'Cherry Red' },
    { bg: '#D5AB09', fg: '#FFFFFF', name: 'Burnt Yellow' },
    { bg: '#86775F', fg: '#FFFFFF', name: 'Brownish Grey' },
    { bg: '#C69F59', fg: '#FFFFFF', name: 'Camel' },
    { bg: '#7A687F', fg: '#FFFFFF', name: 'Purplish Grey' },
    { bg: '#042E60', fg: '#FFFFFF', name: 'Marine' },
    { bg: '#C88D94', fg: '#FFFFFF', name: 'Greyish Pink' },
    { bg: '#A5FBD5', fg: '#000000', name: 'Pale Turquoise' },
    { bg: '#FFFE71', fg: '#000000', name: 'Pastel Yellow' },
    { bg: '#6241C7', fg: '#FFFFFF', name: 'Bluey Purple' },
    { bg: '#FFFE40', fg: '#000000', name: 'Canary Yellow' },
    { bg: '#D3494E', fg: '#FFFFFF', name: 'Faded Red' },
    { bg: '#985E2B', fg: '#FFFFFF', name: 'Sepia' },
    { bg: '#A6814C', fg: '#FFFFFF', name: 'Coffee' },
    { bg: '#FF08E8', fg: '#FFFFFF', name: 'Bright Magenta' },
    { bg: '#9D7651', fg: '#FFFFFF', name: 'Mocha' },
    { bg: '#98568D', fg: '#FFFFFF', name: 'Purpleish' },
    { bg: '#9E003A', fg: '#FFFFFF', name: 'Cranberry' },
    { bg: '#287C37', fg: '#FFFFFF', name: 'Darkish Green' },
    { bg: '#B96902', fg: '#FFFFFF', name: 'Brown Orange' },
    { bg: '#BA6873', fg: '#FFFFFF', name: 'Dusky Rose' },
    { bg: '#FF7855', fg: '#FFFFFF', name: 'Melon' },
    { bg: '#94B21C', fg: '#FFFFFF', name: 'Sickly Green' },
    { bg: '#C5C9C7', fg: '#FFFFFF', name: 'Silver' },
    { bg: '#661AEE', fg: '#FFFFFF', name: 'Purply Blue' },
    { bg: '#6140EF', fg: '#FFFFFF', name: 'Purpleish Blue' },
    { bg: '#9BE5AA', fg: '#000000', name: 'Hospital Green' },
    { bg: '#7B5804', fg: '#FFFFFF', name: 'Shit Brown' },
    { bg: '#276AB3', fg: '#FFFFFF', name: 'Mid Blue' },
    { bg: '#FEB308', fg: '#FFFFFF', name: 'Amber' },
    { bg: '#8CFD7E', fg: '#000000', name: 'Easter Green' },
    { bg: '#6488EA', fg: '#FFFFFF', name: 'Soft Blue' },
    { bg: '#056EEE', fg: '#FFFFFF', name: 'Cerulean Blue' },
    { bg: '#B27A01', fg: '#FFFFFF', name: 'Golden Brown' },
    { bg: '#0FFEF9', fg: '#FFFFFF', name: 'Bright Turquoise' },
    { bg: '#FA2A55', fg: '#FFFFFF', name: 'Red Pink' },
    { bg: '#820747', fg: '#FFFFFF', name: 'Red Purple' },
    { bg: '#7A6A4F', fg: '#FFFFFF', name: 'Greyish Brown' },
    { bg: '#F4320C', fg: '#FFFFFF', name: 'Vermillion' },
    { bg: '#A13905', fg: '#FFFFFF', name: 'Russet' },
    { bg: '#6F828A', fg: '#FFFFFF', name: 'Steel Grey' },
    { bg: '#A55AF4', fg: '#FFFFFF', name: 'Lighter Purple' },
    { bg: '#AD0AFD', fg: '#FFFFFF', name: 'Bright Violet' },
    { bg: '#004577', fg: '#FFFFFF', name: 'Prussian Blue' },
    { bg: '#658D6D', fg: '#FFFFFF', name: 'Slate Green' },
    { bg: '#CA7B80', fg: '#FFFFFF', name: 'Dirty Pink' },
    { bg: '#005249', fg: '#FFFFFF', name: 'Dark Blue Green' },
    { bg: '#2B5D34', fg: '#FFFFFF', name: 'Pine' },
    { bg: '#BFF128', fg: '#000000', name: 'Yellowy Green' },
    { bg: '#B59410', fg: '#FFFFFF', name: 'Dark Gold' },
    { bg: '#2976BB', fg: '#FFFFFF', name: 'Bluish' },
    { bg: '#014182', fg: '#FFFFFF', name: 'Darkish Blue' },
    { bg: '#BB3F3F', fg: '#FFFFFF', name: 'Dull Red' },
    { bg: '#FC2647', fg: '#FFFFFF', name: 'Pinky Red' },
    { bg: '#A87900', fg: '#FFFFFF', name: 'Bronze' },
    { bg: '#82CBB2', fg: '#FFFFFF', name: 'Pale Teal' },
    { bg: '#667C3E', fg: '#FFFFFF', name: 'Military Green' },
    { bg: '#FE46A5', fg: '#FFFFFF', name: 'Barbie Pink' },
    { bg: '#FE83CC', fg: '#FFFFFF', name: 'Bubblegum Pink' },
    { bg: '#94A617', fg: '#FFFFFF', name: 'Pea Soup Green' },
    { bg: '#A88905', fg: '#FFFFFF', name: 'Dark Mustard' },
    { bg: '#7F5F00', fg: '#FFFFFF', name: 'Shit' },
    { bg: '#9E43A2', fg: '#FFFFFF', name: 'Medium Purple' },
    { bg: '#062E03', fg: '#FFFFFF', name: 'Very Dark Green' },
    { bg: '#8A6E45', fg: '#FFFFFF', name: 'Dirt' },
    { bg: '#CC7A8B', fg: '#FFFFFF', name: 'Dusky Pink' },
    { bg: '#9E0168', fg: '#FFFFFF', name: 'Red Violet' },
    { bg: '#FDFF38', fg: '#000000', name: 'Lemon Yellow' },
    { bg: '#C0FA8B', fg: '#000000', name: 'Pistachio' },
    { bg: '#EEDC5B', fg: '#000000', name: 'Dull Yellow' },
    { bg: '#7EBD01', fg: '#FFFFFF', name: 'Dark Lime Green' },
    { bg: '#3B5B92', fg: '#FFFFFF', name: 'Denim Blue' },
    { bg: '#01889F', fg: '#FFFFFF', name: 'Teal Blue' },
    { bg: '#3D7AFD', fg: '#FFFFFF', name: 'Lightish Blue' },
    { bg: '#5F34E7', fg: '#FFFFFF', name: 'Purpley Blue' },
    { bg: '#6D5ACF', fg: '#FFFFFF', name: 'Light Indigo' },
    { bg: '#748500', fg: '#FFFFFF', name: 'Swamp Green' },
    { bg: '#706C11', fg: '#FFFFFF', name: 'Brown Green' },
    { bg: '#3C0008', fg: '#FFFFFF', name: 'Dark Maroon' },
    { bg: '#CB00F5', fg: '#FFFFFF', name: 'Hot Purple' },
    { bg: '#002D04', fg: '#FFFFFF', name: 'Dark Forest Green' },
    { bg: '#658CBB', fg: '#FFFFFF', name: 'Faded Blue' },
    { bg: '#749551', fg: '#FFFFFF', name: 'Drab Green' },
    { bg: '#B9FF66', fg: '#000000', name: 'Light Lime Green' },
    { bg: '#9DC100', fg: '#FFFFFF', name: 'Snot Green' },
    { bg: '#FAEE66', fg: '#000000', name: 'Yellowish' },
    { bg: '#7EFBB3', fg: '#000000', name: 'Light Blue Green' },
    { bg: '#7B002C', fg: '#FFFFFF', name: 'Bordeaux' },
    { bg: '#C292A1', fg: '#FFFFFF', name: 'Light Mauve' },
    { bg: '#017B92', fg: '#FFFFFF', name: 'Ocean' },
    { bg: '#FCC006', fg: '#FFFFFF', name: 'Marigold' },
    { bg: '#657432', fg: '#FFFFFF', name: 'Muddy Green' },
    { bg: '#D8863B', fg: '#FFFFFF', name: 'Dull Orange' },
    { bg: '#738595', fg: '#FFFFFF', name: 'Steel' },
    { bg: '#AA23FF', fg: '#FFFFFF', name: 'Electric Purple' },
    // { bg: '#08FF08', fg: '#FFFFFF', name: 'Fluorescent Green' },
    { bg: '#9B7A01', fg: '#FFFFFF', name: 'Yellowish Brown' },
    { bg: '#F29E8E', fg: '#FFFFFF', name: 'Blush' },
    { bg: '#6FC276', fg: '#FFFFFF', name: 'Soft Green' },
    { bg: '#FF5B00', fg: '#FFFFFF', name: 'Bright Orange' },
    { bg: '#FDFF52', fg: '#000000', name: 'Lemon' },
    { bg: '#866F85', fg: '#FFFFFF', name: 'Purple Grey' },
    // { bg: '#8FFE09', fg: '#FFFFFF', name: 'Acid Green' },
    { bg: '#EECFFE', fg: '#000000', name: 'Pale Lavender' },
    { bg: '#510AC9', fg: '#FFFFFF', name: 'Violet Blue' },
    { bg: '#4F9153', fg: '#FFFFFF', name: 'Light Forest Green' },
    { bg: '#9F2305', fg: '#FFFFFF', name: 'Burnt Red' },
    { bg: '#728639', fg: '#FFFFFF', name: 'Khaki Green' },
    { bg: '#DE0C62', fg: '#FFFFFF', name: 'Cerise' },
    { bg: '#916E99', fg: '#FFFFFF', name: 'Faded Purple' },
    { bg: '#FFB16D', fg: '#FFFFFF', name: 'Apricot' },
    { bg: '#3C4D03', fg: '#FFFFFF', name: 'Dark Olive Green' },
    { bg: '#7F7053', fg: '#FFFFFF', name: 'Grey Brown' },
    { bg: '#77926F', fg: '#FFFFFF', name: 'Green Grey' },
    { bg: '#010FCC', fg: '#FFFFFF', name: 'True Blue' },
    { bg: '#CEAEFA', fg: '#FFFFFF', name: 'Pale Violet' },
    { bg: '#8F99FB', fg: '#FFFFFF', name: 'Periwinkle Blue' },
    { bg: '#C6FCFF', fg: '#000000', name: 'Light Sky Blue' },
    { bg: '#5539CC', fg: '#FFFFFF', name: 'Blurple' },
    { bg: '#544E03', fg: '#FFFFFF', name: 'Green Brown' },
    { bg: '#017A79', fg: '#FFFFFF', name: 'Bluegreen' },
    // { bg: '#01F9C6', fg: '#FFFFFF', name: 'Bright Teal' },
    { bg: '#C9B003', fg: '#FFFFFF', name: 'Brownish Yellow' },
    { bg: '#929901', fg: '#FFFFFF', name: 'Pea Soup' },
    { bg: '#0B5509', fg: '#FFFFFF', name: 'Forest' },
    { bg: '#A00498', fg: '#FFFFFF', name: 'Barney Purple' },
    { bg: '#2000B1', fg: '#FFFFFF', name: 'Ultramarine' },
    { bg: '#94568C', fg: '#FFFFFF', name: 'Purplish' },
    { bg: '#C2BE0E', fg: '#FFFFFF', name: 'Puke Yellow' },
    { bg: '#748B97', fg: '#FFFFFF', name: 'Bluish Grey' },
    { bg: '#665FD1', fg: '#FFFFFF', name: 'Dark Periwinkle' },
    { bg: '#9C6DA5', fg: '#FFFFFF', name: 'Dark Lilac' },
    { bg: '#C44240', fg: '#FFFFFF', name: 'Reddish' },
    { bg: '#A24857', fg: '#FFFFFF', name: 'Light Maroon' },
    { bg: '#825F87', fg: '#FFFFFF', name: 'Dusty Purple' },
    { bg: '#C9643B', fg: '#FFFFFF', name: 'Terra Cotta' },
    { bg: '#90B134', fg: '#FFFFFF', name: 'Avocado' },
    { bg: '#01386A', fg: '#FFFFFF', name: 'Marine Blue' },
    { bg: '#25A36F', fg: '#FFFFFF', name: 'Teal Green' },
    { bg: '#59656D', fg: '#FFFFFF', name: 'Slate Grey' },
    { bg: '#75FD63', fg: '#FFFFFF', name: 'Lighter Green' },
    { bg: '#21FC0D', fg: '#FFFFFF', name: 'Electric Green' },
    { bg: '#5A86AD', fg: '#FFFFFF', name: 'Dusty Blue' },
    { bg: '#FEC615', fg: '#FFFFFF', name: 'Golden Yellow' },
    { bg: '#FFFD01', fg: '#000000', name: 'Bright Yellow' },
    { bg: '#DFC5FE', fg: '#000000', name: 'Light Lavender' },
    { bg: '#B26400', fg: '#FFFFFF', name: 'Umber' },
    { bg: '#7F5E00', fg: '#FFFFFF', name: 'Poop' },
    { bg: '#DE7E5D', fg: '#FFFFFF', name: 'Dark Peach' },
    { bg: '#048243', fg: '#FFFFFF', name: 'Jungle Green' },
    { bg: '#3B638C', fg: '#FFFFFF', name: 'Denim' },
    { bg: '#B79400', fg: '#FFFFFF', name: 'Yellow Brown' },
    { bg: '#84597E', fg: '#FFFFFF', name: 'Dull Purple' },
    { bg: '#411900', fg: '#FFFFFF', name: 'Chocolate Brown' },
    { bg: '#7B0323', fg: '#FFFFFF', name: 'Wine Red' },
    { bg: '#04D9FF', fg: '#FFFFFF', name: 'Neon Blue' },
    { bg: '#667E2C', fg: '#FFFFFF', name: 'Dirty Green' },
    { bg: '#FBEEAC', fg: '#000000', name: 'Light Tan' },
    { bg: '#D7FFFE', fg: '#000000', name: 'Ice Blue' },
    { bg: '#4E7496', fg: '#FFFFFF', name: 'Cadet Blue' },
    { bg: '#874C62', fg: '#FFFFFF', name: 'Dark Mauve' },
    { bg: '#D5FFFF', fg: '#000000', name: 'Very Light Blue' },
    { bg: '#826D8C', fg: '#FFFFFF', name: 'Grey Purple' },
    { bg: '#FFBACD', fg: '#000000', name: 'Pastel Pink' },
    { bg: '#D1FFBD', fg: '#000000', name: 'Very Light Green' },
    { bg: '#448EE4', fg: '#FFFFFF', name: 'Dark Sky Blue' },
    { bg: '#05472A', fg: '#FFFFFF', name: 'Evergreen' },
    { bg: '#D5869D', fg: '#FFFFFF', name: 'Dull Pink' },
    { bg: '#3D0734', fg: '#FFFFFF', name: 'Aubergine' },
    { bg: '#4A0100', fg: '#FFFFFF', name: 'Mahogany' },
    { bg: '#F8481C', fg: '#FFFFFF', name: 'Reddish Orange' },
    { bg: '#02590F', fg: '#FFFFFF', name: 'Deep Green' },
    { bg: '#89A203', fg: '#FFFFFF', name: 'Vomit Green' },
    { bg: '#E03FD8', fg: '#FFFFFF', name: 'Purple Pink' },
    { bg: '#D58A94', fg: '#FFFFFF', name: 'Dusty Pink' },
    { bg: '#7BB274', fg: '#FFFFFF', name: 'Faded Green' },
    { bg: '#526525', fg: '#FFFFFF', name: 'Camo Green' },
    { bg: '#C94CBE', fg: '#FFFFFF', name: 'Pinky Purple' },
    { bg: '#DB4BDA', fg: '#FFFFFF', name: 'Pink Purple' },
    { bg: '#9E3623', fg: '#FFFFFF', name: 'Brownish Red' },
    { bg: '#B5485D', fg: '#FFFFFF', name: 'Dark Rose' },
    { bg: '#735C12', fg: '#FFFFFF', name: 'Mud' },
    { bg: '#9C6D57', fg: '#FFFFFF', name: 'Brownish' },
    { bg: '#028F1E', fg: '#FFFFFF', name: 'Emerald Green' },
    { bg: '#B1916E', fg: '#FFFFFF', name: 'Pale Brown' },
    { bg: '#49759C', fg: '#FFFFFF', name: 'Dull Blue' },
    { bg: '#A0450E', fg: '#FFFFFF', name: 'Burnt Umber' },
    { bg: '#39AD48', fg: '#FFFFFF', name: 'Medium Green' },
    { bg: '#B66A50', fg: '#FFFFFF', name: 'Clay' },
    { bg: '#8CFFDB', fg: '#000000', name: 'Light Aqua' },
    { bg: '#A4BE5C', fg: '#FFFFFF', name: 'Light Olive Green' },
    { bg: '#CB7723', fg: '#FFFFFF', name: 'Brownish Orange' },
    { bg: '#05696B', fg: '#FFFFFF', name: 'Dark Aqua' },
    { bg: '#CE5DAE', fg: '#FFFFFF', name: 'Purplish Pink' },
    { bg: '#C85A53', fg: '#FFFFFF', name: 'Dark Salmon' },
    { bg: '#96AE8D', fg: '#FFFFFF', name: 'Greenish Grey' },
    { bg: '#1FA774', fg: '#FFFFFF', name: 'Jade' },
    { bg: '#7A9703', fg: '#FFFFFF', name: 'Ugly Green' },
    { bg: '#AC9362', fg: '#FFFFFF', name: 'Dark Beige' },
    { bg: '#01A049', fg: '#FFFFFF', name: 'Emerald' },
    { bg: '#D9544D', fg: '#FFFFFF', name: 'Pale Red' },
    { bg: '#FA5FF7', fg: '#FFFFFF', name: 'Light Magenta' },
    { bg: '#82CAFC', fg: '#FFFFFF', name: 'Sky' },
    { bg: '#ACFFFC', fg: '#000000', name: 'Light Cyan' },
    { bg: '#FCB001', fg: '#FFFFFF', name: 'Yellow Orange' },
    { bg: '#910951', fg: '#FFFFFF', name: 'Reddish Purple' },
    { bg: '#FE2C54', fg: '#FFFFFF', name: 'Reddish Pink' },
    { bg: '#C875C4', fg: '#FFFFFF', name: 'Orchid' },
    { bg: '#CDC50A', fg: '#FFFFFF', name: 'Dirty Yellow' },
    { bg: '#FD411E', fg: '#FFFFFF', name: 'Orange Red' },
    { bg: '#9A0200', fg: '#FFFFFF', name: 'Deep Red' },
    { bg: '#BE6400', fg: '#FFFFFF', name: 'Orange Brown' },
    { bg: '#030AA7', fg: '#FFFFFF', name: 'Cobalt Blue' },
    { bg: '#FE019A', fg: '#FFFFFF', name: 'Neon Pink' },
    { bg: '#F7879A', fg: '#FFFFFF', name: 'Rose Pink' },
    { bg: '#887191', fg: '#FFFFFF', name: 'Greyish Purple' },
    { bg: '#B00149', fg: '#FFFFFF', name: 'Raspberry' },
    { bg: '#12E193', fg: '#FFFFFF', name: 'Aqua Green' },
    { bg: '#FE7B7C', fg: '#FFFFFF', name: 'Salmon Pink' },
    { bg: '#FF9408', fg: '#FFFFFF', name: 'Tangerine' },
    { bg: '#6A6E09', fg: '#FFFFFF', name: 'Brownish Green' },
    { bg: '#8B2E16', fg: '#FFFFFF', name: 'Red Brown' },
    { bg: '#696112', fg: '#FFFFFF', name: 'Greenish Brown' },
    { bg: '#E17701', fg: '#FFFFFF', name: 'Pumpkin' },
    { bg: '#0A481E', fg: '#FFFFFF', name: 'Pine Green' },
    { bg: '#343837', fg: '#FFFFFF', name: 'Charcoal' },
    { bg: '#FFB7CE', fg: '#000000', name: 'Baby Pink' },
    { bg: '#6A79F7', fg: '#FFFFFF', name: 'Cornflower' },
    { bg: '#5D06E9', fg: '#FFFFFF', name: 'Blue Violet' },
    { bg: '#3D1C02', fg: '#FFFFFF', name: 'Chocolate' },
    { bg: '#82A67D', fg: '#FFFFFF', name: 'Greyish Green' },
    { bg: '#BE0119', fg: '#FFFFFF', name: 'Scarlet' },
    { bg: '#C9FF27', fg: '#000000', name: 'Green Yellow' },
    { bg: '#373E02', fg: '#FFFFFF', name: 'Dark Olive' },
    { bg: '#A9561E', fg: '#FFFFFF', name: 'Sienna' },
    { bg: '#CAA0FF', fg: '#FFFFFF', name: 'Pastel Purple' },
    { bg: '#CA6641', fg: '#FFFFFF', name: 'Terracotta' },
    { bg: '#02D8E9', fg: '#FFFFFF', name: 'Aqua Blue' },
    { bg: '#88B378', fg: '#FFFFFF', name: 'Sage Green' },
    { bg: '#980002', fg: '#FFFFFF', name: 'Blood Red' },
    { bg: '#CB0162', fg: '#FFFFFF', name: 'Deep Pink' },
    { bg: '#5CAC2D', fg: '#FFFFFF', name: 'Grass' },
    { bg: '#769958', fg: '#FFFFFF', name: 'Moss' },
    { bg: '#A2BFFE', fg: '#FFFFFF', name: 'Pastel Blue' },
    { bg: '#10A674', fg: '#FFFFFF', name: 'Bluish Green' },
    { bg: '#06B48B', fg: '#FFFFFF', name: 'Green Blue' },
    { bg: '#AF884A', fg: '#FFFFFF', name: 'Dark Tan' },
    { bg: '#0B8B87', fg: '#FFFFFF', name: 'Greenish Blue' },
    { bg: '#FFA756', fg: '#FFFFFF', name: 'Pale Orange' },
    { bg: '#A2A415', fg: '#FFFFFF', name: 'Vomit' },
    { bg: '#154406', fg: '#FFFFFF', name: 'Forrest Green' },
    { bg: '#856798', fg: '#FFFFFF', name: 'Dark Lavender' },
    { bg: '#34013F', fg: '#FFFFFF', name: 'Dark Violet' },
    { bg: '#632DE9', fg: '#FFFFFF', name: 'Purple Blue' },
    { bg: '#0A888A', fg: '#FFFFFF', name: 'Dark Cyan' },
    { bg: '#6F7632', fg: '#FFFFFF', name: 'Olive Drab' },
    { bg: '#D46A7E', fg: '#FFFFFF', name: 'Pinkish' },
    { bg: '#1E488F', fg: '#FFFFFF', name: 'Cobalt' },
    { bg: '#BC13FE', fg: '#FFFFFF', name: 'Neon Purple' },
    { bg: '#7EF4CC', fg: '#000000', name: 'Light Turquoise' },
    { bg: '#76CD26', fg: '#FFFFFF', name: 'Apple Green' },
    { bg: '#74A662', fg: '#FFFFFF', name: 'Dull Green' },
    { bg: '#80013F', fg: '#FFFFFF', name: 'Wine' },
    { bg: '#B1D1FC', fg: '#000000', name: 'Powder Blue' },
    { bg: '#0652FF', fg: '#FFFFFF', name: 'Electric Blue' },
    { bg: '#045C5A', fg: '#FFFFFF', name: 'Dark Turquoise' },
    { bg: '#5729CE', fg: '#FFFFFF', name: 'Blue Purple' },
    { bg: '#069AF3', fg: '#FFFFFF', name: 'Azure' },
    { bg: '#FF000D', fg: '#FFFFFF', name: 'Bright Red' },
    { bg: '#F10C45', fg: '#FFFFFF', name: 'Pinkish Red' },
    { bg: '#5170D7', fg: '#FFFFFF', name: 'Cornflower Blue' },
    { bg: '#ACBF69', fg: '#FFFFFF', name: 'Light Olive' },
    { bg: '#6C3461', fg: '#FFFFFF', name: 'Grape' },
    { bg: '#5E819D', fg: '#FFFFFF', name: 'Greyish Blue' },
    { bg: '#601EF9', fg: '#FFFFFF', name: 'Purplish Blue' },
    { bg: '#B0DD16', fg: '#FFFFFF', name: 'Yellowish Green' },
    { bg: '#CDFD02', fg: '#000000', name: 'Greenish Yellow' },
    { bg: '#2C6FBB', fg: '#FFFFFF', name: 'Medium Blue' },
    { bg: '#C0737A', fg: '#FFFFFF', name: 'Dusty Rose' },
    { bg: '#D6B4FC', fg: '#FFFFFF', name: 'Light Violet' },
    { bg: '#703BE7', fg: '#FFFFFF', name: 'Bluish Purple' },
    { bg: '#FD3C06', fg: '#FFFFFF', name: 'Red Orange' },
    { bg: '#960056', fg: '#FFFFFF', name: 'Dark Magenta' },
    { bg: '#40A368', fg: '#FFFFFF', name: 'Greenish' },
    { bg: '#03719C', fg: '#FFFFFF', name: 'Ocean Blue' },
    { bg: '#FC5A50', fg: '#FFFFFF', name: 'Coral' },
    { bg: '#7F2B0A', fg: '#FFFFFF', name: 'Reddish Brown' },
    { bg: '#B04E0F', fg: '#FFFFFF', name: 'Burnt Sienna' },
    { bg: '#A03623', fg: '#FFFFFF', name: 'Brick' },
    { bg: '#87AE73', fg: '#FFFFFF', name: 'Sage' },
    { bg: '#789B73', fg: '#FFFFFF', name: 'Grey Green' },
    { bg: '#98EFF9', fg: '#000000', name: 'robins Egg Blue' },
    { bg: '#658B38', fg: '#FFFFFF', name: 'Moss Green' },
    { bg: '#5A7D9A', fg: '#FFFFFF', name: 'Steel Blue' },
    { bg: '#380835', fg: '#FFFFFF', name: 'Eggplant' },
    { bg: '#FFFE7A', fg: '#000000', name: 'Light Yellow' },
    { bg: '#5CA904', fg: '#FFFFFF', name: 'Leaf Green' },
    { bg: '#D8DCD6', fg: '#000000', name: 'Light Grey' },
    { bg: '#A5A502', fg: '#FFFFFF', name: 'Puke' },
    { bg: '#D648D7', fg: '#FFFFFF', name: 'Pinkish Purple' },
    { bg: '#047495', fg: '#FFFFFF', name: 'Sea Blue' },
    { bg: '#B790D4', fg: '#FFFFFF', name: 'Pale Purple' },
    { bg: '#5B7C99', fg: '#FFFFFF', name: 'Slate Blue' },
    { bg: '#607C8E', fg: '#FFFFFF', name: 'Blue Grey' },
    { bg: '#0B4008', fg: '#FFFFFF', name: 'Hunter Green' },
    { bg: '#ED0DD9', fg: '#FFFFFF', name: 'Fuchsia' },
    { bg: '#8C000F', fg: '#FFFFFF', name: 'Crimson' },
    { bg: '#FFFF84', fg: '#000000', name: 'Pale Yellow' },
    { bg: '#BF9005', fg: '#FFFFFF', name: 'Ochre' },
    { bg: '#D2BD0A', fg: '#FFFFFF', name: 'Mustard Yellow' },
    { bg: '#FF474C', fg: '#FFFFFF', name: 'Light Red' },
    { bg: '#0485D1', fg: '#FFFFFF', name: 'Cerulean' },
    { bg: '#FFCFDC', fg: '#000000', name: 'Pale Pink' },
    { bg: '#040273', fg: '#FFFFFF', name: 'Deep Blue' },
    { bg: '#A83C09', fg: '#FFFFFF', name: 'Rust' },
    { bg: '#90E4C1', fg: '#FFFFFF', name: 'Light Teal' },
    { bg: '#516572', fg: '#FFFFFF', name: 'Slate' },
    { bg: '#FAC205', fg: '#FFFFFF', name: 'Goldenrod' },
    { bg: '#D5B60A', fg: '#FFFFFF', name: 'Dark Yellow' },
    { bg: '#363737', fg: '#FFFFFF', name: 'Dark Grey' },
    { bg: '#4B5D16', fg: '#FFFFFF', name: 'Army Green' },
    { bg: '#6B8BA4', fg: '#FFFFFF', name: 'Grey Blue' },
    { bg: '#80F9AD', fg: '#000000', name: 'Seafoam' },
    { bg: '#A57E52', fg: '#FFFFFF', name: 'Puce' },
    { bg: '#A9F971', fg: '#000000', name: 'Spring Green' },
    { bg: '#C65102', fg: '#FFFFFF', name: 'Dark Orange' },
    { bg: '#E2CA76', fg: '#FFFFFF', name: 'Sand' },
    { bg: '#B0FF9D', fg: '#000000', name: 'Pastel Green' },
    { bg: '#9FFEB0', fg: '#000000', name: 'Mint' },
    { bg: '#FDAA48', fg: '#FFFFFF', name: 'Light Orange' },
    { bg: '#FE01B1', fg: '#FFFFFF', name: 'Bright Pink' },
    { bg: '#C1F80A', fg: '#000000', name: 'Chartreuse' },
    { bg: '#36013F', fg: '#FFFFFF', name: 'Deep Purple' },
    { bg: '#341C02', fg: '#FFFFFF', name: 'Dark Brown' },
    { bg: '#B9A281', fg: '#FFFFFF', name: 'Taupe' },
    { bg: '#8EAB12', fg: '#FFFFFF', name: 'Pea Green' },
    { bg: '#9AAE07', fg: '#FFFFFF', name: 'Puke Green' },
    { bg: '#02AB2E', fg: '#FFFFFF', name: 'Kelly Green' },
    { bg: '#7AF9AB', fg: '#000000', name: 'Seafoam Green' },
    { bg: '#137E6D', fg: '#FFFFFF', name: 'Blue Green' },
    { bg: '#AAA662', fg: '#FFFFFF', name: 'Khaki' },
    { bg: '#610023', fg: '#FFFFFF', name: 'Burgundy' },
    { bg: '#014D4E', fg: '#FFFFFF', name: 'Dark Teal' },
    { bg: '#8F1402', fg: '#FFFFFF', name: 'Brick Red' },
    { bg: '#4B006E', fg: '#FFFFFF', name: 'Royal Purple' },
    { bg: '#580F41', fg: '#FFFFFF', name: 'Plum' },
    { bg: '#8FFF9F', fg: '#000000', name: 'Mint Green' },
    { bg: '#DBB40C', fg: '#FFFFFF', name: 'Gold' },
    { bg: '#A2CFFE', fg: '#FFFFFF', name: 'Baby Blue' },
    { bg: '#C0FB2D', fg: '#000000', name: 'Yellow Green' },
    { bg: '#BE03FD', fg: '#FFFFFF', name: 'Bright Purple' },
    { bg: '#840000', fg: '#FFFFFF', name: 'Dark Red' },
    { bg: '#D0FEFE', fg: '#000000', name: 'Pale Blue' },
    { bg: '#3F9B0B', fg: '#FFFFFF', name: 'Grass Green' },
    { bg: '#01153E', fg: '#FFFFFF', name: 'Navy' },
    { bg: '#04D8B2', fg: '#FFFFFF', name: 'Aquamarine' },
    { bg: '#C04E01', fg: '#FFFFFF', name: 'Burnt Orange' },
    { bg: '#0CFF0C', fg: '#FFFFFF', name: 'Neon Green' },
    { bg: '#0165FC', fg: '#FFFFFF', name: 'Bright Blue' },
    { bg: '#CF6275', fg: '#FFFFFF', name: 'Rose' },
    { bg: '#FFD1DF', fg: '#000000', name: 'Light Pink' },
    { bg: '#CEB301', fg: '#FFFFFF', name: 'Mustard' },
    { bg: '#380282', fg: '#FFFFFF', name: 'Indigo' },
    { bg: '#AAFF32', fg: '#000000', name: 'Lime' },
    { bg: '#53FCA1', fg: '#FFFFFF', name: 'Sea Green' },
    { bg: '#8E82FE', fg: '#FFFFFF', name: 'Periwinkle' },
    { bg: '#CB416B', fg: '#FFFFFF', name: 'Dark Pink' },
    { bg: '#677A04', fg: '#FFFFFF', name: 'Olive Green' },
    { bg: '#FFB07C', fg: '#FFFFFF', name: 'Peach' },
    { bg: '#C7FDB5', fg: '#000000', name: 'Pale Green' },
    { bg: '#AD8150', fg: '#FFFFFF', name: 'Light Brown' },
    // { bg: '#FF028D', fg: '#FFFFFF', name: 'Hot Pink' },
    { bg: '#CEA2FD', fg: '#FFFFFF', name: 'Lilac' },
    { bg: '#001146', fg: '#FFFFFF', name: 'Navy Blue' },
    { bg: '#0504AA', fg: '#FFFFFF', name: 'Royal Blue' },
    { bg: '#E6DAA6', fg: '#000000', name: 'Beige' },
    { bg: '#FF796C', fg: '#FFFFFF', name: 'Salmon' },
    { bg: '#6E750E', fg: '#FFFFFF', name: 'Olive' },
    { bg: '#650021', fg: '#FFFFFF', name: 'Maroon' },
    { bg: '#01FF07', fg: '#FFFFFF', name: 'Bright Green' },
    { bg: '#35063E', fg: '#FFFFFF', name: 'Dark Purple' },
    { bg: '#AE7181', fg: '#FFFFFF', name: 'Mauve' },
    { bg: '#06470C', fg: '#FFFFFF', name: 'Forest Green' },
    { bg: '#13EAC9', fg: '#FFFFFF', name: 'Aqua' },
    // { bg: '#00FFFF', fg: '#FFFFFF', name: 'Cyan' },
    { bg: '#D1B26F', fg: '#FFFFFF', name: 'Tan' },
    { bg: '#00035B', fg: '#FFFFFF', name: 'Dark Blue' },
    { bg: '#C79FEF', fg: '#FFFFFF', name: 'Lavender' },
    { bg: '#06C2AC', fg: '#FFFFFF', name: 'Turquoise' },
    { bg: '#033500', fg: '#FFFFFF', name: 'Dark Green' },
    { bg: '#9A0EEA', fg: '#FFFFFF', name: 'Violet' },
    { bg: '#BF77F6', fg: '#FFFFFF', name: 'Light Purple' },
    { bg: '#89FE05', fg: '#FFFFFF', name: 'Lime Green' },
    { bg: '#929591', fg: '#FFFFFF', name: 'Grey' },
    { bg: '#75BBFD', fg: '#FFFFFF', name: 'Sky Blue' },
    { bg: '#FFFF14', fg: '#000000', name: 'Yellow' },
    { bg: '#C20078', fg: '#FFFFFF', name: 'Magenta' },
    { bg: '#96F97B', fg: '#000000', name: 'Light Green' },
    { bg: '#F97306', fg: '#FFFFFF', name: 'Orange' },
    { bg: '#029386', fg: '#FFFFFF', name: 'Teal' },
    { bg: '#95D0FC', fg: '#FFFFFF', name: 'Light Blue' },
    { bg: '#E50000', fg: '#FFFFFF', name: 'Red' },
    { bg: '#653700', fg: '#FFFFFF', name: 'Brown' },
    { bg: '#FF81C0', fg: '#FFFFFF', name: 'Pink' },
    { bg: '#0343DF', fg: '#FFFFFF', name: 'Blue' },
    { bg: '#15B01A', fg: '#FFFFFF', name: 'Green' },
    { bg: '#7E1E9C', fg: '#FFFFFF', name: 'Purple' },
  ];

export default COLOR_THEMES;