import SwiftUI

struct StudyColorTheme {
    let bg: Color
    let fg: Color
    let name: String

    init(bg: String, fg: String, name: String) {
        self.bg = Color(hex: bg)
        self.fg = Color(hex: fg)
        self.name = name
    }

    /// Calculate contrast text color based on background
    static func getContrastText(for backgroundColor: Color) -> Color {
        // Convert to RGB
        guard let components = backgroundColor.cgColor?.components,
              components.count >= 3 else {
            return .white
        }

        let r = components[0]
        let g = components[1]
        let b = components[2]

        // Calculate relative luminance
        let luminance = 0.299 * r + 0.587 * g + 0.114 * b

        // Return white for dark backgrounds, black for light backgrounds
        return luminance > 0.5 ? Color.black : Color.white
    }
}

// MARK: - All Color Themes (944 themes from xkcd color survey)

struct StudyColorThemes {
    static let all: [StudyColorTheme] = [
        StudyColorTheme(bg: "#ACC2D9", fg: "#FFFFFF", name: "Cloudy Blue"),
        StudyColorTheme(bg: "#56AE57", fg: "#FFFFFF", name: "Dark Pastel Green"),
        StudyColorTheme(bg: "#B2996E", fg: "#FFFFFF", name: "Dust"),
        StudyColorTheme(bg: "#A8FF04", fg: "#000000", name: "Electric Lime"),
        StudyColorTheme(bg: "#69D84F", fg: "#FFFFFF", name: "Fresh Green"),
        StudyColorTheme(bg: "#894585", fg: "#FFFFFF", name: "Light Eggplant"),
        StudyColorTheme(bg: "#70B23F", fg: "#FFFFFF", name: "Nasty Green"),
        StudyColorTheme(bg: "#D4FFFF", fg: "#000000", name: "Really Light Blue"),
        StudyColorTheme(bg: "#65AB7C", fg: "#FFFFFF", name: "Tea"),
        StudyColorTheme(bg: "#952E8F", fg: "#FFFFFF", name: "Warm Purple"),
        StudyColorTheme(bg: "#FCFC81", fg: "#000000", name: "Yellowish Tan"),
        StudyColorTheme(bg: "#A5A391", fg: "#FFFFFF", name: "Cement"),
        StudyColorTheme(bg: "#388004", fg: "#FFFFFF", name: "Dark Grass Green"),
        StudyColorTheme(bg: "#4C9085", fg: "#FFFFFF", name: "Dusty Teal"),
        StudyColorTheme(bg: "#5E9B8A", fg: "#FFFFFF", name: "Grey Teal"),
        StudyColorTheme(bg: "#EFB435", fg: "#FFFFFF", name: "Macaroni And Cheese"),
        StudyColorTheme(bg: "#D99B82", fg: "#FFFFFF", name: "Pinkish Tan"),
        StudyColorTheme(bg: "#0A5F38", fg: "#FFFFFF", name: "Spruce"),
        StudyColorTheme(bg: "#0C06F7", fg: "#FFFFFF", name: "Strong Blue"),
        StudyColorTheme(bg: "#61DE2A", fg: "#FFFFFF", name: "Toxic Green"),
        StudyColorTheme(bg: "#3778BF", fg: "#FFFFFF", name: "Windows Blue"),
        StudyColorTheme(bg: "#2242C7", fg: "#FFFFFF", name: "Blue Blue"),
        StudyColorTheme(bg: "#533CC6", fg: "#FFFFFF", name: "Blue With A Hint Of Purple"),
        StudyColorTheme(bg: "#9BB53C", fg: "#FFFFFF", name: "Booger"),
        StudyColorTheme(bg: "#05FFA6", fg: "#FFFFFF", name: "Bright Sea Green"),
        StudyColorTheme(bg: "#1F6357", fg: "#FFFFFF", name: "Dark Green Blue"),
        StudyColorTheme(bg: "#017374", fg: "#FFFFFF", name: "Deep Turquoise"),
        StudyColorTheme(bg: "#0CB577", fg: "#FFFFFF", name: "Green Teal"),
        StudyColorTheme(bg: "#FF0789", fg: "#FFFFFF", name: "Strong Pink"),
        StudyColorTheme(bg: "#AFA88B", fg: "#FFFFFF", name: "Bland"),
        StudyColorTheme(bg: "#08787F", fg: "#FFFFFF", name: "Deep Aqua"),
        StudyColorTheme(bg: "#DD85D7", fg: "#FFFFFF", name: "Lavender Pink"),
        StudyColorTheme(bg: "#A6C875", fg: "#FFFFFF", name: "Light Moss Green"),
        StudyColorTheme(bg: "#A7FFB5", fg: "#000000", name: "Light Seafoam Green"),
        StudyColorTheme(bg: "#C2B709", fg: "#FFFFFF", name: "Olive Yellow"),
        StudyColorTheme(bg: "#E78EA5", fg: "#FFFFFF", name: "Pig Pink"),
        StudyColorTheme(bg: "#966EBD", fg: "#FFFFFF", name: "Deep Lilac"),
        StudyColorTheme(bg: "#CCAD60", fg: "#FFFFFF", name: "Desert"),
        StudyColorTheme(bg: "#AC86A8", fg: "#FFFFFF", name: "Dusty Lavender"),
        StudyColorTheme(bg: "#947E94", fg: "#FFFFFF", name: "Purpley Grey"),
        StudyColorTheme(bg: "#983FB2", fg: "#FFFFFF", name: "Purply"),
        StudyColorTheme(bg: "#FF63E9", fg: "#FFFFFF", name: "Candy Pink"),
        StudyColorTheme(bg: "#B2FBA5", fg: "#000000", name: "Light Pastel Green"),
        StudyColorTheme(bg: "#63B365", fg: "#FFFFFF", name: "Boring Green"),
        StudyColorTheme(bg: "#B7E1A1", fg: "#000000", name: "Light Grey Green"),
        StudyColorTheme(bg: "#FF6F52", fg: "#FFFFFF", name: "Orange Pink"),
        StudyColorTheme(bg: "#BDF8A3", fg: "#000000", name: "Tea Green"),
        StudyColorTheme(bg: "#D3B683", fg: "#FFFFFF", name: "Very Light Brown"),
        StudyColorTheme(bg: "#430541", fg: "#FFFFFF", name: "Eggplant Purple"),
        StudyColorTheme(bg: "#FFB2D0", fg: "#000000", name: "Powder Pink"),
        StudyColorTheme(bg: "#997570", fg: "#FFFFFF", name: "Reddish Grey"),
        StudyColorTheme(bg: "#AD900D", fg: "#FFFFFF", name: "Baby Shit Brown"),
        StudyColorTheme(bg: "#C48EFD", fg: "#FFFFFF", name: "Liliac"),
        StudyColorTheme(bg: "#507B9C", fg: "#FFFFFF", name: "Stormy Blue"),
        StudyColorTheme(bg: "#7D7103", fg: "#FFFFFF", name: "Ugly Brown"),
        StudyColorTheme(bg: "#FFFD78", fg: "#000000", name: "Custard"),
        StudyColorTheme(bg: "#DA467D", fg: "#FFFFFF", name: "Darkish Pink"),
        StudyColorTheme(bg: "#410200", fg: "#FFFFFF", name: "Deep Brown"),
        StudyColorTheme(bg: "#C9D179", fg: "#FFFFFF", name: "Greenish Beige"),
        StudyColorTheme(bg: "#FFFA86", fg: "#000000", name: "Manilla"),
        StudyColorTheme(bg: "#5684AE", fg: "#FFFFFF", name: "Off Blue"),
        StudyColorTheme(bg: "#6B7C85", fg: "#FFFFFF", name: "Battleship Grey"),
        StudyColorTheme(bg: "#6F6C0A", fg: "#FFFFFF", name: "Browny Green"),
        StudyColorTheme(bg: "#7E4071", fg: "#FFFFFF", name: "Bruise"),
        StudyColorTheme(bg: "#009337", fg: "#FFFFFF", name: "Kelley Green"),
        StudyColorTheme(bg: "#D0E429", fg: "#000000", name: "Sickly Yellow"),
        StudyColorTheme(bg: "#FFF917", fg: "#000000", name: "Sunny Yellow"),
        StudyColorTheme(bg: "#1D5DEC", fg: "#FFFFFF", name: "Azul"),
        StudyColorTheme(bg: "#054907", fg: "#FFFFFF", name: "Darkgreen"),
        StudyColorTheme(bg: "#B5CE08", fg: "#FFFFFF", name: "Green/Yellow"),
        StudyColorTheme(bg: "#8FB67B", fg: "#FFFFFF", name: "Lichen"),
        StudyColorTheme(bg: "#C8FFB0", fg: "#000000", name: "Light Light Green"),
        StudyColorTheme(bg: "#FDDE6C", fg: "#000000", name: "Pale Gold"),
        StudyColorTheme(bg: "#FFDF22", fg: "#000000", name: "Sun Yellow"),
        StudyColorTheme(bg: "#A9BE70", fg: "#FFFFFF", name: "Tan Green"),
        StudyColorTheme(bg: "#6832E3", fg: "#FFFFFF", name: "Burple"),
        StudyColorTheme(bg: "#FDB147", fg: "#FFFFFF", name: "Butterscotch"),
        StudyColorTheme(bg: "#C7AC7D", fg: "#FFFFFF", name: "Toupe"),
        StudyColorTheme(bg: "#FFF39A", fg: "#000000", name: "Dark Cream"),
        StudyColorTheme(bg: "#850E04", fg: "#FFFFFF", name: "Indian Red"),
        StudyColorTheme(bg: "#EFC0FE", fg: "#000000", name: "Light Lavendar"),
        StudyColorTheme(bg: "#B6C406", fg: "#FFFFFF", name: "Baby Puke Green"),
        StudyColorTheme(bg: "#3C4142", fg: "#FFFFFF", name: "Charcoal Grey"),
        StudyColorTheme(bg: "#F2AB15", fg: "#FFFFFF", name: "Squash"),
        StudyColorTheme(bg: "#AC4F06", fg: "#FFFFFF", name: "Cinnamon"),
        StudyColorTheme(bg: "#C4FE82", fg: "#000000", name: "Light Pea Green"),
        StudyColorTheme(bg: "#2CFA1F", fg: "#FFFFFF", name: "Radioactive Green"),
        StudyColorTheme(bg: "#9A6200", fg: "#FFFFFF", name: "Raw Sienna"),
        StudyColorTheme(bg: "#CA9BF7", fg: "#FFFFFF", name: "Baby Purple"),
        StudyColorTheme(bg: "#875F42", fg: "#FFFFFF", name: "Cocoa"),
        StudyColorTheme(bg: "#3A2EFE", fg: "#FFFFFF", name: "Light Royal Blue"),
        StudyColorTheme(bg: "#FD8D49", fg: "#FFFFFF", name: "Orangeish"),
        StudyColorTheme(bg: "#8B3103", fg: "#FFFFFF", name: "Rust Brown"),
        StudyColorTheme(bg: "#CBA560", fg: "#FFFFFF", name: "Sand Brown"),
        StudyColorTheme(bg: "#698339", fg: "#FFFFFF", name: "Swamp"),
        StudyColorTheme(bg: "#0CDC73", fg: "#FFFFFF", name: "Tealish Green"),
        StudyColorTheme(bg: "#B75203", fg: "#FFFFFF", name: "Burnt Siena"),
        StudyColorTheme(bg: "#7F8F4E", fg: "#FFFFFF", name: "Camo"),
        StudyColorTheme(bg: "#26538D", fg: "#FFFFFF", name: "Dusk Blue"),
        StudyColorTheme(bg: "#63A950", fg: "#FFFFFF", name: "Fern"),
        StudyColorTheme(bg: "#C87F89", fg: "#FFFFFF", name: "Old Rose"),
        StudyColorTheme(bg: "#B1FC99", fg: "#000000", name: "Pale Light Green"),
        StudyColorTheme(bg: "#FF9A8A", fg: "#FFFFFF", name: "Peachy Pink"),
        StudyColorTheme(bg: "#F6688E", fg: "#FFFFFF", name: "Rosy Pink"),
        StudyColorTheme(bg: "#76FDA8", fg: "#000000", name: "Light Bluish Green"),
        StudyColorTheme(bg: "#53FE5C", fg: "#FFFFFF", name: "Light Bright Green"),
        StudyColorTheme(bg: "#4EFD54", fg: "#FFFFFF", name: "Light Neon Green"),
        StudyColorTheme(bg: "#A0FEBF", fg: "#000000", name: "Light Seafoam"),
        StudyColorTheme(bg: "#7BF2DA", fg: "#000000", name: "Tiffany Blue"),
        StudyColorTheme(bg: "#BCF5A6", fg: "#000000", name: "Washed Out Green"),
        StudyColorTheme(bg: "#CA6B02", fg: "#FFFFFF", name: "Browny Orange"),
        StudyColorTheme(bg: "#107AB0", fg: "#FFFFFF", name: "Nice Blue"),
        StudyColorTheme(bg: "#2138AB", fg: "#FFFFFF", name: "Sapphire"),
        StudyColorTheme(bg: "#719F91", fg: "#FFFFFF", name: "Greyish Teal"),
        StudyColorTheme(bg: "#FDB915", fg: "#FFFFFF", name: "Orangey Yellow"),
        StudyColorTheme(bg: "#FEFCAF", fg: "#000000", name: "Parchment"),
        StudyColorTheme(bg: "#FCF679", fg: "#000000", name: "Straw"),
        StudyColorTheme(bg: "#CB6843", fg: "#FFFFFF", name: "Terracota"),
        StudyColorTheme(bg: "#31668A", fg: "#FFFFFF", name: "Ugly Blue"),
        StudyColorTheme(bg: "#247AFD", fg: "#FFFFFF", name: "Clear Blue"),
        StudyColorTheme(bg: "#90FDA9", fg: "#000000", name: "Foam Green"),
        StudyColorTheme(bg: "#86A17D", fg: "#FFFFFF", name: "Grey/Green"),
        StudyColorTheme(bg: "#FDDC5C", fg: "#000000", name: "Light Gold"),
        StudyColorTheme(bg: "#78D1B6", fg: "#FFFFFF", name: "Seafoam Blue"),
        StudyColorTheme(bg: "#13BBAF", fg: "#FFFFFF", name: "Topaz"),
        StudyColorTheme(bg: "#FB5FFC", fg: "#FFFFFF", name: "Violet Pink"),
        StudyColorTheme(bg: "#20F986", fg: "#FFFFFF", name: "Wintergreen"),
        StudyColorTheme(bg: "#FFE36E", fg: "#000000", name: "Yellow Tan"),
        StudyColorTheme(bg: "#9D0759", fg: "#FFFFFF", name: "Dark Fuchsia"),
        StudyColorTheme(bg: "#3A18B1", fg: "#FFFFFF", name: "Indigo Blue"),
        StudyColorTheme(bg: "#C2FF89", fg: "#000000", name: "Light Yellowish Green"),
        StudyColorTheme(bg: "#D767AD", fg: "#FFFFFF", name: "Pale Magenta"),
        StudyColorTheme(bg: "#720058", fg: "#FFFFFF", name: "Rich Purple"),
        StudyColorTheme(bg: "#FFDA03", fg: "#000000", name: "Sunflower Yellow"),
        StudyColorTheme(bg: "#01C08D", fg: "#FFFFFF", name: "Green/Blue"),
        StudyColorTheme(bg: "#AC7434", fg: "#FFFFFF", name: "Leather"),
        StudyColorTheme(bg: "#014600", fg: "#FFFFFF", name: "Racing Green"),
        StudyColorTheme(bg: "#9900FA", fg: "#FFFFFF", name: "Vivid Purple"),
        StudyColorTheme(bg: "#02066F", fg: "#FFFFFF", name: "Dark Royal Blue"),
        StudyColorTheme(bg: "#8E7618", fg: "#FFFFFF", name: "Hazel"),
        StudyColorTheme(bg: "#D1768F", fg: "#FFFFFF", name: "Muted Pink"),
        StudyColorTheme(bg: "#96B403", fg: "#FFFFFF", name: "Booger Green"),
        StudyColorTheme(bg: "#FDFF63", fg: "#000000", name: "Canary"),
        StudyColorTheme(bg: "#95A3A6", fg: "#FFFFFF", name: "Cool Grey"),
        StudyColorTheme(bg: "#7F684E", fg: "#FFFFFF", name: "Dark Taupe"),
        StudyColorTheme(bg: "#751973", fg: "#FFFFFF", name: "Darkish Purple"),
        StudyColorTheme(bg: "#089404", fg: "#FFFFFF", name: "True Green"),
        StudyColorTheme(bg: "#FF6163", fg: "#FFFFFF", name: "Coral Pink"),
        StudyColorTheme(bg: "#598556", fg: "#FFFFFF", name: "Dark Sage"),
        StudyColorTheme(bg: "#214761", fg: "#FFFFFF", name: "Dark Slate Blue"),
        StudyColorTheme(bg: "#3C73A8", fg: "#FFFFFF", name: "Flat Blue"),
        StudyColorTheme(bg: "#BA9E88", fg: "#FFFFFF", name: "Mushroom"),
        StudyColorTheme(bg: "#021BF9", fg: "#FFFFFF", name: "Rich Blue"),
        StudyColorTheme(bg: "#734A65", fg: "#FFFFFF", name: "Dirty Purple"),
        StudyColorTheme(bg: "#23C48B", fg: "#FFFFFF", name: "Greenblue"),
        StudyColorTheme(bg: "#8FAE22", fg: "#FFFFFF", name: "Icky Green"),
        StudyColorTheme(bg: "#E6F2A2", fg: "#000000", name: "Light Khaki"),
        StudyColorTheme(bg: "#4B57DB", fg: "#FFFFFF", name: "Warm Blue"),
        StudyColorTheme(bg: "#D90166", fg: "#FFFFFF", name: "Dark Hot Pink"),
        StudyColorTheme(bg: "#015482", fg: "#FFFFFF", name: "Deep Sea Blue"),
        StudyColorTheme(bg: "#9D0216", fg: "#FFFFFF", name: "Carmine"),
        StudyColorTheme(bg: "#728F02", fg: "#FFFFFF", name: "Dark Yellow Green"),
        StudyColorTheme(bg: "#FFE5AD", fg: "#000000", name: "Pale Peach"),
        StudyColorTheme(bg: "#4E0550", fg: "#FFFFFF", name: "Plum Purple"),
        StudyColorTheme(bg: "#F9BC08", fg: "#FFFFFF", name: "Golden Rod"),
        StudyColorTheme(bg: "#FF073A", fg: "#FFFFFF", name: "Neon Red"),
        StudyColorTheme(bg: "#C77986", fg: "#FFFFFF", name: "Old Pink"),
        StudyColorTheme(bg: "#D6FFFE", fg: "#000000", name: "Very Pale Blue"),
        StudyColorTheme(bg: "#FE4B03", fg: "#FFFFFF", name: "Blood Orange"),
        StudyColorTheme(bg: "#FD5956", fg: "#FFFFFF", name: "Grapefruit"),
        StudyColorTheme(bg: "#FCE166", fg: "#000000", name: "Sand Yellow"),
        StudyColorTheme(bg: "#B2713D", fg: "#FFFFFF", name: "Clay Brown"),
        StudyColorTheme(bg: "#1F3B4D", fg: "#FFFFFF", name: "Dark Blue Grey"),
        StudyColorTheme(bg: "#699D4C", fg: "#FFFFFF", name: "Flat Green"),
        StudyColorTheme(bg: "#56FCA2", fg: "#FFFFFF", name: "Light Green Blue"),
        StudyColorTheme(bg: "#FB5581", fg: "#FFFFFF", name: "Warm Pink"),
        StudyColorTheme(bg: "#3E82FC", fg: "#FFFFFF", name: "Dodger Blue"),
        StudyColorTheme(bg: "#A0BF16", fg: "#FFFFFF", name: "Gross Green"),
        StudyColorTheme(bg: "#D6FFFA", fg: "#000000", name: "Ice"),
        StudyColorTheme(bg: "#4F738E", fg: "#FFFFFF", name: "Metallic Blue"),
        StudyColorTheme(bg: "#FFB19A", fg: "#FFFFFF", name: "Pale Salmon"),
        StudyColorTheme(bg: "#5C8B15", fg: "#FFFFFF", name: "Sap Green"),
        StudyColorTheme(bg: "#54AC68", fg: "#FFFFFF", name: "Algae"),
        StudyColorTheme(bg: "#89A0B0", fg: "#FFFFFF", name: "Bluey Grey"),
        StudyColorTheme(bg: "#7EA07A", fg: "#FFFFFF", name: "Greeny Grey"),
        StudyColorTheme(bg: "#1BFC06", fg: "#FFFFFF", name: "Highlighter Green"),
        StudyColorTheme(bg: "#CAFFFB", fg: "#000000", name: "Light Light Blue"),
        StudyColorTheme(bg: "#B6FFBB", fg: "#000000", name: "Light Mint"),
        StudyColorTheme(bg: "#A75E09", fg: "#FFFFFF", name: "Raw Umber"),
        StudyColorTheme(bg: "#152EFF", fg: "#FFFFFF", name: "Vivid Blue"),
        StudyColorTheme(bg: "#8D5EB7", fg: "#FFFFFF", name: "Deep Lavender"),
        StudyColorTheme(bg: "#5F9E8F", fg: "#FFFFFF", name: "Dull Teal"),
        StudyColorTheme(bg: "#606602", fg: "#FFFFFF", name: "Mud Green"),
        StudyColorTheme(bg: "#FC86AA", fg: "#FFFFFF", name: "Pinky"),
        StudyColorTheme(bg: "#8C0034", fg: "#FFFFFF", name: "Red Wine"),
        StudyColorTheme(bg: "#758000", fg: "#FFFFFF", name: "Shit Green"),
        StudyColorTheme(bg: "#AB7E4C", fg: "#FFFFFF", name: "Tan Brown"),
        StudyColorTheme(bg: "#030764", fg: "#FFFFFF", name: "Darkblue"),
        StudyColorTheme(bg: "#FE86A4", fg: "#FFFFFF", name: "Rosa"),
        StudyColorTheme(bg: "#D5174E", fg: "#FFFFFF", name: "Lipstick"),
        StudyColorTheme(bg: "#FED0FC", fg: "#000000", name: "Pale Mauve"),
        StudyColorTheme(bg: "#680018", fg: "#FFFFFF", name: "Claret"),
        StudyColorTheme(bg: "#FEDF08", fg: "#000000", name: "Dandelion"),
        StudyColorTheme(bg: "#FE420F", fg: "#FFFFFF", name: "Orangered"),
        StudyColorTheme(bg: "#6F7C00", fg: "#FFFFFF", name: "Poop Green"),
        StudyColorTheme(bg: "#CA0147", fg: "#FFFFFF", name: "Ruby"),
        StudyColorTheme(bg: "#1B2431", fg: "#FFFFFF", name: "Dark"),
        StudyColorTheme(bg: "#DB5856", fg: "#FFFFFF", name: "Pastel Red"),
        StudyColorTheme(bg: "#DDD618", fg: "#FFFFFF", name: "Piss Yellow"),
        StudyColorTheme(bg: "#CF524E", fg: "#FFFFFF", name: "Dark Coral"),
        StudyColorTheme(bg: "#21C36F", fg: "#FFFFFF", name: "Algae Green"),
        StudyColorTheme(bg: "#A90308", fg: "#FFFFFF", name: "Darkish Red"),
        StudyColorTheme(bg: "#6E1005", fg: "#FFFFFF", name: "Reddy Brown"),
        StudyColorTheme(bg: "#FE828C", fg: "#FFFFFF", name: "Blush Pink"),
        StudyColorTheme(bg: "#4B6113", fg: "#FFFFFF", name: "Camouflage Green"),
        StudyColorTheme(bg: "#4DA409", fg: "#FFFFFF", name: "Lawn Green"),
        StudyColorTheme(bg: "#BEAE8A", fg: "#FFFFFF", name: "Putty"),
        StudyColorTheme(bg: "#0339F8", fg: "#FFFFFF", name: "Vibrant Blue"),
        StudyColorTheme(bg: "#A88F59", fg: "#FFFFFF", name: "Dark Sand"),
        StudyColorTheme(bg: "#5D21D0", fg: "#FFFFFF", name: "Purple/Blue"),
        StudyColorTheme(bg: "#FEB209", fg: "#FFFFFF", name: "Saffron"),
        StudyColorTheme(bg: "#4E518B", fg: "#FFFFFF", name: "Twilight"),
        StudyColorTheme(bg: "#964E02", fg: "#FFFFFF", name: "Warm Brown"),
        StudyColorTheme(bg: "#85A3B2", fg: "#FFFFFF", name: "Bluegrey"),
        StudyColorTheme(bg: "#FF69AF", fg: "#FFFFFF", name: "Bubble Gum Pink"),
        StudyColorTheme(bg: "#C3FBF4", fg: "#000000", name: "Duck Egg Blue"),
        StudyColorTheme(bg: "#2AFEB7", fg: "#FFFFFF", name: "Greenish Cyan"),
        StudyColorTheme(bg: "#005F6A", fg: "#FFFFFF", name: "Petrol"),
        StudyColorTheme(bg: "#0C1793", fg: "#FFFFFF", name: "Royal"),
        StudyColorTheme(bg: "#FFFF81", fg: "#000000", name: "Butter"),
        StudyColorTheme(bg: "#F0833A", fg: "#FFFFFF", name: "Dusty Orange"),
        StudyColorTheme(bg: "#F1F33F", fg: "#000000", name: "Off Yellow"),
        StudyColorTheme(bg: "#B1D27B", fg: "#FFFFFF", name: "Pale Olive Green"),
        StudyColorTheme(bg: "#FC824A", fg: "#FFFFFF", name: "Orangish"),
        StudyColorTheme(bg: "#71AA34", fg: "#FFFFFF", name: "Leaf"),
        StudyColorTheme(bg: "#B7C9E2", fg: "#FFFFFF", name: "Light Blue Grey"),
        StudyColorTheme(bg: "#4B0101", fg: "#FFFFFF", name: "Dried Blood"),
        StudyColorTheme(bg: "#A552E6", fg: "#FFFFFF", name: "Lightish Purple"),
        StudyColorTheme(bg: "#AF2F0D", fg: "#FFFFFF", name: "Rusty Red"),
        StudyColorTheme(bg: "#8B88F8", fg: "#FFFFFF", name: "Lavender Blue"),
        StudyColorTheme(bg: "#9AF764", fg: "#000000", name: "Light Grass Green"),
        StudyColorTheme(bg: "#A6FBB2", fg: "#000000", name: "Light Mint Green"),
        StudyColorTheme(bg: "#FFC512", fg: "#FFFFFF", name: "Sunflower"),
        StudyColorTheme(bg: "#750851", fg: "#FFFFFF", name: "Velvet"),
        StudyColorTheme(bg: "#C14A09", fg: "#FFFFFF", name: "Brick Orange"),
        StudyColorTheme(bg: "#FE2F4A", fg: "#FFFFFF", name: "Lightish Red"),
        StudyColorTheme(bg: "#0203E2", fg: "#FFFFFF", name: "Pure Blue"),
        StudyColorTheme(bg: "#0A437A", fg: "#FFFFFF", name: "Twilight Blue"),
        StudyColorTheme(bg: "#A50055", fg: "#FFFFFF", name: "Violet Red"),
        StudyColorTheme(bg: "#AE8B0C", fg: "#FFFFFF", name: "Yellowy Brown"),
        StudyColorTheme(bg: "#FD798F", fg: "#FFFFFF", name: "Carnation"),
        StudyColorTheme(bg: "#BFAC05", fg: "#FFFFFF", name: "Muddy Yellow"),
        StudyColorTheme(bg: "#3EAF76", fg: "#FFFFFF", name: "Dark Seafoam Green"),
        StudyColorTheme(bg: "#C74767", fg: "#FFFFFF", name: "Deep Rose"),
        StudyColorTheme(bg: "#B9484E", fg: "#FFFFFF", name: "Dusty Red"),
        StudyColorTheme(bg: "#647D8E", fg: "#FFFFFF", name: "Grey/Blue"),
        StudyColorTheme(bg: "#BFFE28", fg: "#000000", name: "Lemon Lime"),
        StudyColorTheme(bg: "#D725DE", fg: "#FFFFFF", name: "Purple/Pink"),
        StudyColorTheme(bg: "#B29705", fg: "#FFFFFF", name: "Brown Yellow"),
        StudyColorTheme(bg: "#673A3F", fg: "#FFFFFF", name: "Purple Brown"),
        StudyColorTheme(bg: "#A87DC2", fg: "#FFFFFF", name: "Wisteria"),
        StudyColorTheme(bg: "#FAFE4B", fg: "#000000", name: "Banana Yellow"),
        StudyColorTheme(bg: "#C0022F", fg: "#FFFFFF", name: "Lipstick Red"),
        StudyColorTheme(bg: "#0E87CC", fg: "#FFFFFF", name: "Water Blue"),
        StudyColorTheme(bg: "#8D8468", fg: "#FFFFFF", name: "Brown Grey"),
        StudyColorTheme(bg: "#AD03DE", fg: "#FFFFFF", name: "Vibrant Purple"),
        StudyColorTheme(bg: "#8CFF9E", fg: "#000000", name: "Baby Green"),
        StudyColorTheme(bg: "#94AC02", fg: "#FFFFFF", name: "Barf Green"),
        StudyColorTheme(bg: "#C4FFF7", fg: "#000000", name: "Eggshell Blue"),
        StudyColorTheme(bg: "#FDEE73", fg: "#000000", name: "Sandy Yellow"),
        StudyColorTheme(bg: "#33B864", fg: "#FFFFFF", name: "Cool Green"),
        StudyColorTheme(bg: "#758DA3", fg: "#FFFFFF", name: "Blue/Grey"),
        StudyColorTheme(bg: "#F504C9", fg: "#FFFFFF", name: "Hot Magenta"),
        StudyColorTheme(bg: "#77A1B5", fg: "#FFFFFF", name: "Greyblue"),
        StudyColorTheme(bg: "#8756E4", fg: "#FFFFFF", name: "Purpley"),
        StudyColorTheme(bg: "#889717", fg: "#FFFFFF", name: "Baby Shit Green"),
        StudyColorTheme(bg: "#C27E79", fg: "#FFFFFF", name: "Brownish Pink"),
        StudyColorTheme(bg: "#017371", fg: "#FFFFFF", name: "Dark Aquamarine"),
        StudyColorTheme(bg: "#9F8303", fg: "#FFFFFF", name: "Diarrhea"),
        StudyColorTheme(bg: "#F7D560", fg: "#000000", name: "Light Mustard"),
        StudyColorTheme(bg: "#BDF6FE", fg: "#000000", name: "Pale Sky Blue"),
        StudyColorTheme(bg: "#75B84F", fg: "#FFFFFF", name: "Turtle Green"),
        StudyColorTheme(bg: "#9CBB04", fg: "#FFFFFF", name: "Bright Olive"),
        StudyColorTheme(bg: "#29465B", fg: "#FFFFFF", name: "Dark Grey Blue"),
        StudyColorTheme(bg: "#696006", fg: "#FFFFFF", name: "Greeny Brown"),
        StudyColorTheme(bg: "#C1C6FC", fg: "#000000", name: "Light Periwinkle"),
        StudyColorTheme(bg: "#35AD6B", fg: "#FFFFFF", name: "Seaweed Green"),
        StudyColorTheme(bg: "#FFFD37", fg: "#000000", name: "Sunshine Yellow"),
        StudyColorTheme(bg: "#A442A0", fg: "#FFFFFF", name: "Ugly Purple"),
        StudyColorTheme(bg: "#F36196", fg: "#FFFFFF", name: "Medium Pink"),
        StudyColorTheme(bg: "#947706", fg: "#FFFFFF", name: "Puke Brown"),
        StudyColorTheme(bg: "#1E9167", fg: "#FFFFFF", name: "Viridian"),
        StudyColorTheme(bg: "#B5C306", fg: "#FFFFFF", name: "Bile"),
        StudyColorTheme(bg: "#FEFF7F", fg: "#000000", name: "Faded Yellow"),
        StudyColorTheme(bg: "#CFFDBC", fg: "#000000", name: "Very Pale Green"),
        StudyColorTheme(bg: "#0ADD08", fg: "#FFFFFF", name: "Vibrant Green"),
        StudyColorTheme(bg: "#87FD05", fg: "#FFFFFF", name: "Bright Lime"),
        StudyColorTheme(bg: "#1EF876", fg: "#FFFFFF", name: "Spearmint"),
        StudyColorTheme(bg: "#7BFDC7", fg: "#000000", name: "Light Aquamarine"),
        StudyColorTheme(bg: "#BCECAC", fg: "#000000", name: "Light Sage"),
        StudyColorTheme(bg: "#BBF90F", fg: "#000000", name: "Yellowgreen"),
        StudyColorTheme(bg: "#AB9004", fg: "#FFFFFF", name: "Baby Poo"),
        StudyColorTheme(bg: "#1FB57A", fg: "#FFFFFF", name: "Dark Seafoam"),
        StudyColorTheme(bg: "#00555A", fg: "#FFFFFF", name: "Deep Teal"),
        StudyColorTheme(bg: "#A484AC", fg: "#FFFFFF", name: "Heather"),
        StudyColorTheme(bg: "#C45508", fg: "#FFFFFF", name: "Rust Orange"),
        StudyColorTheme(bg: "#3F829D", fg: "#FFFFFF", name: "Dirty Blue"),
        StudyColorTheme(bg: "#548D44", fg: "#FFFFFF", name: "Fern Green"),
        StudyColorTheme(bg: "#C95EFB", fg: "#FFFFFF", name: "Bright Lilac"),
        StudyColorTheme(bg: "#3AE57F", fg: "#FFFFFF", name: "Weird Green"),
        StudyColorTheme(bg: "#016795", fg: "#FFFFFF", name: "Peacock Blue"),
        StudyColorTheme(bg: "#87A922", fg: "#FFFFFF", name: "Avocado Green"),
        StudyColorTheme(bg: "#F0944D", fg: "#FFFFFF", name: "Faded Orange"),
        StudyColorTheme(bg: "#5D1451", fg: "#FFFFFF", name: "Grape Purple"),
        StudyColorTheme(bg: "#D0FE1D", fg: "#000000", name: "Lime Yellow"),
        StudyColorTheme(bg: "#FFA62B", fg: "#FFFFFF", name: "Mango"),
        StudyColorTheme(bg: "#01B44C", fg: "#FFFFFF", name: "Shamrock"),
        StudyColorTheme(bg: "#FF6CB5", fg: "#FFFFFF", name: "Bubblegum"),
        StudyColorTheme(bg: "#6B4247", fg: "#FFFFFF", name: "Purplish Brown"),
        StudyColorTheme(bg: "#C7C10C", fg: "#FFFFFF", name: "Vomit Yellow"),
        StudyColorTheme(bg: "#B7FFFA", fg: "#000000", name: "Pale Cyan"),
        StudyColorTheme(bg: "#AEFF6E", fg: "#000000", name: "Key Lime"),
        StudyColorTheme(bg: "#EC2D01", fg: "#FFFFFF", name: "Tomato Red"),
        StudyColorTheme(bg: "#76FF7B", fg: "#FFFFFF", name: "Lightgreen"),
        StudyColorTheme(bg: "#730039", fg: "#FFFFFF", name: "Merlot"),
        StudyColorTheme(bg: "#040348", fg: "#FFFFFF", name: "Night Blue"),
        StudyColorTheme(bg: "#DF4EC8", fg: "#FFFFFF", name: "Purpleish Pink"),
        StudyColorTheme(bg: "#6ECB3C", fg: "#FFFFFF", name: "Apple"),
        StudyColorTheme(bg: "#8F9805", fg: "#FFFFFF", name: "Baby Poop Green"),
        StudyColorTheme(bg: "#5EDC1F", fg: "#FFFFFF", name: "Green Apple"),
        StudyColorTheme(bg: "#D94FF5", fg: "#FFFFFF", name: "Heliotrope"),
        StudyColorTheme(bg: "#C8FD3D", fg: "#000000", name: "Yellow/Green"),
        StudyColorTheme(bg: "#070D0D", fg: "#FFFFFF", name: "Almost Black"),
        StudyColorTheme(bg: "#4984B8", fg: "#FFFFFF", name: "Cool Blue"),
        StudyColorTheme(bg: "#51B73B", fg: "#FFFFFF", name: "Leafy Green"),
        StudyColorTheme(bg: "#AC7E04", fg: "#FFFFFF", name: "Mustard Brown"),
        StudyColorTheme(bg: "#4E5481", fg: "#FFFFFF", name: "Dusk"),
        StudyColorTheme(bg: "#876E4B", fg: "#FFFFFF", name: "Dull Brown"),
        StudyColorTheme(bg: "#58BC08", fg: "#FFFFFF", name: "Frog Green"),
        StudyColorTheme(bg: "#2FEF10", fg: "#FFFFFF", name: "Vivid Green"),
        StudyColorTheme(bg: "#2DFE54", fg: "#FFFFFF", name: "Bright Light Green"),
        StudyColorTheme(bg: "#9CEF43", fg: "#FFFFFF", name: "Kiwi"),
        StudyColorTheme(bg: "#18D17B", fg: "#FFFFFF", name: "Seaweed"),
        StudyColorTheme(bg: "#35530A", fg: "#FFFFFF", name: "Navy Green"),
        StudyColorTheme(bg: "#1805DB", fg: "#FFFFFF", name: "Ultramarine Blue"),
        StudyColorTheme(bg: "#6258C4", fg: "#FFFFFF", name: "Iris"),
        StudyColorTheme(bg: "#FF964F", fg: "#FFFFFF", name: "Pastel Orange"),
        StudyColorTheme(bg: "#FFAB0F", fg: "#FFFFFF", name: "Yellowish Orange"),
        StudyColorTheme(bg: "#8F8CE7", fg: "#FFFFFF", name: "Perrywinkle"),
        StudyColorTheme(bg: "#24BCA8", fg: "#FFFFFF", name: "Tealish"),
        StudyColorTheme(bg: "#3F012C", fg: "#FFFFFF", name: "Dark Plum"),
        StudyColorTheme(bg: "#CBF85F", fg: "#000000", name: "Pear"),
        StudyColorTheme(bg: "#FF724C", fg: "#FFFFFF", name: "Pinkish Orange"),
        StudyColorTheme(bg: "#280137", fg: "#FFFFFF", name: "Midnight Purple"),
        StudyColorTheme(bg: "#B36FF6", fg: "#FFFFFF", name: "Light Urple"),
        StudyColorTheme(bg: "#48C072", fg: "#FFFFFF", name: "Dark Mint"),
        StudyColorTheme(bg: "#BCCB7A", fg: "#FFFFFF", name: "Greenish Tan"),
        StudyColorTheme(bg: "#A8415B", fg: "#FFFFFF", name: "Light Burgundy"),
        StudyColorTheme(bg: "#06B1C4", fg: "#FFFFFF", name: "Turquoise Blue"),
        StudyColorTheme(bg: "#CD7584", fg: "#FFFFFF", name: "Ugly Pink"),
        StudyColorTheme(bg: "#F1DA7A", fg: "#000000", name: "Sandy"),
        StudyColorTheme(bg: "#FF0490", fg: "#FFFFFF", name: "Electric Pink"),
        StudyColorTheme(bg: "#805B87", fg: "#FFFFFF", name: "Muted Purple"),
        StudyColorTheme(bg: "#50A747", fg: "#FFFFFF", name: "Mid Green"),
        StudyColorTheme(bg: "#A8A495", fg: "#FFFFFF", name: "Greyish"),
        StudyColorTheme(bg: "#CFFF04", fg: "#000000", name: "Neon Yellow"),
        StudyColorTheme(bg: "#FFFF7E", fg: "#000000", name: "Banana"),
        StudyColorTheme(bg: "#FF7FA7", fg: "#FFFFFF", name: "Carnation Pink"),
        StudyColorTheme(bg: "#EF4026", fg: "#FFFFFF", name: "Tomato"),
        StudyColorTheme(bg: "#3C9992", fg: "#FFFFFF", name: "Sea"),
        StudyColorTheme(bg: "#886806", fg: "#FFFFFF", name: "Muddy Brown"),
        StudyColorTheme(bg: "#04F489", fg: "#FFFFFF", name: "Turquoise Green"),
        StudyColorTheme(bg: "#FEF69E", fg: "#000000", name: "Buff"),
        StudyColorTheme(bg: "#CFAF7B", fg: "#FFFFFF", name: "Fawn"),
        StudyColorTheme(bg: "#3B719F", fg: "#FFFFFF", name: "Muted Blue"),
        StudyColorTheme(bg: "#FDC1C5", fg: "#000000", name: "Pale Rose"),
        StudyColorTheme(bg: "#20C073", fg: "#FFFFFF", name: "Dark Mint Green"),
        StudyColorTheme(bg: "#9B5FC0", fg: "#FFFFFF", name: "Amethyst"),
        StudyColorTheme(bg: "#0F9B8E", fg: "#FFFFFF", name: "Blue/Green"),
        StudyColorTheme(bg: "#742802", fg: "#FFFFFF", name: "Chestnut"),
        StudyColorTheme(bg: "#9DB92C", fg: "#FFFFFF", name: "Sick Green"),
        StudyColorTheme(bg: "#A4BF20", fg: "#FFFFFF", name: "Pea"),
        StudyColorTheme(bg: "#CD5909", fg: "#FFFFFF", name: "Rusty Orange"),
        StudyColorTheme(bg: "#ADA587", fg: "#FFFFFF", name: "Stone"),
        StudyColorTheme(bg: "#BE013C", fg: "#FFFFFF", name: "Rose Red"),
        StudyColorTheme(bg: "#B8FFEB", fg: "#000000", name: "Pale Aqua"),
        StudyColorTheme(bg: "#DC4D01", fg: "#FFFFFF", name: "Deep Orange"),
        StudyColorTheme(bg: "#A2653E", fg: "#FFFFFF", name: "Earth"),
        StudyColorTheme(bg: "#638B27", fg: "#FFFFFF", name: "Mossy Green"),
        StudyColorTheme(bg: "#419C03", fg: "#FFFFFF", name: "Grassy Green"),
        StudyColorTheme(bg: "#B1FF65", fg: "#000000", name: "Pale Lime Green"),
        StudyColorTheme(bg: "#9DBCD4", fg: "#FFFFFF", name: "Light Grey Blue"),
        StudyColorTheme(bg: "#77AB56", fg: "#FFFFFF", name: "Asparagus"),
        StudyColorTheme(bg: "#464196", fg: "#FFFFFF", name: "Blueberry"),
        StudyColorTheme(bg: "#990147", fg: "#FFFFFF", name: "Purple Red"),
        StudyColorTheme(bg: "#BEFD73", fg: "#000000", name: "Pale Lime"),
        StudyColorTheme(bg: "#32BF84", fg: "#FFFFFF", name: "Greenish Teal"),
        StudyColorTheme(bg: "#AF6F09", fg: "#FFFFFF", name: "Caramel"),
        StudyColorTheme(bg: "#A0025C", fg: "#FFFFFF", name: "Deep Magenta"),
        StudyColorTheme(bg: "#FFD8B1", fg: "#000000", name: "Light Peach"),
        StudyColorTheme(bg: "#7F4E1E", fg: "#FFFFFF", name: "Milk Chocolate"),
        StudyColorTheme(bg: "#BF9B0C", fg: "#FFFFFF", name: "Ocher"),
        StudyColorTheme(bg: "#6BA353", fg: "#FFFFFF", name: "Off Green"),
        StudyColorTheme(bg: "#F075E6", fg: "#FFFFFF", name: "Purply Pink"),
        StudyColorTheme(bg: "#7BC8F6", fg: "#FFFFFF", name: "Lightblue"),
        StudyColorTheme(bg: "#475F94", fg: "#FFFFFF", name: "Dusky Blue"),
        StudyColorTheme(bg: "#F5BF03", fg: "#FFFFFF", name: "Golden"),
        StudyColorTheme(bg: "#FFFD74", fg: "#000000", name: "Butter Yellow"),
        StudyColorTheme(bg: "#895B7B", fg: "#FFFFFF", name: "Dusky Purple"),
        StudyColorTheme(bg: "#436BAD", fg: "#FFFFFF", name: "French Blue"),
        StudyColorTheme(bg: "#D0C101", fg: "#FFFFFF", name: "Ugly Yellow"),
        StudyColorTheme(bg: "#C6F808", fg: "#000000", name: "Greeny Yellow"),
        StudyColorTheme(bg: "#F43605", fg: "#FFFFFF", name: "Orangish Red"),
        StudyColorTheme(bg: "#02C14D", fg: "#FFFFFF", name: "Shamrock Green"),
        StudyColorTheme(bg: "#B25F03", fg: "#FFFFFF", name: "Orangish Brown"),
        StudyColorTheme(bg: "#2A7E19", fg: "#FFFFFF", name: "Tree Green"),
        StudyColorTheme(bg: "#490648", fg: "#FFFFFF", name: "Deep Violet"),
        StudyColorTheme(bg: "#536267", fg: "#FFFFFF", name: "Gunmetal"),
        StudyColorTheme(bg: "#5A06EF", fg: "#FFFFFF", name: "Blue/Purple"),
        StudyColorTheme(bg: "#CF0234", fg: "#FFFFFF", name: "Cherry"),
        StudyColorTheme(bg: "#C4A661", fg: "#FFFFFF", name: "Sandy Brown"),
        StudyColorTheme(bg: "#978A84", fg: "#FFFFFF", name: "Warm Grey"),
        StudyColorTheme(bg: "#1F0954", fg: "#FFFFFF", name: "Dark Indigo"),
        StudyColorTheme(bg: "#2BB179", fg: "#FFFFFF", name: "Bluey Green"),
        StudyColorTheme(bg: "#C3909B", fg: "#FFFFFF", name: "Grey Pink"),
        StudyColorTheme(bg: "#A66FB5", fg: "#FFFFFF", name: "Soft Purple"),
        StudyColorTheme(bg: "#770001", fg: "#FFFFFF", name: "Blood"),
        StudyColorTheme(bg: "#922B05", fg: "#FFFFFF", name: "Brown Red"),
        StudyColorTheme(bg: "#7D7F7C", fg: "#FFFFFF", name: "Medium Grey"),
        StudyColorTheme(bg: "#990F4B", fg: "#FFFFFF", name: "Berry"),
        StudyColorTheme(bg: "#8F7303", fg: "#FFFFFF", name: "Poo"),
        StudyColorTheme(bg: "#C83CB9", fg: "#FFFFFF", name: "Purpley Pink"),
        StudyColorTheme(bg: "#FEA993", fg: "#FFFFFF", name: "Light Salmon"),
        StudyColorTheme(bg: "#ACBB0D", fg: "#FFFFFF", name: "Snot"),
        StudyColorTheme(bg: "#C071FE", fg: "#FFFFFF", name: "Easter Purple"),
        StudyColorTheme(bg: "#CCFD7F", fg: "#000000", name: "Light Yellow Green"),
        StudyColorTheme(bg: "#828344", fg: "#FFFFFF", name: "Drab"),
        StudyColorTheme(bg: "#FFC5CB", fg: "#000000", name: "Light Rose"),
        StudyColorTheme(bg: "#AB1239", fg: "#FFFFFF", name: "Rouge"),
        StudyColorTheme(bg: "#B0054B", fg: "#FFFFFF", name: "Purplish Red"),
        StudyColorTheme(bg: "#99CC04", fg: "#FFFFFF", name: "Slime Green"),
        StudyColorTheme(bg: "#937C00", fg: "#FFFFFF", name: "Baby Poop"),
        StudyColorTheme(bg: "#019529", fg: "#FFFFFF", name: "Irish Green"),
        StudyColorTheme(bg: "#EF1DE7", fg: "#FFFFFF", name: "Pink/Purple"),
        StudyColorTheme(bg: "#42B395", fg: "#FFFFFF", name: "Greeny Blue"),
        StudyColorTheme(bg: "#9D5783", fg: "#FFFFFF", name: "Light Plum"),
        StudyColorTheme(bg: "#C8ACA9", fg: "#FFFFFF", name: "Pinkish Grey"),
        StudyColorTheme(bg: "#C87606", fg: "#FFFFFF", name: "Dirty Orange"),
        StudyColorTheme(bg: "#AA2704", fg: "#FFFFFF", name: "Rust Red"),
        StudyColorTheme(bg: "#E4CBFF", fg: "#000000", name: "Pale Lilac"),
        StudyColorTheme(bg: "#FA4224", fg: "#FFFFFF", name: "Orangey Red"),
        StudyColorTheme(bg: "#0804F9", fg: "#FFFFFF", name: "Primary Blue"),
        StudyColorTheme(bg: "#5CB200", fg: "#FFFFFF", name: "Kermit Green"),
        StudyColorTheme(bg: "#76424E", fg: "#FFFFFF", name: "Brownish Purple"),
        StudyColorTheme(bg: "#6C7A0E", fg: "#FFFFFF", name: "Murky Green"),
        StudyColorTheme(bg: "#FBDD7E", fg: "#000000", name: "Wheat"),
        StudyColorTheme(bg: "#2A0134", fg: "#FFFFFF", name: "Very Dark Purple"),
        StudyColorTheme(bg: "#044A05", fg: "#FFFFFF", name: "Bottle Green"),
        StudyColorTheme(bg: "#FD4659", fg: "#FFFFFF", name: "Watermelon"),
        StudyColorTheme(bg: "#0D75F8", fg: "#FFFFFF", name: "Deep Sky Blue"),
        StudyColorTheme(bg: "#FE0002", fg: "#FFFFFF", name: "Fire Engine Red"),
        StudyColorTheme(bg: "#CB9D06", fg: "#FFFFFF", name: "Yellow Ochre"),
        StudyColorTheme(bg: "#FB7D07", fg: "#FFFFFF", name: "Pumpkin Orange"),
        StudyColorTheme(bg: "#B9CC81", fg: "#FFFFFF", name: "Pale Olive"),
        StudyColorTheme(bg: "#EDC8FF", fg: "#000000", name: "Light Lilac"),
        StudyColorTheme(bg: "#61E160", fg: "#FFFFFF", name: "Lightish Green"),
        StudyColorTheme(bg: "#8AB8FE", fg: "#FFFFFF", name: "Carolina Blue"),
        StudyColorTheme(bg: "#920A4E", fg: "#FFFFFF", name: "Mulberry"),
        StudyColorTheme(bg: "#FE02A2", fg: "#FFFFFF", name: "Shocking Pink"),
        StudyColorTheme(bg: "#9A3001", fg: "#FFFFFF", name: "Auburn"),
        StudyColorTheme(bg: "#65FE08", fg: "#FFFFFF", name: "Bright Lime Green"),
        StudyColorTheme(bg: "#BEFDB7", fg: "#000000", name: "Celadon"),
        StudyColorTheme(bg: "#B17261", fg: "#FFFFFF", name: "Pinkish Brown"),
        StudyColorTheme(bg: "#885F01", fg: "#FFFFFF", name: "Poo Brown"),
        StudyColorTheme(bg: "#02CCFE", fg: "#FFFFFF", name: "Bright Sky Blue"),
        StudyColorTheme(bg: "#C1FD95", fg: "#000000", name: "Celery"),
        StudyColorTheme(bg: "#836539", fg: "#FFFFFF", name: "Dirt Brown"),
        StudyColorTheme(bg: "#FB2943", fg: "#FFFFFF", name: "Strawberry"),
        StudyColorTheme(bg: "#84B701", fg: "#FFFFFF", name: "Dark Lime"),
        StudyColorTheme(bg: "#B66325", fg: "#FFFFFF", name: "Copper"),
        StudyColorTheme(bg: "#7F5112", fg: "#FFFFFF", name: "Medium Brown"),
        StudyColorTheme(bg: "#5FA052", fg: "#FFFFFF", name: "Muted Green"),
        StudyColorTheme(bg: "#6DEDFD", fg: "#000000", name: "robins Egg"),
        StudyColorTheme(bg: "#0BF9EA", fg: "#FFFFFF", name: "Bright Aqua"),
        StudyColorTheme(bg: "#C760FF", fg: "#FFFFFF", name: "Bright Lavender"),
        StudyColorTheme(bg: "#F6CEFC", fg: "#000000", name: "Very Light Purple"),
        StudyColorTheme(bg: "#155084", fg: "#FFFFFF", name: "Light Navy"),
        StudyColorTheme(bg: "#F5054F", fg: "#FFFFFF", name: "Pink Red"),
        StudyColorTheme(bg: "#645403", fg: "#FFFFFF", name: "Olive Brown"),
        StudyColorTheme(bg: "#7A5901", fg: "#FFFFFF", name: "Poop Brown"),
        StudyColorTheme(bg: "#A8B504", fg: "#FFFFFF", name: "Mustard Green"),
        StudyColorTheme(bg: "#3D9973", fg: "#FFFFFF", name: "Ocean Green"),
        StudyColorTheme(bg: "#76A973", fg: "#FFFFFF", name: "Dusty Green"),
        StudyColorTheme(bg: "#2E5A88", fg: "#FFFFFF", name: "Light Navy Blue"),
        StudyColorTheme(bg: "#0BF77D", fg: "#FFFFFF", name: "Minty Green"),
        StudyColorTheme(bg: "#BD6C48", fg: "#FFFFFF", name: "Adobe"),
        StudyColorTheme(bg: "#AC1DB8", fg: "#FFFFFF", name: "Barney"),
        StudyColorTheme(bg: "#2BAF6A", fg: "#FFFFFF", name: "Jade Green"),
        StudyColorTheme(bg: "#26F7FD", fg: "#FFFFFF", name: "Bright Light Blue"),
        StudyColorTheme(bg: "#AEFD6C", fg: "#000000", name: "Light Lime"),
        StudyColorTheme(bg: "#9B8F55", fg: "#FFFFFF", name: "Dark Khaki"),
        StudyColorTheme(bg: "#FFAD01", fg: "#FFFFFF", name: "Orange Yellow"),
        StudyColorTheme(bg: "#C69C04", fg: "#FFFFFF", name: "Ocre"),
        StudyColorTheme(bg: "#F4D054", fg: "#000000", name: "Maize"),
        StudyColorTheme(bg: "#DE9DAC", fg: "#FFFFFF", name: "Faded Pink"),
        StudyColorTheme(bg: "#05480D", fg: "#FFFFFF", name: "British Racing Green"),
        StudyColorTheme(bg: "#C9AE74", fg: "#FFFFFF", name: "Sandstone"),
        StudyColorTheme(bg: "#60460F", fg: "#FFFFFF", name: "Mud Brown"),
        StudyColorTheme(bg: "#98F6B0", fg: "#000000", name: "Light Sea Green"),
        StudyColorTheme(bg: "#8AF1FE", fg: "#000000", name: "Robin Egg Blue"),
        StudyColorTheme(bg: "#2EE8BB", fg: "#FFFFFF", name: "Aqua Marine"),
        StudyColorTheme(bg: "#11875D", fg: "#FFFFFF", name: "Dark Sea Green"),
        StudyColorTheme(bg: "#FDB0C0", fg: "#000000", name: "Soft Pink"),
        StudyColorTheme(bg: "#B16002", fg: "#FFFFFF", name: "Orangey Brown"),
        StudyColorTheme(bg: "#F7022A", fg: "#FFFFFF", name: "Cherry Red"),
        StudyColorTheme(bg: "#D5AB09", fg: "#FFFFFF", name: "Burnt Yellow"),
        StudyColorTheme(bg: "#86775F", fg: "#FFFFFF", name: "Brownish Grey"),
        StudyColorTheme(bg: "#C69F59", fg: "#FFFFFF", name: "Camel"),
        StudyColorTheme(bg: "#7A687F", fg: "#FFFFFF", name: "Purplish Grey"),
        StudyColorTheme(bg: "#042E60", fg: "#FFFFFF", name: "Marine"),
        StudyColorTheme(bg: "#C88D94", fg: "#FFFFFF", name: "Greyish Pink"),
        StudyColorTheme(bg: "#A5FBD5", fg: "#000000", name: "Pale Turquoise"),
        StudyColorTheme(bg: "#FFFE71", fg: "#000000", name: "Pastel Yellow"),
        StudyColorTheme(bg: "#6241C7", fg: "#FFFFFF", name: "Bluey Purple"),
        StudyColorTheme(bg: "#FFFE40", fg: "#000000", name: "Canary Yellow"),
        StudyColorTheme(bg: "#D3494E", fg: "#FFFFFF", name: "Faded Red"),
        StudyColorTheme(bg: "#985E2B", fg: "#FFFFFF", name: "Sepia"),
        StudyColorTheme(bg: "#A6814C", fg: "#FFFFFF", name: "Coffee"),
        StudyColorTheme(bg: "#FF08E8", fg: "#FFFFFF", name: "Bright Magenta"),
        StudyColorTheme(bg: "#9D7651", fg: "#FFFFFF", name: "Mocha"),
        StudyColorTheme(bg: "#98568D", fg: "#FFFFFF", name: "Purpleish"),
        StudyColorTheme(bg: "#9E003A", fg: "#FFFFFF", name: "Cranberry"),
        StudyColorTheme(bg: "#287C37", fg: "#FFFFFF", name: "Darkish Green"),
        StudyColorTheme(bg: "#B96902", fg: "#FFFFFF", name: "Brown Orange"),
        StudyColorTheme(bg: "#BA6873", fg: "#FFFFFF", name: "Dusky Rose"),
        StudyColorTheme(bg: "#FF7855", fg: "#FFFFFF", name: "Melon"),
        StudyColorTheme(bg: "#94B21C", fg: "#FFFFFF", name: "Sickly Green"),
        StudyColorTheme(bg: "#C5C9C7", fg: "#FFFFFF", name: "Silver"),
        StudyColorTheme(bg: "#661AEE", fg: "#FFFFFF", name: "Purply Blue"),
        StudyColorTheme(bg: "#6140EF", fg: "#FFFFFF", name: "Purpleish Blue"),
        StudyColorTheme(bg: "#9BE5AA", fg: "#000000", name: "Hospital Green"),
        StudyColorTheme(bg: "#7B5804", fg: "#FFFFFF", name: "Shit Brown"),
        StudyColorTheme(bg: "#276AB3", fg: "#FFFFFF", name: "Mid Blue"),
        StudyColorTheme(bg: "#FEB308", fg: "#FFFFFF", name: "Amber"),
        StudyColorTheme(bg: "#8CFD7E", fg: "#000000", name: "Easter Green"),
        StudyColorTheme(bg: "#6488EA", fg: "#FFFFFF", name: "Soft Blue"),
        StudyColorTheme(bg: "#056EEE", fg: "#FFFFFF", name: "Cerulean Blue"),
        StudyColorTheme(bg: "#B27A01", fg: "#FFFFFF", name: "Golden Brown"),
        StudyColorTheme(bg: "#0FFEF9", fg: "#FFFFFF", name: "Bright Turquoise"),
        StudyColorTheme(bg: "#FA2A55", fg: "#FFFFFF", name: "Red Pink"),
        StudyColorTheme(bg: "#820747", fg: "#FFFFFF", name: "Red Purple"),
        StudyColorTheme(bg: "#7A6A4F", fg: "#FFFFFF", name: "Greyish Brown"),
        StudyColorTheme(bg: "#F4320C", fg: "#FFFFFF", name: "Vermillion"),
        StudyColorTheme(bg: "#A13905", fg: "#FFFFFF", name: "Russet"),
        StudyColorTheme(bg: "#6F828A", fg: "#FFFFFF", name: "Steel Grey"),
        StudyColorTheme(bg: "#A55AF4", fg: "#FFFFFF", name: "Lighter Purple"),
        StudyColorTheme(bg: "#AD0AFD", fg: "#FFFFFF", name: "Bright Violet"),
        StudyColorTheme(bg: "#004577", fg: "#FFFFFF", name: "Prussian Blue"),
        StudyColorTheme(bg: "#658D6D", fg: "#FFFFFF", name: "Slate Green"),
        StudyColorTheme(bg: "#CA7B80", fg: "#FFFFFF", name: "Dirty Pink"),
        StudyColorTheme(bg: "#005249", fg: "#FFFFFF", name: "Dark Blue Green"),
        StudyColorTheme(bg: "#2B5D34", fg: "#FFFFFF", name: "Pine"),
        StudyColorTheme(bg: "#BFF128", fg: "#000000", name: "Yellowy Green"),
        StudyColorTheme(bg: "#B59410", fg: "#FFFFFF", name: "Dark Gold"),
        StudyColorTheme(bg: "#2976BB", fg: "#FFFFFF", name: "Bluish"),
        StudyColorTheme(bg: "#014182", fg: "#FFFFFF", name: "Darkish Blue"),
        StudyColorTheme(bg: "#BB3F3F", fg: "#FFFFFF", name: "Dull Red"),
        StudyColorTheme(bg: "#FC2647", fg: "#FFFFFF", name: "Pinky Red"),
        StudyColorTheme(bg: "#A87900", fg: "#FFFFFF", name: "Bronze"),
        StudyColorTheme(bg: "#82CBB2", fg: "#FFFFFF", name: "Pale Teal"),
        StudyColorTheme(bg: "#667C3E", fg: "#FFFFFF", name: "Military Green"),
        StudyColorTheme(bg: "#FE46A5", fg: "#FFFFFF", name: "Barbie Pink"),
        StudyColorTheme(bg: "#FE83CC", fg: "#FFFFFF", name: "Bubblegum Pink"),
        StudyColorTheme(bg: "#94A617", fg: "#FFFFFF", name: "Pea Soup Green"),
        StudyColorTheme(bg: "#A88905", fg: "#FFFFFF", name: "Dark Mustard"),
        StudyColorTheme(bg: "#7F5F00", fg: "#FFFFFF", name: "Shit"),
        StudyColorTheme(bg: "#9E43A2", fg: "#FFFFFF", name: "Medium Purple"),
        StudyColorTheme(bg: "#062E03", fg: "#FFFFFF", name: "Very Dark Green"),
        StudyColorTheme(bg: "#8A6E45", fg: "#FFFFFF", name: "Dirt"),
        StudyColorTheme(bg: "#CC7A8B", fg: "#FFFFFF", name: "Dusky Pink"),
        StudyColorTheme(bg: "#9E0168", fg: "#FFFFFF", name: "Red Violet"),
        StudyColorTheme(bg: "#FDFF38", fg: "#000000", name: "Lemon Yellow"),
        StudyColorTheme(bg: "#C0FA8B", fg: "#000000", name: "Pistachio"),
        StudyColorTheme(bg: "#EEDC5B", fg: "#000000", name: "Dull Yellow"),
        StudyColorTheme(bg: "#7EBD01", fg: "#FFFFFF", name: "Dark Lime Green"),
        StudyColorTheme(bg: "#3B5B92", fg: "#FFFFFF", name: "Denim Blue"),
        StudyColorTheme(bg: "#01889F", fg: "#FFFFFF", name: "Teal Blue"),
        StudyColorTheme(bg: "#3D7AFD", fg: "#FFFFFF", name: "Lightish Blue"),
        StudyColorTheme(bg: "#5F34E7", fg: "#FFFFFF", name: "Purpley Blue"),
        StudyColorTheme(bg: "#6D5ACF", fg: "#FFFFFF", name: "Light Indigo"),
        StudyColorTheme(bg: "#748500", fg: "#FFFFFF", name: "Swamp Green"),
        StudyColorTheme(bg: "#706C11", fg: "#FFFFFF", name: "Brown Green"),
        StudyColorTheme(bg: "#3C0008", fg: "#FFFFFF", name: "Dark Maroon"),
        StudyColorTheme(bg: "#CB00F5", fg: "#FFFFFF", name: "Hot Purple"),
        StudyColorTheme(bg: "#002D04", fg: "#FFFFFF", name: "Dark Forest Green"),
        StudyColorTheme(bg: "#658CBB", fg: "#FFFFFF", name: "Faded Blue"),
        StudyColorTheme(bg: "#749551", fg: "#FFFFFF", name: "Drab Green"),
        StudyColorTheme(bg: "#B9FF66", fg: "#000000", name: "Light Lime Green"),
        StudyColorTheme(bg: "#9DC100", fg: "#FFFFFF", name: "Snot Green"),
        StudyColorTheme(bg: "#FAEE66", fg: "#000000", name: "Yellowish"),
        StudyColorTheme(bg: "#7EFBB3", fg: "#000000", name: "Light Blue Green"),
        StudyColorTheme(bg: "#7B002C", fg: "#FFFFFF", name: "Bordeaux"),
        StudyColorTheme(bg: "#C292A1", fg: "#FFFFFF", name: "Light Mauve"),
        StudyColorTheme(bg: "#017B92", fg: "#FFFFFF", name: "Ocean"),
        StudyColorTheme(bg: "#FCC006", fg: "#FFFFFF", name: "Marigold"),
        StudyColorTheme(bg: "#657432", fg: "#FFFFFF", name: "Muddy Green"),
        StudyColorTheme(bg: "#D8863B", fg: "#FFFFFF", name: "Dull Orange"),
        StudyColorTheme(bg: "#738595", fg: "#FFFFFF", name: "Steel"),
        StudyColorTheme(bg: "#AA23FF", fg: "#FFFFFF", name: "Electric Purple"),
        StudyColorTheme(bg: "#9B7A01", fg: "#FFFFFF", name: "Yellowish Brown"),
        StudyColorTheme(bg: "#F29E8E", fg: "#FFFFFF", name: "Blush"),
        StudyColorTheme(bg: "#6FC276", fg: "#FFFFFF", name: "Soft Green"),
        StudyColorTheme(bg: "#FF5B00", fg: "#FFFFFF", name: "Bright Orange"),
        StudyColorTheme(bg: "#FDFF52", fg: "#000000", name: "Lemon"),
        StudyColorTheme(bg: "#866F85", fg: "#FFFFFF", name: "Purple Grey"),
        StudyColorTheme(bg: "#EECFFE", fg: "#000000", name: "Pale Lavender"),
        StudyColorTheme(bg: "#510AC9", fg: "#FFFFFF", name: "Violet Blue"),
        StudyColorTheme(bg: "#4F9153", fg: "#FFFFFF", name: "Light Forest Green"),
        StudyColorTheme(bg: "#9F2305", fg: "#FFFFFF", name: "Burnt Red"),
        StudyColorTheme(bg: "#728639", fg: "#FFFFFF", name: "Khaki Green"),
        StudyColorTheme(bg: "#DE0C62", fg: "#FFFFFF", name: "Cerise"),
        StudyColorTheme(bg: "#916E99", fg: "#FFFFFF", name: "Faded Purple"),
        StudyColorTheme(bg: "#FFB16D", fg: "#FFFFFF", name: "Apricot"),
        StudyColorTheme(bg: "#3C4D03", fg: "#FFFFFF", name: "Dark Olive Green"),
        StudyColorTheme(bg: "#7F7053", fg: "#FFFFFF", name: "Grey Brown"),
        StudyColorTheme(bg: "#77926F", fg: "#FFFFFF", name: "Green Grey"),
        StudyColorTheme(bg: "#010FCC", fg: "#FFFFFF", name: "True Blue"),
        StudyColorTheme(bg: "#CEAEFA", fg: "#FFFFFF", name: "Pale Violet"),
        StudyColorTheme(bg: "#8F99FB", fg: "#FFFFFF", name: "Periwinkle Blue"),
        StudyColorTheme(bg: "#C6FCFF", fg: "#000000", name: "Light Sky Blue"),
        StudyColorTheme(bg: "#5539CC", fg: "#FFFFFF", name: "Blurple"),
        StudyColorTheme(bg: "#544E03", fg: "#FFFFFF", name: "Green Brown"),
        StudyColorTheme(bg: "#017A79", fg: "#FFFFFF", name: "Bluegreen"),
        StudyColorTheme(bg: "#C9B003", fg: "#FFFFFF", name: "Brownish Yellow"),
        StudyColorTheme(bg: "#929901", fg: "#FFFFFF", name: "Pea Soup"),
        StudyColorTheme(bg: "#0B5509", fg: "#FFFFFF", name: "Forest"),
        StudyColorTheme(bg: "#A00498", fg: "#FFFFFF", name: "Barney Purple"),
        StudyColorTheme(bg: "#2000B1", fg: "#FFFFFF", name: "Ultramarine"),
        StudyColorTheme(bg: "#94568C", fg: "#FFFFFF", name: "Purplish"),
        StudyColorTheme(bg: "#C2BE0E", fg: "#FFFFFF", name: "Puke Yellow"),
        StudyColorTheme(bg: "#748B97", fg: "#FFFFFF", name: "Bluish Grey"),
        StudyColorTheme(bg: "#665FD1", fg: "#FFFFFF", name: "Dark Periwinkle"),
        StudyColorTheme(bg: "#9C6DA5", fg: "#FFFFFF", name: "Dark Lilac"),
        StudyColorTheme(bg: "#C44240", fg: "#FFFFFF", name: "Reddish"),
        StudyColorTheme(bg: "#A24857", fg: "#FFFFFF", name: "Light Maroon"),
        StudyColorTheme(bg: "#825F87", fg: "#FFFFFF", name: "Dusty Purple"),
        StudyColorTheme(bg: "#C9643B", fg: "#FFFFFF", name: "Terra Cotta"),
        StudyColorTheme(bg: "#90B134", fg: "#FFFFFF", name: "Avocado"),
        StudyColorTheme(bg: "#01386A", fg: "#FFFFFF", name: "Marine Blue"),
        StudyColorTheme(bg: "#25A36F", fg: "#FFFFFF", name: "Teal Green"),
        StudyColorTheme(bg: "#59656D", fg: "#FFFFFF", name: "Slate Grey"),
        StudyColorTheme(bg: "#75FD63", fg: "#FFFFFF", name: "Lighter Green"),
        StudyColorTheme(bg: "#21FC0D", fg: "#FFFFFF", name: "Electric Green"),
        StudyColorTheme(bg: "#5A86AD", fg: "#FFFFFF", name: "Dusty Blue"),
        StudyColorTheme(bg: "#FEC615", fg: "#FFFFFF", name: "Golden Yellow"),
        StudyColorTheme(bg: "#FFFD01", fg: "#000000", name: "Bright Yellow"),
        StudyColorTheme(bg: "#DFC5FE", fg: "#000000", name: "Light Lavender"),
        StudyColorTheme(bg: "#B26400", fg: "#FFFFFF", name: "Umber"),
        StudyColorTheme(bg: "#7F5E00", fg: "#FFFFFF", name: "Poop"),
        StudyColorTheme(bg: "#DE7E5D", fg: "#FFFFFF", name: "Dark Peach"),
        StudyColorTheme(bg: "#048243", fg: "#FFFFFF", name: "Jungle Green"),
        StudyColorTheme(bg: "#3B638C", fg: "#FFFFFF", name: "Denim"),
        StudyColorTheme(bg: "#B79400", fg: "#FFFFFF", name: "Yellow Brown"),
        StudyColorTheme(bg: "#84597E", fg: "#FFFFFF", name: "Dull Purple"),
        StudyColorTheme(bg: "#411900", fg: "#FFFFFF", name: "Chocolate Brown"),
        StudyColorTheme(bg: "#7B0323", fg: "#FFFFFF", name: "Wine Red"),
        StudyColorTheme(bg: "#04D9FF", fg: "#FFFFFF", name: "Neon Blue"),
        StudyColorTheme(bg: "#667E2C", fg: "#FFFFFF", name: "Dirty Green"),
        StudyColorTheme(bg: "#FBEEAC", fg: "#000000", name: "Light Tan"),
        StudyColorTheme(bg: "#D7FFFE", fg: "#000000", name: "Ice Blue"),
        StudyColorTheme(bg: "#4E7496", fg: "#FFFFFF", name: "Cadet Blue"),
        StudyColorTheme(bg: "#874C62", fg: "#FFFFFF", name: "Dark Mauve"),
        StudyColorTheme(bg: "#D5FFFF", fg: "#000000", name: "Very Light Blue"),
        StudyColorTheme(bg: "#826D8C", fg: "#FFFFFF", name: "Grey Purple"),
        StudyColorTheme(bg: "#FFBACD", fg: "#000000", name: "Pastel Pink"),
        StudyColorTheme(bg: "#D1FFBD", fg: "#000000", name: "Very Light Green"),
        StudyColorTheme(bg: "#448EE4", fg: "#FFFFFF", name: "Dark Sky Blue"),
        StudyColorTheme(bg: "#05472A", fg: "#FFFFFF", name: "Evergreen"),
        StudyColorTheme(bg: "#D5869D", fg: "#FFFFFF", name: "Dull Pink"),
        StudyColorTheme(bg: "#3D0734", fg: "#FFFFFF", name: "Aubergine"),
        StudyColorTheme(bg: "#4A0100", fg: "#FFFFFF", name: "Mahogany"),
        StudyColorTheme(bg: "#F8481C", fg: "#FFFFFF", name: "Reddish Orange"),
        StudyColorTheme(bg: "#02590F", fg: "#FFFFFF", name: "Deep Green"),
        StudyColorTheme(bg: "#89A203", fg: "#FFFFFF", name: "Vomit Green"),
        StudyColorTheme(bg: "#E03FD8", fg: "#FFFFFF", name: "Purple Pink"),
        StudyColorTheme(bg: "#D58A94", fg: "#FFFFFF", name: "Dusty Pink"),
        StudyColorTheme(bg: "#7BB274", fg: "#FFFFFF", name: "Faded Green"),
        StudyColorTheme(bg: "#526525", fg: "#FFFFFF", name: "Camo Green"),
        StudyColorTheme(bg: "#C94CBE", fg: "#FFFFFF", name: "Pinky Purple"),
        StudyColorTheme(bg: "#DB4BDA", fg: "#FFFFFF", name: "Pink Purple"),
        StudyColorTheme(bg: "#9E3623", fg: "#FFFFFF", name: "Brownish Red"),
        StudyColorTheme(bg: "#B5485D", fg: "#FFFFFF", name: "Dark Rose"),
        StudyColorTheme(bg: "#735C12", fg: "#FFFFFF", name: "Mud"),
        StudyColorTheme(bg: "#9C6D57", fg: "#FFFFFF", name: "Brownish"),
        StudyColorTheme(bg: "#028F1E", fg: "#FFFFFF", name: "Emerald Green"),
        StudyColorTheme(bg: "#B1916E", fg: "#FFFFFF", name: "Pale Brown"),
        StudyColorTheme(bg: "#49759C", fg: "#FFFFFF", name: "Dull Blue"),
        StudyColorTheme(bg: "#A0450E", fg: "#FFFFFF", name: "Burnt Umber"),
        StudyColorTheme(bg: "#39AD48", fg: "#FFFFFF", name: "Medium Green"),
        StudyColorTheme(bg: "#B66A50", fg: "#FFFFFF", name: "Clay"),
        StudyColorTheme(bg: "#8CFFDB", fg: "#000000", name: "Light Aqua"),
        StudyColorTheme(bg: "#A4BE5C", fg: "#FFFFFF", name: "Light Olive Green"),
        StudyColorTheme(bg: "#CB7723", fg: "#FFFFFF", name: "Brownish Orange"),
        StudyColorTheme(bg: "#05696B", fg: "#FFFFFF", name: "Dark Aqua"),
        StudyColorTheme(bg: "#CE5DAE", fg: "#FFFFFF", name: "Purplish Pink"),
        StudyColorTheme(bg: "#C85A53", fg: "#FFFFFF", name: "Dark Salmon"),
        StudyColorTheme(bg: "#96AE8D", fg: "#FFFFFF", name: "Greenish Grey"),
        StudyColorTheme(bg: "#1FA774", fg: "#FFFFFF", name: "Jade"),
        StudyColorTheme(bg: "#7A9703", fg: "#FFFFFF", name: "Ugly Green"),
        StudyColorTheme(bg: "#AC9362", fg: "#FFFFFF", name: "Dark Beige"),
        StudyColorTheme(bg: "#01A049", fg: "#FFFFFF", name: "Emerald"),
        StudyColorTheme(bg: "#D9544D", fg: "#FFFFFF", name: "Pale Red"),
        StudyColorTheme(bg: "#FA5FF7", fg: "#FFFFFF", name: "Light Magenta"),
        StudyColorTheme(bg: "#82CAFC", fg: "#FFFFFF", name: "Sky"),
        StudyColorTheme(bg: "#ACFFFC", fg: "#000000", name: "Light Cyan"),
        StudyColorTheme(bg: "#FCB001", fg: "#FFFFFF", name: "Yellow Orange"),
        StudyColorTheme(bg: "#910951", fg: "#FFFFFF", name: "Reddish Purple"),
        StudyColorTheme(bg: "#FE2C54", fg: "#FFFFFF", name: "Reddish Pink"),
        StudyColorTheme(bg: "#C875C4", fg: "#FFFFFF", name: "Orchid"),
        StudyColorTheme(bg: "#CDC50A", fg: "#FFFFFF", name: "Dirty Yellow"),
        StudyColorTheme(bg: "#FD411E", fg: "#FFFFFF", name: "Orange Red"),
        StudyColorTheme(bg: "#9A0200", fg: "#FFFFFF", name: "Deep Red"),
        StudyColorTheme(bg: "#BE6400", fg: "#FFFFFF", name: "Orange Brown"),
        StudyColorTheme(bg: "#030AA7", fg: "#FFFFFF", name: "Cobalt Blue"),
        StudyColorTheme(bg: "#FE019A", fg: "#FFFFFF", name: "Neon Pink"),
        StudyColorTheme(bg: "#F7879A", fg: "#FFFFFF", name: "Rose Pink"),
        StudyColorTheme(bg: "#887191", fg: "#FFFFFF", name: "Greyish Purple"),
        StudyColorTheme(bg: "#B00149", fg: "#FFFFFF", name: "Raspberry"),
        StudyColorTheme(bg: "#12E193", fg: "#FFFFFF", name: "Aqua Green"),
        StudyColorTheme(bg: "#FE7B7C", fg: "#FFFFFF", name: "Salmon Pink"),
        StudyColorTheme(bg: "#FF9408", fg: "#FFFFFF", name: "Tangerine"),
        StudyColorTheme(bg: "#6A6E09", fg: "#FFFFFF", name: "Brownish Green"),
        StudyColorTheme(bg: "#8B2E16", fg: "#FFFFFF", name: "Red Brown"),
        StudyColorTheme(bg: "#696112", fg: "#FFFFFF", name: "Greenish Brown"),
        StudyColorTheme(bg: "#E17701", fg: "#FFFFFF", name: "Pumpkin"),
        StudyColorTheme(bg: "#0A481E", fg: "#FFFFFF", name: "Pine Green"),
        StudyColorTheme(bg: "#343837", fg: "#FFFFFF", name: "Charcoal"),
        StudyColorTheme(bg: "#FFB7CE", fg: "#000000", name: "Baby Pink"),
        StudyColorTheme(bg: "#6A79F7", fg: "#FFFFFF", name: "Cornflower"),
        StudyColorTheme(bg: "#5D06E9", fg: "#FFFFFF", name: "Blue Violet"),
        StudyColorTheme(bg: "#3D1C02", fg: "#FFFFFF", name: "Chocolate"),
        StudyColorTheme(bg: "#82A67D", fg: "#FFFFFF", name: "Greyish Green"),
        StudyColorTheme(bg: "#BE0119", fg: "#FFFFFF", name: "Scarlet"),
        StudyColorTheme(bg: "#C9FF27", fg: "#000000", name: "Green Yellow"),
        StudyColorTheme(bg: "#373E02", fg: "#FFFFFF", name: "Dark Olive"),
        StudyColorTheme(bg: "#A9561E", fg: "#FFFFFF", name: "Sienna"),
        StudyColorTheme(bg: "#CAA0FF", fg: "#FFFFFF", name: "Pastel Purple"),
        StudyColorTheme(bg: "#CA6641", fg: "#FFFFFF", name: "Terracotta"),
        StudyColorTheme(bg: "#02D8E9", fg: "#FFFFFF", name: "Aqua Blue"),
        StudyColorTheme(bg: "#88B378", fg: "#FFFFFF", name: "Sage Green"),
        StudyColorTheme(bg: "#980002", fg: "#FFFFFF", name: "Blood Red"),
        StudyColorTheme(bg: "#CB0162", fg: "#FFFFFF", name: "Deep Pink"),
        StudyColorTheme(bg: "#5CAC2D", fg: "#FFFFFF", name: "Grass"),
        StudyColorTheme(bg: "#769958", fg: "#FFFFFF", name: "Moss"),
        StudyColorTheme(bg: "#A2BFFE", fg: "#FFFFFF", name: "Pastel Blue"),
        StudyColorTheme(bg: "#10A674", fg: "#FFFFFF", name: "Bluish Green"),
        StudyColorTheme(bg: "#06B48B", fg: "#FFFFFF", name: "Green Blue"),
        StudyColorTheme(bg: "#AF884A", fg: "#FFFFFF", name: "Dark Tan"),
        StudyColorTheme(bg: "#0B8B87", fg: "#FFFFFF", name: "Greenish Blue"),
        StudyColorTheme(bg: "#FFA756", fg: "#FFFFFF", name: "Pale Orange"),
        StudyColorTheme(bg: "#A2A415", fg: "#FFFFFF", name: "Vomit"),
        StudyColorTheme(bg: "#154406", fg: "#FFFFFF", name: "Forrest Green"),
        StudyColorTheme(bg: "#856798", fg: "#FFFFFF", name: "Dark Lavender"),
        StudyColorTheme(bg: "#34013F", fg: "#FFFFFF", name: "Dark Violet"),
        StudyColorTheme(bg: "#632DE9", fg: "#FFFFFF", name: "Purple Blue"),
        StudyColorTheme(bg: "#0A888A", fg: "#FFFFFF", name: "Dark Cyan"),
        StudyColorTheme(bg: "#6F7632", fg: "#FFFFFF", name: "Olive Drab"),
        StudyColorTheme(bg: "#D46A7E", fg: "#FFFFFF", name: "Pinkish"),
        StudyColorTheme(bg: "#1E488F", fg: "#FFFFFF", name: "Cobalt"),
        StudyColorTheme(bg: "#BC13FE", fg: "#FFFFFF", name: "Neon Purple"),
        StudyColorTheme(bg: "#7EF4CC", fg: "#000000", name: "Light Turquoise"),
        StudyColorTheme(bg: "#76CD26", fg: "#FFFFFF", name: "Apple Green"),
        StudyColorTheme(bg: "#74A662", fg: "#FFFFFF", name: "Dull Green"),
        StudyColorTheme(bg: "#80013F", fg: "#FFFFFF", name: "Wine"),
        StudyColorTheme(bg: "#B1D1FC", fg: "#000000", name: "Powder Blue"),
        StudyColorTheme(bg: "#0652FF", fg: "#FFFFFF", name: "Electric Blue"),
        StudyColorTheme(bg: "#045C5A", fg: "#FFFFFF", name: "Dark Turquoise"),
        StudyColorTheme(bg: "#5729CE", fg: "#FFFFFF", name: "Blue Purple"),
        StudyColorTheme(bg: "#069AF3", fg: "#FFFFFF", name: "Azure"),
        StudyColorTheme(bg: "#FF000D", fg: "#FFFFFF", name: "Bright Red"),
        StudyColorTheme(bg: "#F10C45", fg: "#FFFFFF", name: "Pinkish Red"),
        StudyColorTheme(bg: "#5170D7", fg: "#FFFFFF", name: "Cornflower Blue"),
        StudyColorTheme(bg: "#ACBF69", fg: "#FFFFFF", name: "Light Olive"),
        StudyColorTheme(bg: "#6C3461", fg: "#FFFFFF", name: "Grape"),
        StudyColorTheme(bg: "#5E819D", fg: "#FFFFFF", name: "Greyish Blue"),
        StudyColorTheme(bg: "#601EF9", fg: "#FFFFFF", name: "Purplish Blue"),
        StudyColorTheme(bg: "#B0DD16", fg: "#FFFFFF", name: "Yellowish Green"),
        StudyColorTheme(bg: "#CDFD02", fg: "#000000", name: "Greenish Yellow"),
        StudyColorTheme(bg: "#2C6FBB", fg: "#FFFFFF", name: "Medium Blue"),
        StudyColorTheme(bg: "#C0737A", fg: "#FFFFFF", name: "Dusty Rose"),
        StudyColorTheme(bg: "#D6B4FC", fg: "#FFFFFF", name: "Light Violet"),
        StudyColorTheme(bg: "#703BE7", fg: "#FFFFFF", name: "Bluish Purple"),
        StudyColorTheme(bg: "#FD3C06", fg: "#FFFFFF", name: "Red Orange"),
        StudyColorTheme(bg: "#960056", fg: "#FFFFFF", name: "Dark Magenta"),
        StudyColorTheme(bg: "#40A368", fg: "#FFFFFF", name: "Greenish"),
        StudyColorTheme(bg: "#03719C", fg: "#FFFFFF", name: "Ocean Blue"),
        StudyColorTheme(bg: "#FC5A50", fg: "#FFFFFF", name: "Coral"),
        StudyColorTheme(bg: "#7F2B0A", fg: "#FFFFFF", name: "Reddish Brown"),
        StudyColorTheme(bg: "#B04E0F", fg: "#FFFFFF", name: "Burnt Sienna"),
        StudyColorTheme(bg: "#A03623", fg: "#FFFFFF", name: "Brick"),
        StudyColorTheme(bg: "#87AE73", fg: "#FFFFFF", name: "Sage"),
        StudyColorTheme(bg: "#789B73", fg: "#FFFFFF", name: "Grey Green"),
        StudyColorTheme(bg: "#98EFF9", fg: "#000000", name: "robins Egg Blue"),
        StudyColorTheme(bg: "#658B38", fg: "#FFFFFF", name: "Moss Green"),
        StudyColorTheme(bg: "#5A7D9A", fg: "#FFFFFF", name: "Steel Blue"),
        StudyColorTheme(bg: "#380835", fg: "#FFFFFF", name: "Eggplant"),
        StudyColorTheme(bg: "#FFFE7A", fg: "#000000", name: "Light Yellow"),
        StudyColorTheme(bg: "#5CA904", fg: "#FFFFFF", name: "Leaf Green"),
        StudyColorTheme(bg: "#D8DCD6", fg: "#000000", name: "Light Grey"),
        StudyColorTheme(bg: "#A5A502", fg: "#FFFFFF", name: "Puke"),
        StudyColorTheme(bg: "#D648D7", fg: "#FFFFFF", name: "Pinkish Purple"),
        StudyColorTheme(bg: "#047495", fg: "#FFFFFF", name: "Sea Blue"),
        StudyColorTheme(bg: "#B790D4", fg: "#FFFFFF", name: "Pale Purple"),
        StudyColorTheme(bg: "#5B7C99", fg: "#FFFFFF", name: "Slate Blue"),
        StudyColorTheme(bg: "#607C8E", fg: "#FFFFFF", name: "Blue Grey"),
        StudyColorTheme(bg: "#0B4008", fg: "#FFFFFF", name: "Hunter Green"),
        StudyColorTheme(bg: "#ED0DD9", fg: "#FFFFFF", name: "Fuchsia"),
        StudyColorTheme(bg: "#8C000F", fg: "#FFFFFF", name: "Crimson"),
        StudyColorTheme(bg: "#FFFF84", fg: "#000000", name: "Pale Yellow"),
        StudyColorTheme(bg: "#BF9005", fg: "#FFFFFF", name: "Ochre"),
        StudyColorTheme(bg: "#D2BD0A", fg: "#FFFFFF", name: "Mustard Yellow"),
        StudyColorTheme(bg: "#FF474C", fg: "#FFFFFF", name: "Light Red"),
        StudyColorTheme(bg: "#0485D1", fg: "#FFFFFF", name: "Cerulean"),
        StudyColorTheme(bg: "#FFCFDC", fg: "#000000", name: "Pale Pink"),
        StudyColorTheme(bg: "#040273", fg: "#FFFFFF", name: "Deep Blue"),
        StudyColorTheme(bg: "#A83C09", fg: "#FFFFFF", name: "Rust"),
        StudyColorTheme(bg: "#90E4C1", fg: "#FFFFFF", name: "Light Teal"),
        StudyColorTheme(bg: "#516572", fg: "#FFFFFF", name: "Slate"),
        StudyColorTheme(bg: "#FAC205", fg: "#FFFFFF", name: "Goldenrod"),
        StudyColorTheme(bg: "#D5B60A", fg: "#FFFFFF", name: "Dark Yellow"),
        StudyColorTheme(bg: "#363737", fg: "#FFFFFF", name: "Dark Grey"),
        StudyColorTheme(bg: "#4B5D16", fg: "#FFFFFF", name: "Army Green"),
        StudyColorTheme(bg: "#6B8BA4", fg: "#FFFFFF", name: "Grey Blue"),
        StudyColorTheme(bg: "#80F9AD", fg: "#000000", name: "Seafoam"),
        StudyColorTheme(bg: "#A57E52", fg: "#FFFFFF", name: "Puce"),
        StudyColorTheme(bg: "#A9F971", fg: "#000000", name: "Spring Green"),
        StudyColorTheme(bg: "#C65102", fg: "#FFFFFF", name: "Dark Orange"),
        StudyColorTheme(bg: "#E2CA76", fg: "#FFFFFF", name: "Sand"),
        StudyColorTheme(bg: "#B0FF9D", fg: "#000000", name: "Pastel Green"),
        StudyColorTheme(bg: "#9FFEB0", fg: "#000000", name: "Mint"),
        StudyColorTheme(bg: "#FDAA48", fg: "#FFFFFF", name: "Light Orange"),
        StudyColorTheme(bg: "#FE01B1", fg: "#FFFFFF", name: "Bright Pink"),
        StudyColorTheme(bg: "#C1F80A", fg: "#000000", name: "Chartreuse"),
        StudyColorTheme(bg: "#36013F", fg: "#FFFFFF", name: "Deep Purple"),
        StudyColorTheme(bg: "#341C02", fg: "#FFFFFF", name: "Dark Brown"),
        StudyColorTheme(bg: "#B9A281", fg: "#FFFFFF", name: "Taupe"),
        StudyColorTheme(bg: "#8EAB12", fg: "#FFFFFF", name: "Pea Green"),
        StudyColorTheme(bg: "#9AAE07", fg: "#FFFFFF", name: "Puke Green"),
        StudyColorTheme(bg: "#02AB2E", fg: "#FFFFFF", name: "Kelly Green"),
        StudyColorTheme(bg: "#7AF9AB", fg: "#000000", name: "Seafoam Green"),
        StudyColorTheme(bg: "#137E6D", fg: "#FFFFFF", name: "Blue Green"),
        StudyColorTheme(bg: "#AAA662", fg: "#FFFFFF", name: "Khaki"),
        StudyColorTheme(bg: "#610023", fg: "#FFFFFF", name: "Burgundy"),
        StudyColorTheme(bg: "#014D4E", fg: "#FFFFFF", name: "Dark Teal"),
        StudyColorTheme(bg: "#8F1402", fg: "#FFFFFF", name: "Brick Red"),
        StudyColorTheme(bg: "#4B006E", fg: "#FFFFFF", name: "Royal Purple"),
        StudyColorTheme(bg: "#580F41", fg: "#FFFFFF", name: "Plum"),
        StudyColorTheme(bg: "#8FFF9F", fg: "#000000", name: "Mint Green"),
        StudyColorTheme(bg: "#DBB40C", fg: "#FFFFFF", name: "Gold"),
        StudyColorTheme(bg: "#A2CFFE", fg: "#FFFFFF", name: "Baby Blue"),
        StudyColorTheme(bg: "#C0FB2D", fg: "#000000", name: "Yellow Green"),
        StudyColorTheme(bg: "#BE03FD", fg: "#FFFFFF", name: "Bright Purple"),
        StudyColorTheme(bg: "#840000", fg: "#FFFFFF", name: "Dark Red"),
        StudyColorTheme(bg: "#D0FEFE", fg: "#000000", name: "Pale Blue"),
        StudyColorTheme(bg: "#3F9B0B", fg: "#FFFFFF", name: "Grass Green"),
        StudyColorTheme(bg: "#01153E", fg: "#FFFFFF", name: "Navy"),
        StudyColorTheme(bg: "#04D8B2", fg: "#FFFFFF", name: "Aquamarine"),
        StudyColorTheme(bg: "#C04E01", fg: "#FFFFFF", name: "Burnt Orange"),
        StudyColorTheme(bg: "#0CFF0C", fg: "#FFFFFF", name: "Neon Green"),
        StudyColorTheme(bg: "#0165FC", fg: "#FFFFFF", name: "Bright Blue"),
        StudyColorTheme(bg: "#CF6275", fg: "#FFFFFF", name: "Rose"),
        StudyColorTheme(bg: "#FFD1DF", fg: "#000000", name: "Light Pink"),
        StudyColorTheme(bg: "#CEB301", fg: "#FFFFFF", name: "Mustard"),
        StudyColorTheme(bg: "#380282", fg: "#FFFFFF", name: "Indigo"),
        StudyColorTheme(bg: "#AAFF32", fg: "#000000", name: "Lime"),
        StudyColorTheme(bg: "#53FCA1", fg: "#FFFFFF", name: "Sea Green"),
        StudyColorTheme(bg: "#8E82FE", fg: "#FFFFFF", name: "Periwinkle"),
        StudyColorTheme(bg: "#CB416B", fg: "#FFFFFF", name: "Dark Pink"),
        StudyColorTheme(bg: "#677A04", fg: "#FFFFFF", name: "Olive Green"),
        StudyColorTheme(bg: "#FFB07C", fg: "#FFFFFF", name: "Peach"),
        StudyColorTheme(bg: "#C7FDB5", fg: "#000000", name: "Pale Green"),
        StudyColorTheme(bg: "#AD8150", fg: "#FFFFFF", name: "Light Brown"),
        StudyColorTheme(bg: "#CEA2FD", fg: "#FFFFFF", name: "Lilac"),
        StudyColorTheme(bg: "#001146", fg: "#FFFFFF", name: "Navy Blue"),
        StudyColorTheme(bg: "#0504AA", fg: "#FFFFFF", name: "Royal Blue"),
        StudyColorTheme(bg: "#E6DAA6", fg: "#000000", name: "Beige"),
        StudyColorTheme(bg: "#FF796C", fg: "#FFFFFF", name: "Salmon"),
        StudyColorTheme(bg: "#6E750E", fg: "#FFFFFF", name: "Olive"),
        StudyColorTheme(bg: "#650021", fg: "#FFFFFF", name: "Maroon"),
        StudyColorTheme(bg: "#01FF07", fg: "#FFFFFF", name: "Bright Green"),
        StudyColorTheme(bg: "#35063E", fg: "#FFFFFF", name: "Dark Purple"),
        StudyColorTheme(bg: "#AE7181", fg: "#FFFFFF", name: "Mauve"),
        StudyColorTheme(bg: "#06470C", fg: "#FFFFFF", name: "Forest Green"),
        StudyColorTheme(bg: "#13EAC9", fg: "#FFFFFF", name: "Aqua"),
        StudyColorTheme(bg: "#D1B26F", fg: "#FFFFFF", name: "Tan"),
        StudyColorTheme(bg: "#00035B", fg: "#FFFFFF", name: "Dark Blue"),
        StudyColorTheme(bg: "#C79FEF", fg: "#FFFFFF", name: "Lavender"),
        StudyColorTheme(bg: "#06C2AC", fg: "#FFFFFF", name: "Turquoise"),
        StudyColorTheme(bg: "#033500", fg: "#FFFFFF", name: "Dark Green"),
        StudyColorTheme(bg: "#9A0EEA", fg: "#FFFFFF", name: "Violet"),
        StudyColorTheme(bg: "#BF77F6", fg: "#FFFFFF", name: "Light Purple"),
        StudyColorTheme(bg: "#89FE05", fg: "#FFFFFF", name: "Lime Green"),
        StudyColorTheme(bg: "#929591", fg: "#FFFFFF", name: "Grey"),
        StudyColorTheme(bg: "#75BBFD", fg: "#FFFFFF", name: "Sky Blue"),
        StudyColorTheme(bg: "#FFFF14", fg: "#000000", name: "Yellow"),
        StudyColorTheme(bg: "#C20078", fg: "#FFFFFF", name: "Magenta"),
        StudyColorTheme(bg: "#96F97B", fg: "#000000", name: "Light Green"),
        StudyColorTheme(bg: "#F97306", fg: "#FFFFFF", name: "Orange"),
        StudyColorTheme(bg: "#029386", fg: "#FFFFFF", name: "Teal"),
        StudyColorTheme(bg: "#95D0FC", fg: "#FFFFFF", name: "Light Blue"),
        StudyColorTheme(bg: "#E50000", fg: "#FFFFFF", name: "Red"),
        StudyColorTheme(bg: "#653700", fg: "#FFFFFF", name: "Brown"),
        StudyColorTheme(bg: "#FF81C0", fg: "#FFFFFF", name: "Pink"),
        StudyColorTheme(bg: "#0343DF", fg: "#FFFFFF", name: "Blue"),
        StudyColorTheme(bg: "#15B01A", fg: "#FFFFFF", name: "Green"),
        StudyColorTheme(bg: "#7E1E9C", fg: "#FFFFFF", name: "Purple"),
    ]
}
