import SwiftUI

// MARK: - XKCD Color Themes
// 916 vibrant colors from the XKCD color survey
// https://xkcd.com/color/rgb/

struct ColorTheme {
    let bg: String
    let fg: String
    let name: String
    
    var background: Color { Color(hex: bg) }
    var foreground: Color { Color(hex: fg) }
}

struct XKCDColors {
    static let all: [ColorTheme] = [
            ColorTheme(bg: "#ACC2D9", fg: "#FFFFFF", name: "Cloudy Blue"),
            ColorTheme(bg: "#56AE57", fg: "#FFFFFF", name: "Dark Pastel Green"),
            ColorTheme(bg: "#B2996E", fg: "#FFFFFF", name: "Dust"),
            ColorTheme(bg: "#A8FF04", fg: "#000000", name: "Electric Lime"),
            ColorTheme(bg: "#69D84F", fg: "#FFFFFF", name: "Fresh Green"),
            ColorTheme(bg: "#894585", fg: "#FFFFFF", name: "Light Eggplant"),
            ColorTheme(bg: "#70B23F", fg: "#FFFFFF", name: "Nasty Green"),
            ColorTheme(bg: "#D4FFFF", fg: "#000000", name: "Really Light Blue"),
            ColorTheme(bg: "#65AB7C", fg: "#FFFFFF", name: "Tea"),
            ColorTheme(bg: "#952E8F", fg: "#FFFFFF", name: "Warm Purple"),
            ColorTheme(bg: "#FCFC81", fg: "#000000", name: "Yellowish Tan"),
            ColorTheme(bg: "#A5A391", fg: "#FFFFFF", name: "Cement"),
            ColorTheme(bg: "#388004", fg: "#FFFFFF", name: "Dark Grass Green"),
            ColorTheme(bg: "#4C9085", fg: "#FFFFFF", name: "Dusty Teal"),
            ColorTheme(bg: "#5E9B8A", fg: "#FFFFFF", name: "Grey Teal"),
            ColorTheme(bg: "#EFB435", fg: "#FFFFFF", name: "Macaroni And Cheese"),
            ColorTheme(bg: "#D99B82", fg: "#FFFFFF", name: "Pinkish Tan"),
            ColorTheme(bg: "#0A5F38", fg: "#FFFFFF", name: "Spruce"),
            ColorTheme(bg: "#0C06F7", fg: "#FFFFFF", name: "Strong Blue"),
            ColorTheme(bg: "#61DE2A", fg: "#FFFFFF", name: "Toxic Green"),
            ColorTheme(bg: "#3778BF", fg: "#FFFFFF", name: "Windows Blue"),
            ColorTheme(bg: "#2242C7", fg: "#FFFFFF", name: "Blue Blue"),
            ColorTheme(bg: "#533CC6", fg: "#FFFFFF", name: "Blue With A Hint Of Purple"),
            ColorTheme(bg: "#9BB53C", fg: "#FFFFFF", name: "Booger"),
            ColorTheme(bg: "#05FFA6", fg: "#FFFFFF", name: "Bright Sea Green"),
            ColorTheme(bg: "#1F6357", fg: "#FFFFFF", name: "Dark Green Blue"),
            ColorTheme(bg: "#017374", fg: "#FFFFFF", name: "Deep Turquoise"),
            ColorTheme(bg: "#0CB577", fg: "#FFFFFF", name: "Green Teal"),
            ColorTheme(bg: "#FF0789", fg: "#FFFFFF", name: "Strong Pink"),
            ColorTheme(bg: "#AFA88B", fg: "#FFFFFF", name: "Bland"),
            ColorTheme(bg: "#08787F", fg: "#FFFFFF", name: "Deep Aqua"),
            ColorTheme(bg: "#DD85D7", fg: "#FFFFFF", name: "Lavender Pink"),
            ColorTheme(bg: "#A6C875", fg: "#FFFFFF", name: "Light Moss Green"),
            ColorTheme(bg: "#A7FFB5", fg: "#000000", name: "Light Seafoam Green"),
            ColorTheme(bg: "#C2B709", fg: "#FFFFFF", name: "Olive Yellow"),
            ColorTheme(bg: "#E78EA5", fg: "#FFFFFF", name: "Pig Pink"),
            ColorTheme(bg: "#966EBD", fg: "#FFFFFF", name: "Deep Lilac"),
            ColorTheme(bg: "#CCAD60", fg: "#FFFFFF", name: "Desert"),
            ColorTheme(bg: "#AC86A8", fg: "#FFFFFF", name: "Dusty Lavender"),
            ColorTheme(bg: "#947E94", fg: "#FFFFFF", name: "Purpley Grey"),
            ColorTheme(bg: "#983FB2", fg: "#FFFFFF", name: "Purply"),
            ColorTheme(bg: "#FF63E9", fg: "#FFFFFF", name: "Candy Pink"),
            ColorTheme(bg: "#B2FBA5", fg: "#000000", name: "Light Pastel Green"),
            ColorTheme(bg: "#63B365", fg: "#FFFFFF", name: "Boring Green"),
            ColorTheme(bg: "#B7E1A1", fg: "#000000", name: "Light Grey Green"),
            ColorTheme(bg: "#FF6F52", fg: "#FFFFFF", name: "Orange Pink"),
            ColorTheme(bg: "#BDF8A3", fg: "#000000", name: "Tea Green"),
            ColorTheme(bg: "#D3B683", fg: "#FFFFFF", name: "Very Light Brown"),
            ColorTheme(bg: "#430541", fg: "#FFFFFF", name: "Eggplant Purple"),
            ColorTheme(bg: "#FFB2D0", fg: "#000000", name: "Powder Pink"),
            ColorTheme(bg: "#997570", fg: "#FFFFFF", name: "Reddish Grey"),
            ColorTheme(bg: "#AD900D", fg: "#FFFFFF", name: "Baby Shit Brown"),
            ColorTheme(bg: "#C48EFD", fg: "#FFFFFF", name: "Liliac"),
            ColorTheme(bg: "#507B9C", fg: "#FFFFFF", name: "Stormy Blue"),
            ColorTheme(bg: "#7D7103", fg: "#FFFFFF", name: "Ugly Brown"),
            ColorTheme(bg: "#FFFD78", fg: "#000000", name: "Custard"),
            ColorTheme(bg: "#DA467D", fg: "#FFFFFF", name: "Darkish Pink"),
            ColorTheme(bg: "#410200", fg: "#FFFFFF", name: "Deep Brown"),
            ColorTheme(bg: "#C9D179", fg: "#FFFFFF", name: "Greenish Beige"),
            ColorTheme(bg: "#FFFA86", fg: "#000000", name: "Manilla"),
            ColorTheme(bg: "#5684AE", fg: "#FFFFFF", name: "Off Blue"),
            ColorTheme(bg: "#6B7C85", fg: "#FFFFFF", name: "Battleship Grey"),
            ColorTheme(bg: "#6F6C0A", fg: "#FFFFFF", name: "Browny Green"),
            ColorTheme(bg: "#7E4071", fg: "#FFFFFF", name: "Bruise"),
            ColorTheme(bg: "#009337", fg: "#FFFFFF", name: "Kelley Green"),
            ColorTheme(bg: "#D0E429", fg: "#000000", name: "Sickly Yellow"),
            ColorTheme(bg: "#FFF917", fg: "#000000", name: "Sunny Yellow"),
            ColorTheme(bg: "#1D5DEC", fg: "#FFFFFF", name: "Azul"),
            ColorTheme(bg: "#054907", fg: "#FFFFFF", name: "Darkgreen"),
            ColorTheme(bg: "#B5CE08", fg: "#FFFFFF", name: "Green/Yellow"),
            ColorTheme(bg: "#8FB67B", fg: "#FFFFFF", name: "Lichen"),
            ColorTheme(bg: "#C8FFB0", fg: "#000000", name: "Light Light Green"),
            ColorTheme(bg: "#FDDE6C", fg: "#000000", name: "Pale Gold"),
            ColorTheme(bg: "#FFDF22", fg: "#000000", name: "Sun Yellow"),
            ColorTheme(bg: "#A9BE70", fg: "#FFFFFF", name: "Tan Green"),
            ColorTheme(bg: "#6832E3", fg: "#FFFFFF", name: "Burple"),
            ColorTheme(bg: "#FDB147", fg: "#FFFFFF", name: "Butterscotch"),
            ColorTheme(bg: "#C7AC7D", fg: "#FFFFFF", name: "Toupe"),
            ColorTheme(bg: "#FFF39A", fg: "#000000", name: "Dark Cream"),
            ColorTheme(bg: "#850E04", fg: "#FFFFFF", name: "Indian Red"),
            ColorTheme(bg: "#EFC0FE", fg: "#000000", name: "Light Lavendar"),
            ColorTheme(bg: "#B6C406", fg: "#FFFFFF", name: "Baby Puke Green"),
            ColorTheme(bg: "#3C4142", fg: "#FFFFFF", name: "Charcoal Grey"),
            ColorTheme(bg: "#F2AB15", fg: "#FFFFFF", name: "Squash"),
            ColorTheme(bg: "#AC4F06", fg: "#FFFFFF", name: "Cinnamon"),
            ColorTheme(bg: "#C4FE82", fg: "#000000", name: "Light Pea Green"),
            ColorTheme(bg: "#2CFA1F", fg: "#FFFFFF", name: "Radioactive Green"),
            ColorTheme(bg: "#9A6200", fg: "#FFFFFF", name: "Raw Sienna"),
            ColorTheme(bg: "#CA9BF7", fg: "#FFFFFF", name: "Baby Purple"),
            ColorTheme(bg: "#875F42", fg: "#FFFFFF", name: "Cocoa"),
            ColorTheme(bg: "#3A2EFE", fg: "#FFFFFF", name: "Light Royal Blue"),
            ColorTheme(bg: "#FD8D49", fg: "#FFFFFF", name: "Orangeish"),
            ColorTheme(bg: "#8B3103", fg: "#FFFFFF", name: "Rust Brown"),
            ColorTheme(bg: "#CBA560", fg: "#FFFFFF", name: "Sand Brown"),
            ColorTheme(bg: "#698339", fg: "#FFFFFF", name: "Swamp"),
            ColorTheme(bg: "#0CDC73", fg: "#FFFFFF", name: "Tealish Green"),
            ColorTheme(bg: "#B75203", fg: "#FFFFFF", name: "Burnt Siena"),
            ColorTheme(bg: "#7F8F4E", fg: "#FFFFFF", name: "Camo"),
            ColorTheme(bg: "#26538D", fg: "#FFFFFF", name: "Dusk Blue"),
            ColorTheme(bg: "#63A950", fg: "#FFFFFF", name: "Fern"),
            ColorTheme(bg: "#C87F89", fg: "#FFFFFF", name: "Old Rose"),
            ColorTheme(bg: "#B1FC99", fg: "#000000", name: "Pale Light Green"),
            ColorTheme(bg: "#FF9A8A", fg: "#FFFFFF", name: "Peachy Pink"),
            ColorTheme(bg: "#F6688E", fg: "#FFFFFF", name: "Rosy Pink"),
            ColorTheme(bg: "#76FDA8", fg: "#000000", name: "Light Bluish Green"),
            ColorTheme(bg: "#53FE5C", fg: "#FFFFFF", name: "Light Bright Green"),
            ColorTheme(bg: "#4EFD54", fg: "#FFFFFF", name: "Light Neon Green"),
            ColorTheme(bg: "#A0FEBF", fg: "#000000", name: "Light Seafoam"),
            ColorTheme(bg: "#7BF2DA", fg: "#000000", name: "Tiffany Blue"),
            ColorTheme(bg: "#BCF5A6", fg: "#000000", name: "Washed Out Green"),
            ColorTheme(bg: "#CA6B02", fg: "#FFFFFF", name: "Browny Orange"),
            ColorTheme(bg: "#107AB0", fg: "#FFFFFF", name: "Nice Blue"),
            ColorTheme(bg: "#2138AB", fg: "#FFFFFF", name: "Sapphire"),
            ColorTheme(bg: "#719F91", fg: "#FFFFFF", name: "Greyish Teal"),
            ColorTheme(bg: "#FDB915", fg: "#FFFFFF", name: "Orangey Yellow"),
            ColorTheme(bg: "#FEFCAF", fg: "#000000", name: "Parchment"),
            ColorTheme(bg: "#FCF679", fg: "#000000", name: "Straw"),
            ColorTheme(bg: "#CB6843", fg: "#FFFFFF", name: "Terracota"),
            ColorTheme(bg: "#31668A", fg: "#FFFFFF", name: "Ugly Blue"),
            ColorTheme(bg: "#247AFD", fg: "#FFFFFF", name: "Clear Blue"),
            ColorTheme(bg: "#90FDA9", fg: "#000000", name: "Foam Green"),
            ColorTheme(bg: "#86A17D", fg: "#FFFFFF", name: "Grey/Green"),
            ColorTheme(bg: "#FDDC5C", fg: "#000000", name: "Light Gold"),
            ColorTheme(bg: "#78D1B6", fg: "#FFFFFF", name: "Seafoam Blue"),
            ColorTheme(bg: "#13BBAF", fg: "#FFFFFF", name: "Topaz"),
            ColorTheme(bg: "#FB5FFC", fg: "#FFFFFF", name: "Violet Pink"),
            ColorTheme(bg: "#20F986", fg: "#FFFFFF", name: "Wintergreen"),
            ColorTheme(bg: "#FFE36E", fg: "#000000", name: "Yellow Tan"),
            ColorTheme(bg: "#9D0759", fg: "#FFFFFF", name: "Dark Fuchsia"),
            ColorTheme(bg: "#3A18B1", fg: "#FFFFFF", name: "Indigo Blue"),
            ColorTheme(bg: "#C2FF89", fg: "#000000", name: "Light Yellowish Green"),
            ColorTheme(bg: "#D767AD", fg: "#FFFFFF", name: "Pale Magenta"),
            ColorTheme(bg: "#720058", fg: "#FFFFFF", name: "Rich Purple"),
            ColorTheme(bg: "#FFDA03", fg: "#000000", name: "Sunflower Yellow"),
            ColorTheme(bg: "#01C08D", fg: "#FFFFFF", name: "Green/Blue"),
            ColorTheme(bg: "#AC7434", fg: "#FFFFFF", name: "Leather"),
            ColorTheme(bg: "#014600", fg: "#FFFFFF", name: "Racing Green"),
            ColorTheme(bg: "#9900FA", fg: "#FFFFFF", name: "Vivid Purple"),
            ColorTheme(bg: "#02066F", fg: "#FFFFFF", name: "Dark Royal Blue"),
            ColorTheme(bg: "#8E7618", fg: "#FFFFFF", name: "Hazel"),
            ColorTheme(bg: "#D1768F", fg: "#FFFFFF", name: "Muted Pink"),
            ColorTheme(bg: "#96B403", fg: "#FFFFFF", name: "Booger Green"),
            ColorTheme(bg: "#FDFF63", fg: "#000000", name: "Canary"),
            ColorTheme(bg: "#95A3A6", fg: "#FFFFFF", name: "Cool Grey"),
            ColorTheme(bg: "#7F684E", fg: "#FFFFFF", name: "Dark Taupe"),
            ColorTheme(bg: "#751973", fg: "#FFFFFF", name: "Darkish Purple"),
            ColorTheme(bg: "#089404", fg: "#FFFFFF", name: "True Green"),
            ColorTheme(bg: "#FF6163", fg: "#FFFFFF", name: "Coral Pink"),
            ColorTheme(bg: "#598556", fg: "#FFFFFF", name: "Dark Sage"),
            ColorTheme(bg: "#214761", fg: "#FFFFFF", name: "Dark Slate Blue"),
            ColorTheme(bg: "#3C73A8", fg: "#FFFFFF", name: "Flat Blue"),
            ColorTheme(bg: "#BA9E88", fg: "#FFFFFF", name: "Mushroom"),
            ColorTheme(bg: "#021BF9", fg: "#FFFFFF", name: "Rich Blue"),
            ColorTheme(bg: "#734A65", fg: "#FFFFFF", name: "Dirty Purple"),
            ColorTheme(bg: "#23C48B", fg: "#FFFFFF", name: "Greenblue"),
            ColorTheme(bg: "#8FAE22", fg: "#FFFFFF", name: "Icky Green"),
            ColorTheme(bg: "#E6F2A2", fg: "#000000", name: "Light Khaki"),
            ColorTheme(bg: "#4B57DB", fg: "#FFFFFF", name: "Warm Blue"),
            ColorTheme(bg: "#D90166", fg: "#FFFFFF", name: "Dark Hot Pink"),
            ColorTheme(bg: "#015482", fg: "#FFFFFF", name: "Deep Sea Blue"),
            ColorTheme(bg: "#9D0216", fg: "#FFFFFF", name: "Carmine"),
            ColorTheme(bg: "#728F02", fg: "#FFFFFF", name: "Dark Yellow Green"),
            ColorTheme(bg: "#FFE5AD", fg: "#000000", name: "Pale Peach"),
            ColorTheme(bg: "#4E0550", fg: "#FFFFFF", name: "Plum Purple"),
            ColorTheme(bg: "#F9BC08", fg: "#FFFFFF", name: "Golden Rod"),
            ColorTheme(bg: "#FF073A", fg: "#FFFFFF", name: "Neon Red"),
            ColorTheme(bg: "#C77986", fg: "#FFFFFF", name: "Old Pink"),
            ColorTheme(bg: "#D6FFFE", fg: "#000000", name: "Very Pale Blue"),
            ColorTheme(bg: "#FE4B03", fg: "#FFFFFF", name: "Blood Orange"),
            ColorTheme(bg: "#FD5956", fg: "#FFFFFF", name: "Grapefruit"),
            ColorTheme(bg: "#FCE166", fg: "#000000", name: "Sand Yellow"),
            ColorTheme(bg: "#B2713D", fg: "#FFFFFF", name: "Clay Brown"),
            ColorTheme(bg: "#1F3B4D", fg: "#FFFFFF", name: "Dark Blue Grey"),
            ColorTheme(bg: "#699D4C", fg: "#FFFFFF", name: "Flat Green"),
            ColorTheme(bg: "#56FCA2", fg: "#FFFFFF", name: "Light Green Blue"),
            ColorTheme(bg: "#FB5581", fg: "#FFFFFF", name: "Warm Pink"),
            ColorTheme(bg: "#3E82FC", fg: "#FFFFFF", name: "Dodger Blue"),
            ColorTheme(bg: "#A0BF16", fg: "#FFFFFF", name: "Gross Green"),
            ColorTheme(bg: "#D6FFFA", fg: "#000000", name: "Ice"),
            ColorTheme(bg: "#4F738E", fg: "#FFFFFF", name: "Metallic Blue"),
            ColorTheme(bg: "#FFB19A", fg: "#FFFFFF", name: "Pale Salmon"),
            ColorTheme(bg: "#5C8B15", fg: "#FFFFFF", name: "Sap Green"),
            ColorTheme(bg: "#54AC68", fg: "#FFFFFF", name: "Algae"),
            ColorTheme(bg: "#89A0B0", fg: "#FFFFFF", name: "Bluey Grey"),
            ColorTheme(bg: "#7EA07A", fg: "#FFFFFF", name: "Greeny Grey"),
            ColorTheme(bg: "#1BFC06", fg: "#FFFFFF", name: "Highlighter Green"),
            ColorTheme(bg: "#CAFFFB", fg: "#000000", name: "Light Light Blue"),
            ColorTheme(bg: "#B6FFBB", fg: "#000000", name: "Light Mint"),
            ColorTheme(bg: "#A75E09", fg: "#FFFFFF", name: "Raw Umber"),
            ColorTheme(bg: "#152EFF", fg: "#FFFFFF", name: "Vivid Blue"),
            ColorTheme(bg: "#8D5EB7", fg: "#FFFFFF", name: "Deep Lavender"),
            ColorTheme(bg: "#5F9E8F", fg: "#FFFFFF", name: "Dull Teal"),
            ColorTheme(bg: "#606602", fg: "#FFFFFF", name: "Mud Green"),
            ColorTheme(bg: "#FC86AA", fg: "#FFFFFF", name: "Pinky"),
            ColorTheme(bg: "#8C0034", fg: "#FFFFFF", name: "Red Wine"),
            ColorTheme(bg: "#758000", fg: "#FFFFFF", name: "Shit Green"),
            ColorTheme(bg: "#AB7E4C", fg: "#FFFFFF", name: "Tan Brown"),
            ColorTheme(bg: "#030764", fg: "#FFFFFF", name: "Darkblue"),
            ColorTheme(bg: "#FE86A4", fg: "#FFFFFF", name: "Rosa"),
            ColorTheme(bg: "#D5174E", fg: "#FFFFFF", name: "Lipstick"),
            ColorTheme(bg: "#FED0FC", fg: "#000000", name: "Pale Mauve"),
            ColorTheme(bg: "#680018", fg: "#FFFFFF", name: "Claret"),
            ColorTheme(bg: "#FEDF08", fg: "#000000", name: "Dandelion"),
            ColorTheme(bg: "#FE420F", fg: "#FFFFFF", name: "Orangered"),
            ColorTheme(bg: "#6F7C00", fg: "#FFFFFF", name: "Poop Green"),
            ColorTheme(bg: "#CA0147", fg: "#FFFFFF", name: "Ruby"),
            ColorTheme(bg: "#1B2431", fg: "#FFFFFF", name: "Dark"),
            ColorTheme(bg: "#DB5856", fg: "#FFFFFF", name: "Pastel Red"),
            ColorTheme(bg: "#DDD618", fg: "#FFFFFF", name: "Piss Yellow"),
            ColorTheme(bg: "#CF524E", fg: "#FFFFFF", name: "Dark Coral"),
            ColorTheme(bg: "#21C36F", fg: "#FFFFFF", name: "Algae Green"),
            ColorTheme(bg: "#A90308", fg: "#FFFFFF", name: "Darkish Red"),
            ColorTheme(bg: "#6E1005", fg: "#FFFFFF", name: "Reddy Brown"),
            ColorTheme(bg: "#FE828C", fg: "#FFFFFF", name: "Blush Pink"),
            ColorTheme(bg: "#4B6113", fg: "#FFFFFF", name: "Camouflage Green"),
            ColorTheme(bg: "#4DA409", fg: "#FFFFFF", name: "Lawn Green"),
            ColorTheme(bg: "#BEAE8A", fg: "#FFFFFF", name: "Putty"),
            ColorTheme(bg: "#0339F8", fg: "#FFFFFF", name: "Vibrant Blue"),
            ColorTheme(bg: "#A88F59", fg: "#FFFFFF", name: "Dark Sand"),
            ColorTheme(bg: "#5D21D0", fg: "#FFFFFF", name: "Purple/Blue"),
            ColorTheme(bg: "#FEB209", fg: "#FFFFFF", name: "Saffron"),
            ColorTheme(bg: "#4E518B", fg: "#FFFFFF", name: "Twilight"),
            ColorTheme(bg: "#964E02", fg: "#FFFFFF", name: "Warm Brown"),
            ColorTheme(bg: "#85A3B2", fg: "#FFFFFF", name: "Bluegrey"),
            ColorTheme(bg: "#FF69AF", fg: "#FFFFFF", name: "Bubble Gum Pink"),
            ColorTheme(bg: "#C3FBF4", fg: "#000000", name: "Duck Egg Blue"),
            ColorTheme(bg: "#2AFEB7", fg: "#FFFFFF", name: "Greenish Cyan"),
            ColorTheme(bg: "#005F6A", fg: "#FFFFFF", name: "Petrol"),
            ColorTheme(bg: "#0C1793", fg: "#FFFFFF", name: "Royal"),
            ColorTheme(bg: "#FFFF81", fg: "#000000", name: "Butter"),
            ColorTheme(bg: "#F0833A", fg: "#FFFFFF", name: "Dusty Orange"),
            ColorTheme(bg: "#F1F33F", fg: "#000000", name: "Off Yellow"),
            ColorTheme(bg: "#B1D27B", fg: "#FFFFFF", name: "Pale Olive Green"),
            ColorTheme(bg: "#FC824A", fg: "#FFFFFF", name: "Orangish"),
            ColorTheme(bg: "#71AA34", fg: "#FFFFFF", name: "Leaf"),
            ColorTheme(bg: "#B7C9E2", fg: "#FFFFFF", name: "Light Blue Grey"),
            ColorTheme(bg: "#4B0101", fg: "#FFFFFF", name: "Dried Blood"),
            ColorTheme(bg: "#A552E6", fg: "#FFFFFF", name: "Lightish Purple"),
            ColorTheme(bg: "#AF2F0D", fg: "#FFFFFF", name: "Rusty Red"),
            ColorTheme(bg: "#8B88F8", fg: "#FFFFFF", name: "Lavender Blue"),
            ColorTheme(bg: "#9AF764", fg: "#000000", name: "Light Grass Green"),
            ColorTheme(bg: "#A6FBB2", fg: "#000000", name: "Light Mint Green"),
            ColorTheme(bg: "#FFC512", fg: "#FFFFFF", name: "Sunflower"),
            ColorTheme(bg: "#750851", fg: "#FFFFFF", name: "Velvet"),
            ColorTheme(bg: "#C14A09", fg: "#FFFFFF", name: "Brick Orange"),
            ColorTheme(bg: "#FE2F4A", fg: "#FFFFFF", name: "Lightish Red"),
            ColorTheme(bg: "#0203E2", fg: "#FFFFFF", name: "Pure Blue"),
            ColorTheme(bg: "#0A437A", fg: "#FFFFFF", name: "Twilight Blue"),
            ColorTheme(bg: "#A50055", fg: "#FFFFFF", name: "Violet Red"),
            ColorTheme(bg: "#AE8B0C", fg: "#FFFFFF", name: "Yellowy Brown"),
            ColorTheme(bg: "#FD798F", fg: "#FFFFFF", name: "Carnation"),
            ColorTheme(bg: "#BFAC05", fg: "#FFFFFF", name: "Muddy Yellow"),
            ColorTheme(bg: "#3EAF76", fg: "#FFFFFF", name: "Dark Seafoam Green"),
            ColorTheme(bg: "#C74767", fg: "#FFFFFF", name: "Deep Rose"),
            ColorTheme(bg: "#B9484E", fg: "#FFFFFF", name: "Dusty Red"),
            ColorTheme(bg: "#647D8E", fg: "#FFFFFF", name: "Grey/Blue"),
            ColorTheme(bg: "#BFFE28", fg: "#000000", name: "Lemon Lime"),
            ColorTheme(bg: "#D725DE", fg: "#FFFFFF", name: "Purple/Pink"),
            ColorTheme(bg: "#B29705", fg: "#FFFFFF", name: "Brown Yellow"),
            ColorTheme(bg: "#673A3F", fg: "#FFFFFF", name: "Purple Brown"),
            ColorTheme(bg: "#A87DC2", fg: "#FFFFFF", name: "Wisteria"),
            ColorTheme(bg: "#FAFE4B", fg: "#000000", name: "Banana Yellow"),
            ColorTheme(bg: "#C0022F", fg: "#FFFFFF", name: "Lipstick Red"),
            ColorTheme(bg: "#0E87CC", fg: "#FFFFFF", name: "Water Blue"),
            ColorTheme(bg: "#8D8468", fg: "#FFFFFF", name: "Brown Grey"),
            ColorTheme(bg: "#AD03DE", fg: "#FFFFFF", name: "Vibrant Purple"),
            ColorTheme(bg: "#8CFF9E", fg: "#000000", name: "Baby Green"),
            ColorTheme(bg: "#94AC02", fg: "#FFFFFF", name: "Barf Green"),
            ColorTheme(bg: "#C4FFF7", fg: "#000000", name: "Eggshell Blue"),
            ColorTheme(bg: "#FDEE73", fg: "#000000", name: "Sandy Yellow"),
            ColorTheme(bg: "#33B864", fg: "#FFFFFF", name: "Cool Green"),
            ColorTheme(bg: "#758DA3", fg: "#FFFFFF", name: "Blue/Grey"),
            ColorTheme(bg: "#F504C9", fg: "#FFFFFF", name: "Hot Magenta"),
            ColorTheme(bg: "#77A1B5", fg: "#FFFFFF", name: "Greyblue"),
            ColorTheme(bg: "#8756E4", fg: "#FFFFFF", name: "Purpley"),
            ColorTheme(bg: "#889717", fg: "#FFFFFF", name: "Baby Shit Green"),
            ColorTheme(bg: "#C27E79", fg: "#FFFFFF", name: "Brownish Pink"),
            ColorTheme(bg: "#017371", fg: "#FFFFFF", name: "Dark Aquamarine"),
            ColorTheme(bg: "#9F8303", fg: "#FFFFFF", name: "Diarrhea"),
            ColorTheme(bg: "#F7D560", fg: "#000000", name: "Light Mustard"),
            ColorTheme(bg: "#BDF6FE", fg: "#000000", name: "Pale Sky Blue"),
            ColorTheme(bg: "#75B84F", fg: "#FFFFFF", name: "Turtle Green"),
            ColorTheme(bg: "#9CBB04", fg: "#FFFFFF", name: "Bright Olive"),
            ColorTheme(bg: "#29465B", fg: "#FFFFFF", name: "Dark Grey Blue"),
            ColorTheme(bg: "#696006", fg: "#FFFFFF", name: "Greeny Brown"),
            ColorTheme(bg: "#C1C6FC", fg: "#000000", name: "Light Periwinkle"),
            ColorTheme(bg: "#35AD6B", fg: "#FFFFFF", name: "Seaweed Green"),
            ColorTheme(bg: "#FFFD37", fg: "#000000", name: "Sunshine Yellow"),
            ColorTheme(bg: "#A442A0", fg: "#FFFFFF", name: "Ugly Purple"),
            ColorTheme(bg: "#F36196", fg: "#FFFFFF", name: "Medium Pink"),
            ColorTheme(bg: "#947706", fg: "#FFFFFF", name: "Puke Brown"),
            ColorTheme(bg: "#1E9167", fg: "#FFFFFF", name: "Viridian"),
            ColorTheme(bg: "#B5C306", fg: "#FFFFFF", name: "Bile"),
            ColorTheme(bg: "#FEFF7F", fg: "#000000", name: "Faded Yellow"),
            ColorTheme(bg: "#CFFDBC", fg: "#000000", name: "Very Pale Green"),
            ColorTheme(bg: "#0ADD08", fg: "#FFFFFF", name: "Vibrant Green"),
            ColorTheme(bg: "#87FD05", fg: "#FFFFFF", name: "Bright Lime"),
            ColorTheme(bg: "#1EF876", fg: "#FFFFFF", name: "Spearmint"),
            ColorTheme(bg: "#7BFDC7", fg: "#000000", name: "Light Aquamarine"),
            ColorTheme(bg: "#BCECAC", fg: "#000000", name: "Light Sage"),
            ColorTheme(bg: "#BBF90F", fg: "#000000", name: "Yellowgreen"),
            ColorTheme(bg: "#AB9004", fg: "#FFFFFF", name: "Baby Poo"),
            ColorTheme(bg: "#1FB57A", fg: "#FFFFFF", name: "Dark Seafoam"),
            ColorTheme(bg: "#00555A", fg: "#FFFFFF", name: "Deep Teal"),
            ColorTheme(bg: "#A484AC", fg: "#FFFFFF", name: "Heather"),
            ColorTheme(bg: "#C45508", fg: "#FFFFFF", name: "Rust Orange"),
            ColorTheme(bg: "#3F829D", fg: "#FFFFFF", name: "Dirty Blue"),
            ColorTheme(bg: "#548D44", fg: "#FFFFFF", name: "Fern Green"),
            ColorTheme(bg: "#C95EFB", fg: "#FFFFFF", name: "Bright Lilac"),
            ColorTheme(bg: "#3AE57F", fg: "#FFFFFF", name: "Weird Green"),
            ColorTheme(bg: "#016795", fg: "#FFFFFF", name: "Peacock Blue"),
            ColorTheme(bg: "#87A922", fg: "#FFFFFF", name: "Avocado Green"),
            ColorTheme(bg: "#F0944D", fg: "#FFFFFF", name: "Faded Orange"),
            ColorTheme(bg: "#5D1451", fg: "#FFFFFF", name: "Grape Purple"),
            ColorTheme(bg: "#D0FE1D", fg: "#000000", name: "Lime Yellow"),
            ColorTheme(bg: "#FFA62B", fg: "#FFFFFF", name: "Mango"),
            ColorTheme(bg: "#01B44C", fg: "#FFFFFF", name: "Shamrock"),
            ColorTheme(bg: "#FF6CB5", fg: "#FFFFFF", name: "Bubblegum"),
            ColorTheme(bg: "#6B4247", fg: "#FFFFFF", name: "Purplish Brown"),
            ColorTheme(bg: "#C7C10C", fg: "#FFFFFF", name: "Vomit Yellow"),
            ColorTheme(bg: "#B7FFFA", fg: "#000000", name: "Pale Cyan"),
            ColorTheme(bg: "#AEFF6E", fg: "#000000", name: "Key Lime"),
            ColorTheme(bg: "#EC2D01", fg: "#FFFFFF", name: "Tomato Red"),
            ColorTheme(bg: "#76FF7B", fg: "#FFFFFF", name: "Lightgreen"),
            ColorTheme(bg: "#730039", fg: "#FFFFFF", name: "Merlot"),
            ColorTheme(bg: "#040348", fg: "#FFFFFF", name: "Night Blue"),
            ColorTheme(bg: "#DF4EC8", fg: "#FFFFFF", name: "Purpleish Pink"),
            ColorTheme(bg: "#6ECB3C", fg: "#FFFFFF", name: "Apple"),
            ColorTheme(bg: "#8F9805", fg: "#FFFFFF", name: "Baby Poop Green"),
            ColorTheme(bg: "#5EDC1F", fg: "#FFFFFF", name: "Green Apple"),
            ColorTheme(bg: "#D94FF5", fg: "#FFFFFF", name: "Heliotrope"),
            ColorTheme(bg: "#C8FD3D", fg: "#000000", name: "Yellow/Green"),
            ColorTheme(bg: "#070D0D", fg: "#FFFFFF", name: "Almost Black"),
            ColorTheme(bg: "#4984B8", fg: "#FFFFFF", name: "Cool Blue"),
            ColorTheme(bg: "#51B73B", fg: "#FFFFFF", name: "Leafy Green"),
            ColorTheme(bg: "#AC7E04", fg: "#FFFFFF", name: "Mustard Brown"),
            ColorTheme(bg: "#4E5481", fg: "#FFFFFF", name: "Dusk"),
            ColorTheme(bg: "#876E4B", fg: "#FFFFFF", name: "Dull Brown"),
            ColorTheme(bg: "#58BC08", fg: "#FFFFFF", name: "Frog Green"),
            ColorTheme(bg: "#2FEF10", fg: "#FFFFFF", name: "Vivid Green"),
            ColorTheme(bg: "#2DFE54", fg: "#FFFFFF", name: "Bright Light Green"),
            ColorTheme(bg: "#9CEF43", fg: "#FFFFFF", name: "Kiwi"),
            ColorTheme(bg: "#18D17B", fg: "#FFFFFF", name: "Seaweed"),
            ColorTheme(bg: "#35530A", fg: "#FFFFFF", name: "Navy Green"),
            ColorTheme(bg: "#1805DB", fg: "#FFFFFF", name: "Ultramarine Blue"),
            ColorTheme(bg: "#6258C4", fg: "#FFFFFF", name: "Iris"),
            ColorTheme(bg: "#FF964F", fg: "#FFFFFF", name: "Pastel Orange"),
            ColorTheme(bg: "#FFAB0F", fg: "#FFFFFF", name: "Yellowish Orange"),
            ColorTheme(bg: "#8F8CE7", fg: "#FFFFFF", name: "Perrywinkle"),
            ColorTheme(bg: "#24BCA8", fg: "#FFFFFF", name: "Tealish"),
            ColorTheme(bg: "#3F012C", fg: "#FFFFFF", name: "Dark Plum"),
            ColorTheme(bg: "#CBF85F", fg: "#000000", name: "Pear"),
            ColorTheme(bg: "#FF724C", fg: "#FFFFFF", name: "Pinkish Orange"),
            ColorTheme(bg: "#280137", fg: "#FFFFFF", name: "Midnight Purple"),
            ColorTheme(bg: "#B36FF6", fg: "#FFFFFF", name: "Light Urple"),
            ColorTheme(bg: "#48C072", fg: "#FFFFFF", name: "Dark Mint"),
            ColorTheme(bg: "#BCCB7A", fg: "#FFFFFF", name: "Greenish Tan"),
            ColorTheme(bg: "#A8415B", fg: "#FFFFFF", name: "Light Burgundy"),
            ColorTheme(bg: "#06B1C4", fg: "#FFFFFF", name: "Turquoise Blue"),
            ColorTheme(bg: "#CD7584", fg: "#FFFFFF", name: "Ugly Pink"),
            ColorTheme(bg: "#F1DA7A", fg: "#000000", name: "Sandy"),
            ColorTheme(bg: "#FF0490", fg: "#FFFFFF", name: "Electric Pink"),
            ColorTheme(bg: "#805B87", fg: "#FFFFFF", name: "Muted Purple"),
            ColorTheme(bg: "#50A747", fg: "#FFFFFF", name: "Mid Green"),
            ColorTheme(bg: "#A8A495", fg: "#FFFFFF", name: "Greyish"),
            ColorTheme(bg: "#CFFF04", fg: "#000000", name: "Neon Yellow"),
            ColorTheme(bg: "#FFFF7E", fg: "#000000", name: "Banana"),
            ColorTheme(bg: "#FF7FA7", fg: "#FFFFFF", name: "Carnation Pink"),
            ColorTheme(bg: "#EF4026", fg: "#FFFFFF", name: "Tomato"),
            ColorTheme(bg: "#3C9992", fg: "#FFFFFF", name: "Sea"),
            ColorTheme(bg: "#886806", fg: "#FFFFFF", name: "Muddy Brown"),
            ColorTheme(bg: "#04F489", fg: "#FFFFFF", name: "Turquoise Green"),
            ColorTheme(bg: "#FEF69E", fg: "#000000", name: "Buff"),
            ColorTheme(bg: "#CFAF7B", fg: "#FFFFFF", name: "Fawn"),
            ColorTheme(bg: "#3B719F", fg: "#FFFFFF", name: "Muted Blue"),
            ColorTheme(bg: "#FDC1C5", fg: "#000000", name: "Pale Rose"),
            ColorTheme(bg: "#20C073", fg: "#FFFFFF", name: "Dark Mint Green"),
            ColorTheme(bg: "#9B5FC0", fg: "#FFFFFF", name: "Amethyst"),
            ColorTheme(bg: "#0F9B8E", fg: "#FFFFFF", name: "Blue/Green"),
            ColorTheme(bg: "#742802", fg: "#FFFFFF", name: "Chestnut"),
            ColorTheme(bg: "#9DB92C", fg: "#FFFFFF", name: "Sick Green"),
            ColorTheme(bg: "#A4BF20", fg: "#FFFFFF", name: "Pea"),
            ColorTheme(bg: "#CD5909", fg: "#FFFFFF", name: "Rusty Orange"),
            ColorTheme(bg: "#ADA587", fg: "#FFFFFF", name: "Stone"),
            ColorTheme(bg: "#BE013C", fg: "#FFFFFF", name: "Rose Red"),
            ColorTheme(bg: "#B8FFEB", fg: "#000000", name: "Pale Aqua"),
            ColorTheme(bg: "#DC4D01", fg: "#FFFFFF", name: "Deep Orange"),
            ColorTheme(bg: "#A2653E", fg: "#FFFFFF", name: "Earth"),
            ColorTheme(bg: "#638B27", fg: "#FFFFFF", name: "Mossy Green"),
            ColorTheme(bg: "#419C03", fg: "#FFFFFF", name: "Grassy Green"),
            ColorTheme(bg: "#B1FF65", fg: "#000000", name: "Pale Lime Green"),
            ColorTheme(bg: "#9DBCD4", fg: "#FFFFFF", name: "Light Grey Blue"),
            ColorTheme(bg: "#77AB56", fg: "#FFFFFF", name: "Asparagus"),
            ColorTheme(bg: "#464196", fg: "#FFFFFF", name: "Blueberry"),
            ColorTheme(bg: "#990147", fg: "#FFFFFF", name: "Purple Red"),
            ColorTheme(bg: "#BEFD73", fg: "#000000", name: "Pale Lime"),
            ColorTheme(bg: "#32BF84", fg: "#FFFFFF", name: "Greenish Teal"),
            ColorTheme(bg: "#AF6F09", fg: "#FFFFFF", name: "Caramel"),
            ColorTheme(bg: "#A0025C", fg: "#FFFFFF", name: "Deep Magenta"),
            ColorTheme(bg: "#FFD8B1", fg: "#000000", name: "Light Peach"),
            ColorTheme(bg: "#7F4E1E", fg: "#FFFFFF", name: "Milk Chocolate"),
            ColorTheme(bg: "#BF9B0C", fg: "#FFFFFF", name: "Ocher"),
            ColorTheme(bg: "#6BA353", fg: "#FFFFFF", name: "Off Green"),
            ColorTheme(bg: "#F075E6", fg: "#FFFFFF", name: "Purply Pink"),
            ColorTheme(bg: "#7BC8F6", fg: "#FFFFFF", name: "Lightblue"),
            ColorTheme(bg: "#475F94", fg: "#FFFFFF", name: "Dusky Blue"),
            ColorTheme(bg: "#F5BF03", fg: "#FFFFFF", name: "Golden"),
            ColorTheme(bg: "#FFFD74", fg: "#000000", name: "Butter Yellow"),
            ColorTheme(bg: "#895B7B", fg: "#FFFFFF", name: "Dusky Purple"),
            ColorTheme(bg: "#436BAD", fg: "#FFFFFF", name: "French Blue"),
            ColorTheme(bg: "#D0C101", fg: "#FFFFFF", name: "Ugly Yellow"),
            ColorTheme(bg: "#C6F808", fg: "#000000", name: "Greeny Yellow"),
            ColorTheme(bg: "#F43605", fg: "#FFFFFF", name: "Orangish Red"),
            ColorTheme(bg: "#02C14D", fg: "#FFFFFF", name: "Shamrock Green"),
            ColorTheme(bg: "#B25F03", fg: "#FFFFFF", name: "Orangish Brown"),
            ColorTheme(bg: "#2A7E19", fg: "#FFFFFF", name: "Tree Green"),
            ColorTheme(bg: "#490648", fg: "#FFFFFF", name: "Deep Violet"),
            ColorTheme(bg: "#536267", fg: "#FFFFFF", name: "Gunmetal"),
            ColorTheme(bg: "#5A06EF", fg: "#FFFFFF", name: "Blue/Purple"),
            ColorTheme(bg: "#CF0234", fg: "#FFFFFF", name: "Cherry"),
            ColorTheme(bg: "#C4A661", fg: "#FFFFFF", name: "Sandy Brown"),
            ColorTheme(bg: "#978A84", fg: "#FFFFFF", name: "Warm Grey"),
            ColorTheme(bg: "#1F0954", fg: "#FFFFFF", name: "Dark Indigo"),
            ColorTheme(bg: "#2BB179", fg: "#FFFFFF", name: "Bluey Green"),
            ColorTheme(bg: "#C3909B", fg: "#FFFFFF", name: "Grey Pink"),
            ColorTheme(bg: "#A66FB5", fg: "#FFFFFF", name: "Soft Purple"),
            ColorTheme(bg: "#770001", fg: "#FFFFFF", name: "Blood"),
            ColorTheme(bg: "#922B05", fg: "#FFFFFF", name: "Brown Red"),
            ColorTheme(bg: "#7D7F7C", fg: "#FFFFFF", name: "Medium Grey"),
            ColorTheme(bg: "#990F4B", fg: "#FFFFFF", name: "Berry"),
            ColorTheme(bg: "#8F7303", fg: "#FFFFFF", name: "Poo"),
            ColorTheme(bg: "#C83CB9", fg: "#FFFFFF", name: "Purpley Pink"),
            ColorTheme(bg: "#FEA993", fg: "#FFFFFF", name: "Light Salmon"),
            ColorTheme(bg: "#ACBB0D", fg: "#FFFFFF", name: "Snot"),
            ColorTheme(bg: "#C071FE", fg: "#FFFFFF", name: "Easter Purple"),
            ColorTheme(bg: "#CCFD7F", fg: "#000000", name: "Light Yellow Green"),
            ColorTheme(bg: "#828344", fg: "#FFFFFF", name: "Drab"),
            ColorTheme(bg: "#FFC5CB", fg: "#000000", name: "Light Rose"),
            ColorTheme(bg: "#AB1239", fg: "#FFFFFF", name: "Rouge"),
            ColorTheme(bg: "#B0054B", fg: "#FFFFFF", name: "Purplish Red"),
            ColorTheme(bg: "#99CC04", fg: "#FFFFFF", name: "Slime Green"),
            ColorTheme(bg: "#937C00", fg: "#FFFFFF", name: "Baby Poop"),
            ColorTheme(bg: "#019529", fg: "#FFFFFF", name: "Irish Green"),
            ColorTheme(bg: "#EF1DE7", fg: "#FFFFFF", name: "Pink/Purple"),
            ColorTheme(bg: "#42B395", fg: "#FFFFFF", name: "Greeny Blue"),
            ColorTheme(bg: "#9D5783", fg: "#FFFFFF", name: "Light Plum"),
            ColorTheme(bg: "#C8ACA9", fg: "#FFFFFF", name: "Pinkish Grey"),
            ColorTheme(bg: "#C87606", fg: "#FFFFFF", name: "Dirty Orange"),
            ColorTheme(bg: "#AA2704", fg: "#FFFFFF", name: "Rust Red"),
            ColorTheme(bg: "#E4CBFF", fg: "#000000", name: "Pale Lilac"),
            ColorTheme(bg: "#FA4224", fg: "#FFFFFF", name: "Orangey Red"),
            ColorTheme(bg: "#0804F9", fg: "#FFFFFF", name: "Primary Blue"),
            ColorTheme(bg: "#5CB200", fg: "#FFFFFF", name: "Kermit Green"),
            ColorTheme(bg: "#76424E", fg: "#FFFFFF", name: "Brownish Purple"),
            ColorTheme(bg: "#6C7A0E", fg: "#FFFFFF", name: "Murky Green"),
            ColorTheme(bg: "#FBDD7E", fg: "#000000", name: "Wheat"),
            ColorTheme(bg: "#2A0134", fg: "#FFFFFF", name: "Very Dark Purple"),
            ColorTheme(bg: "#044A05", fg: "#FFFFFF", name: "Bottle Green"),
            ColorTheme(bg: "#FD4659", fg: "#FFFFFF", name: "Watermelon"),
            ColorTheme(bg: "#0D75F8", fg: "#FFFFFF", name: "Deep Sky Blue"),
            ColorTheme(bg: "#FE0002", fg: "#FFFFFF", name: "Fire Engine Red"),
            ColorTheme(bg: "#CB9D06", fg: "#FFFFFF", name: "Yellow Ochre"),
            ColorTheme(bg: "#FB7D07", fg: "#FFFFFF", name: "Pumpkin Orange"),
            ColorTheme(bg: "#B9CC81", fg: "#FFFFFF", name: "Pale Olive"),
            ColorTheme(bg: "#EDC8FF", fg: "#000000", name: "Light Lilac"),
            ColorTheme(bg: "#61E160", fg: "#FFFFFF", name: "Lightish Green"),
            ColorTheme(bg: "#8AB8FE", fg: "#FFFFFF", name: "Carolina Blue"),
            ColorTheme(bg: "#920A4E", fg: "#FFFFFF", name: "Mulberry"),
            ColorTheme(bg: "#FE02A2", fg: "#FFFFFF", name: "Shocking Pink"),
            ColorTheme(bg: "#9A3001", fg: "#FFFFFF", name: "Auburn"),
            ColorTheme(bg: "#65FE08", fg: "#FFFFFF", name: "Bright Lime Green"),
            ColorTheme(bg: "#BEFDB7", fg: "#000000", name: "Celadon"),
            ColorTheme(bg: "#B17261", fg: "#FFFFFF", name: "Pinkish Brown"),
            ColorTheme(bg: "#885F01", fg: "#FFFFFF", name: "Poo Brown"),
            ColorTheme(bg: "#02CCFE", fg: "#FFFFFF", name: "Bright Sky Blue"),
            ColorTheme(bg: "#C1FD95", fg: "#000000", name: "Celery"),
            ColorTheme(bg: "#836539", fg: "#FFFFFF", name: "Dirt Brown"),
            ColorTheme(bg: "#FB2943", fg: "#FFFFFF", name: "Strawberry"),
            ColorTheme(bg: "#84B701", fg: "#FFFFFF", name: "Dark Lime"),
            ColorTheme(bg: "#B66325", fg: "#FFFFFF", name: "Copper"),
            ColorTheme(bg: "#7F5112", fg: "#FFFFFF", name: "Medium Brown"),
            ColorTheme(bg: "#5FA052", fg: "#FFFFFF", name: "Muted Green"),
            ColorTheme(bg: "#6DEDFD", fg: "#000000", name: "robins Egg"),
            ColorTheme(bg: "#0BF9EA", fg: "#FFFFFF", name: "Bright Aqua"),
            ColorTheme(bg: "#C760FF", fg: "#FFFFFF", name: "Bright Lavender"),
            ColorTheme(bg: "#F6CEFC", fg: "#000000", name: "Very Light Purple"),
            ColorTheme(bg: "#155084", fg: "#FFFFFF", name: "Light Navy"),
            ColorTheme(bg: "#F5054F", fg: "#FFFFFF", name: "Pink Red"),
            ColorTheme(bg: "#645403", fg: "#FFFFFF", name: "Olive Brown"),
            ColorTheme(bg: "#7A5901", fg: "#FFFFFF", name: "Poop Brown"),
            ColorTheme(bg: "#A8B504", fg: "#FFFFFF", name: "Mustard Green"),
            ColorTheme(bg: "#3D9973", fg: "#FFFFFF", name: "Ocean Green"),
            ColorTheme(bg: "#76A973", fg: "#FFFFFF", name: "Dusty Green"),
            ColorTheme(bg: "#2E5A88", fg: "#FFFFFF", name: "Light Navy Blue"),
            ColorTheme(bg: "#0BF77D", fg: "#FFFFFF", name: "Minty Green"),
            ColorTheme(bg: "#BD6C48", fg: "#FFFFFF", name: "Adobe"),
            ColorTheme(bg: "#AC1DB8", fg: "#FFFFFF", name: "Barney"),
            ColorTheme(bg: "#2BAF6A", fg: "#FFFFFF", name: "Jade Green"),
            ColorTheme(bg: "#26F7FD", fg: "#FFFFFF", name: "Bright Light Blue"),
            ColorTheme(bg: "#AEFD6C", fg: "#000000", name: "Light Lime"),
            ColorTheme(bg: "#9B8F55", fg: "#FFFFFF", name: "Dark Khaki"),
            ColorTheme(bg: "#FFAD01", fg: "#FFFFFF", name: "Orange Yellow"),
            ColorTheme(bg: "#C69C04", fg: "#FFFFFF", name: "Ocre"),
            ColorTheme(bg: "#F4D054", fg: "#000000", name: "Maize"),
            ColorTheme(bg: "#DE9DAC", fg: "#FFFFFF", name: "Faded Pink"),
            ColorTheme(bg: "#05480D", fg: "#FFFFFF", name: "British Racing Green"),
            ColorTheme(bg: "#C9AE74", fg: "#FFFFFF", name: "Sandstone"),
            ColorTheme(bg: "#60460F", fg: "#FFFFFF", name: "Mud Brown"),
            ColorTheme(bg: "#98F6B0", fg: "#000000", name: "Light Sea Green"),
            ColorTheme(bg: "#8AF1FE", fg: "#000000", name: "Robin Egg Blue"),
            ColorTheme(bg: "#2EE8BB", fg: "#FFFFFF", name: "Aqua Marine"),
            ColorTheme(bg: "#11875D", fg: "#FFFFFF", name: "Dark Sea Green"),
            ColorTheme(bg: "#FDB0C0", fg: "#000000", name: "Soft Pink"),
            ColorTheme(bg: "#B16002", fg: "#FFFFFF", name: "Orangey Brown"),
            ColorTheme(bg: "#F7022A", fg: "#FFFFFF", name: "Cherry Red"),
            ColorTheme(bg: "#D5AB09", fg: "#FFFFFF", name: "Burnt Yellow"),
            ColorTheme(bg: "#86775F", fg: "#FFFFFF", name: "Brownish Grey"),
            ColorTheme(bg: "#C69F59", fg: "#FFFFFF", name: "Camel"),
            ColorTheme(bg: "#7A687F", fg: "#FFFFFF", name: "Purplish Grey"),
            ColorTheme(bg: "#042E60", fg: "#FFFFFF", name: "Marine"),
            ColorTheme(bg: "#C88D94", fg: "#FFFFFF", name: "Greyish Pink"),
            ColorTheme(bg: "#A5FBD5", fg: "#000000", name: "Pale Turquoise"),
            ColorTheme(bg: "#FFFE71", fg: "#000000", name: "Pastel Yellow"),
            ColorTheme(bg: "#6241C7", fg: "#FFFFFF", name: "Bluey Purple"),
            ColorTheme(bg: "#FFFE40", fg: "#000000", name: "Canary Yellow"),
            ColorTheme(bg: "#D3494E", fg: "#FFFFFF", name: "Faded Red"),
            ColorTheme(bg: "#985E2B", fg: "#FFFFFF", name: "Sepia"),
            ColorTheme(bg: "#A6814C", fg: "#FFFFFF", name: "Coffee"),
            ColorTheme(bg: "#FF08E8", fg: "#FFFFFF", name: "Bright Magenta"),
            ColorTheme(bg: "#9D7651", fg: "#FFFFFF", name: "Mocha"),
            ColorTheme(bg: "#98568D", fg: "#FFFFFF", name: "Purpleish"),
            ColorTheme(bg: "#9E003A", fg: "#FFFFFF", name: "Cranberry"),
            ColorTheme(bg: "#287C37", fg: "#FFFFFF", name: "Darkish Green"),
            ColorTheme(bg: "#B96902", fg: "#FFFFFF", name: "Brown Orange"),
            ColorTheme(bg: "#BA6873", fg: "#FFFFFF", name: "Dusky Rose"),
            ColorTheme(bg: "#FF7855", fg: "#FFFFFF", name: "Melon"),
            ColorTheme(bg: "#94B21C", fg: "#FFFFFF", name: "Sickly Green"),
            ColorTheme(bg: "#C5C9C7", fg: "#FFFFFF", name: "Silver"),
            ColorTheme(bg: "#661AEE", fg: "#FFFFFF", name: "Purply Blue"),
            ColorTheme(bg: "#6140EF", fg: "#FFFFFF", name: "Purpleish Blue"),
            ColorTheme(bg: "#9BE5AA", fg: "#000000", name: "Hospital Green"),
            ColorTheme(bg: "#7B5804", fg: "#FFFFFF", name: "Shit Brown"),
            ColorTheme(bg: "#276AB3", fg: "#FFFFFF", name: "Mid Blue"),
            ColorTheme(bg: "#FEB308", fg: "#FFFFFF", name: "Amber"),
            ColorTheme(bg: "#8CFD7E", fg: "#000000", name: "Easter Green"),
            ColorTheme(bg: "#6488EA", fg: "#FFFFFF", name: "Soft Blue"),
            ColorTheme(bg: "#056EEE", fg: "#FFFFFF", name: "Cerulean Blue"),
            ColorTheme(bg: "#B27A01", fg: "#FFFFFF", name: "Golden Brown"),
            ColorTheme(bg: "#0FFEF9", fg: "#FFFFFF", name: "Bright Turquoise"),
            ColorTheme(bg: "#FA2A55", fg: "#FFFFFF", name: "Red Pink"),
            ColorTheme(bg: "#820747", fg: "#FFFFFF", name: "Red Purple"),
            ColorTheme(bg: "#7A6A4F", fg: "#FFFFFF", name: "Greyish Brown"),
            ColorTheme(bg: "#F4320C", fg: "#FFFFFF", name: "Vermillion"),
            ColorTheme(bg: "#A13905", fg: "#FFFFFF", name: "Russet"),
            ColorTheme(bg: "#6F828A", fg: "#FFFFFF", name: "Steel Grey"),
            ColorTheme(bg: "#A55AF4", fg: "#FFFFFF", name: "Lighter Purple"),
            ColorTheme(bg: "#AD0AFD", fg: "#FFFFFF", name: "Bright Violet"),
            ColorTheme(bg: "#004577", fg: "#FFFFFF", name: "Prussian Blue"),
            ColorTheme(bg: "#658D6D", fg: "#FFFFFF", name: "Slate Green"),
            ColorTheme(bg: "#CA7B80", fg: "#FFFFFF", name: "Dirty Pink"),
            ColorTheme(bg: "#005249", fg: "#FFFFFF", name: "Dark Blue Green"),
            ColorTheme(bg: "#2B5D34", fg: "#FFFFFF", name: "Pine"),
            ColorTheme(bg: "#BFF128", fg: "#000000", name: "Yellowy Green"),
            ColorTheme(bg: "#B59410", fg: "#FFFFFF", name: "Dark Gold"),
            ColorTheme(bg: "#2976BB", fg: "#FFFFFF", name: "Bluish"),
            ColorTheme(bg: "#014182", fg: "#FFFFFF", name: "Darkish Blue"),
            ColorTheme(bg: "#BB3F3F", fg: "#FFFFFF", name: "Dull Red"),
            ColorTheme(bg: "#FC2647", fg: "#FFFFFF", name: "Pinky Red"),
            ColorTheme(bg: "#A87900", fg: "#FFFFFF", name: "Bronze"),
            ColorTheme(bg: "#82CBB2", fg: "#FFFFFF", name: "Pale Teal"),
            ColorTheme(bg: "#667C3E", fg: "#FFFFFF", name: "Military Green"),
            ColorTheme(bg: "#FE46A5", fg: "#FFFFFF", name: "Barbie Pink"),
            ColorTheme(bg: "#FE83CC", fg: "#FFFFFF", name: "Bubblegum Pink"),
            ColorTheme(bg: "#94A617", fg: "#FFFFFF", name: "Pea Soup Green"),
            ColorTheme(bg: "#A88905", fg: "#FFFFFF", name: "Dark Mustard"),
            ColorTheme(bg: "#7F5F00", fg: "#FFFFFF", name: "Shit"),
            ColorTheme(bg: "#9E43A2", fg: "#FFFFFF", name: "Medium Purple"),
            ColorTheme(bg: "#062E03", fg: "#FFFFFF", name: "Very Dark Green"),
            ColorTheme(bg: "#8A6E45", fg: "#FFFFFF", name: "Dirt"),
            ColorTheme(bg: "#CC7A8B", fg: "#FFFFFF", name: "Dusky Pink"),
            ColorTheme(bg: "#9E0168", fg: "#FFFFFF", name: "Red Violet"),
            ColorTheme(bg: "#FDFF38", fg: "#000000", name: "Lemon Yellow"),
            ColorTheme(bg: "#C0FA8B", fg: "#000000", name: "Pistachio"),
            ColorTheme(bg: "#EEDC5B", fg: "#000000", name: "Dull Yellow"),
            ColorTheme(bg: "#7EBD01", fg: "#FFFFFF", name: "Dark Lime Green"),
            ColorTheme(bg: "#3B5B92", fg: "#FFFFFF", name: "Denim Blue"),
            ColorTheme(bg: "#01889F", fg: "#FFFFFF", name: "Teal Blue"),
            ColorTheme(bg: "#3D7AFD", fg: "#FFFFFF", name: "Lightish Blue"),
            ColorTheme(bg: "#5F34E7", fg: "#FFFFFF", name: "Purpley Blue"),
            ColorTheme(bg: "#6D5ACF", fg: "#FFFFFF", name: "Light Indigo"),
            ColorTheme(bg: "#748500", fg: "#FFFFFF", name: "Swamp Green"),
            ColorTheme(bg: "#706C11", fg: "#FFFFFF", name: "Brown Green"),
            ColorTheme(bg: "#3C0008", fg: "#FFFFFF", name: "Dark Maroon"),
            ColorTheme(bg: "#CB00F5", fg: "#FFFFFF", name: "Hot Purple"),
            ColorTheme(bg: "#002D04", fg: "#FFFFFF", name: "Dark Forest Green"),
            ColorTheme(bg: "#658CBB", fg: "#FFFFFF", name: "Faded Blue"),
            ColorTheme(bg: "#749551", fg: "#FFFFFF", name: "Drab Green"),
            ColorTheme(bg: "#B9FF66", fg: "#000000", name: "Light Lime Green"),
            ColorTheme(bg: "#9DC100", fg: "#FFFFFF", name: "Snot Green"),
            ColorTheme(bg: "#FAEE66", fg: "#000000", name: "Yellowish"),
            ColorTheme(bg: "#7EFBB3", fg: "#000000", name: "Light Blue Green"),
            ColorTheme(bg: "#7B002C", fg: "#FFFFFF", name: "Bordeaux"),
            ColorTheme(bg: "#C292A1", fg: "#FFFFFF", name: "Light Mauve"),
            ColorTheme(bg: "#017B92", fg: "#FFFFFF", name: "Ocean"),
            ColorTheme(bg: "#FCC006", fg: "#FFFFFF", name: "Marigold"),
            ColorTheme(bg: "#657432", fg: "#FFFFFF", name: "Muddy Green"),
            ColorTheme(bg: "#D8863B", fg: "#FFFFFF", name: "Dull Orange"),
            ColorTheme(bg: "#738595", fg: "#FFFFFF", name: "Steel"),
            ColorTheme(bg: "#AA23FF", fg: "#FFFFFF", name: "Electric Purple"),
            ColorTheme(bg: "#9B7A01", fg: "#FFFFFF", name: "Yellowish Brown"),
            ColorTheme(bg: "#F29E8E", fg: "#FFFFFF", name: "Blush"),
            ColorTheme(bg: "#6FC276", fg: "#FFFFFF", name: "Soft Green"),
            ColorTheme(bg: "#FF5B00", fg: "#FFFFFF", name: "Bright Orange"),
            ColorTheme(bg: "#FDFF52", fg: "#000000", name: "Lemon"),
            ColorTheme(bg: "#866F85", fg: "#FFFFFF", name: "Purple Grey"),
            ColorTheme(bg: "#EECFFE", fg: "#000000", name: "Pale Lavender"),
            ColorTheme(bg: "#510AC9", fg: "#FFFFFF", name: "Violet Blue"),
            ColorTheme(bg: "#4F9153", fg: "#FFFFFF", name: "Light Forest Green"),
            ColorTheme(bg: "#9F2305", fg: "#FFFFFF", name: "Burnt Red"),
            ColorTheme(bg: "#728639", fg: "#FFFFFF", name: "Khaki Green"),
            ColorTheme(bg: "#DE0C62", fg: "#FFFFFF", name: "Cerise"),
            ColorTheme(bg: "#916E99", fg: "#FFFFFF", name: "Faded Purple"),
            ColorTheme(bg: "#FFB16D", fg: "#FFFFFF", name: "Apricot"),
            ColorTheme(bg: "#3C4D03", fg: "#FFFFFF", name: "Dark Olive Green"),
            ColorTheme(bg: "#7F7053", fg: "#FFFFFF", name: "Grey Brown"),
            ColorTheme(bg: "#77926F", fg: "#FFFFFF", name: "Green Grey"),
            ColorTheme(bg: "#010FCC", fg: "#FFFFFF", name: "True Blue"),
            ColorTheme(bg: "#CEAEFA", fg: "#FFFFFF", name: "Pale Violet"),
            ColorTheme(bg: "#8F99FB", fg: "#FFFFFF", name: "Periwinkle Blue"),
            ColorTheme(bg: "#C6FCFF", fg: "#000000", name: "Light Sky Blue"),
            ColorTheme(bg: "#5539CC", fg: "#FFFFFF", name: "Blurple"),
            ColorTheme(bg: "#544E03", fg: "#FFFFFF", name: "Green Brown"),
            ColorTheme(bg: "#017A79", fg: "#FFFFFF", name: "Bluegreen"),
            ColorTheme(bg: "#C9B003", fg: "#FFFFFF", name: "Brownish Yellow"),
            ColorTheme(bg: "#929901", fg: "#FFFFFF", name: "Pea Soup"),
            ColorTheme(bg: "#0B5509", fg: "#FFFFFF", name: "Forest"),
            ColorTheme(bg: "#A00498", fg: "#FFFFFF", name: "Barney Purple"),
            ColorTheme(bg: "#2000B1", fg: "#FFFFFF", name: "Ultramarine"),
            ColorTheme(bg: "#94568C", fg: "#FFFFFF", name: "Purplish"),
            ColorTheme(bg: "#C2BE0E", fg: "#FFFFFF", name: "Puke Yellow"),
            ColorTheme(bg: "#748B97", fg: "#FFFFFF", name: "Bluish Grey"),
            ColorTheme(bg: "#665FD1", fg: "#FFFFFF", name: "Dark Periwinkle"),
            ColorTheme(bg: "#9C6DA5", fg: "#FFFFFF", name: "Dark Lilac"),
            ColorTheme(bg: "#C44240", fg: "#FFFFFF", name: "Reddish"),
            ColorTheme(bg: "#A24857", fg: "#FFFFFF", name: "Light Maroon"),
            ColorTheme(bg: "#825F87", fg: "#FFFFFF", name: "Dusty Purple"),
            ColorTheme(bg: "#C9643B", fg: "#FFFFFF", name: "Terra Cotta"),
            ColorTheme(bg: "#90B134", fg: "#FFFFFF", name: "Avocado"),
            ColorTheme(bg: "#01386A", fg: "#FFFFFF", name: "Marine Blue"),
            ColorTheme(bg: "#25A36F", fg: "#FFFFFF", name: "Teal Green"),
            ColorTheme(bg: "#59656D", fg: "#FFFFFF", name: "Slate Grey"),
            ColorTheme(bg: "#75FD63", fg: "#FFFFFF", name: "Lighter Green"),
            ColorTheme(bg: "#21FC0D", fg: "#FFFFFF", name: "Electric Green"),
            ColorTheme(bg: "#5A86AD", fg: "#FFFFFF", name: "Dusty Blue"),
            ColorTheme(bg: "#FEC615", fg: "#FFFFFF", name: "Golden Yellow"),
            ColorTheme(bg: "#FFFD01", fg: "#000000", name: "Bright Yellow"),
            ColorTheme(bg: "#DFC5FE", fg: "#000000", name: "Light Lavender"),
            ColorTheme(bg: "#B26400", fg: "#FFFFFF", name: "Umber"),
            ColorTheme(bg: "#7F5E00", fg: "#FFFFFF", name: "Poop"),
            ColorTheme(bg: "#DE7E5D", fg: "#FFFFFF", name: "Dark Peach"),
            ColorTheme(bg: "#048243", fg: "#FFFFFF", name: "Jungle Green"),
            ColorTheme(bg: "#3B638C", fg: "#FFFFFF", name: "Denim"),
            ColorTheme(bg: "#B79400", fg: "#FFFFFF", name: "Yellow Brown"),
            ColorTheme(bg: "#84597E", fg: "#FFFFFF", name: "Dull Purple"),
            ColorTheme(bg: "#411900", fg: "#FFFFFF", name: "Chocolate Brown"),
            ColorTheme(bg: "#7B0323", fg: "#FFFFFF", name: "Wine Red"),
            ColorTheme(bg: "#04D9FF", fg: "#FFFFFF", name: "Neon Blue"),
            ColorTheme(bg: "#667E2C", fg: "#FFFFFF", name: "Dirty Green"),
            ColorTheme(bg: "#FBEEAC", fg: "#000000", name: "Light Tan"),
            ColorTheme(bg: "#D7FFFE", fg: "#000000", name: "Ice Blue"),
            ColorTheme(bg: "#4E7496", fg: "#FFFFFF", name: "Cadet Blue"),
            ColorTheme(bg: "#874C62", fg: "#FFFFFF", name: "Dark Mauve"),
            ColorTheme(bg: "#D5FFFF", fg: "#000000", name: "Very Light Blue"),
            ColorTheme(bg: "#826D8C", fg: "#FFFFFF", name: "Grey Purple"),
            ColorTheme(bg: "#FFBACD", fg: "#000000", name: "Pastel Pink"),
            ColorTheme(bg: "#D1FFBD", fg: "#000000", name: "Very Light Green"),
            ColorTheme(bg: "#448EE4", fg: "#FFFFFF", name: "Dark Sky Blue"),
            ColorTheme(bg: "#05472A", fg: "#FFFFFF", name: "Evergreen"),
            ColorTheme(bg: "#D5869D", fg: "#FFFFFF", name: "Dull Pink"),
            ColorTheme(bg: "#3D0734", fg: "#FFFFFF", name: "Aubergine"),
            ColorTheme(bg: "#4A0100", fg: "#FFFFFF", name: "Mahogany"),
            ColorTheme(bg: "#F8481C", fg: "#FFFFFF", name: "Reddish Orange"),
            ColorTheme(bg: "#02590F", fg: "#FFFFFF", name: "Deep Green"),
            ColorTheme(bg: "#89A203", fg: "#FFFFFF", name: "Vomit Green"),
            ColorTheme(bg: "#E03FD8", fg: "#FFFFFF", name: "Purple Pink"),
            ColorTheme(bg: "#D58A94", fg: "#FFFFFF", name: "Dusty Pink"),
            ColorTheme(bg: "#7BB274", fg: "#FFFFFF", name: "Faded Green"),
            ColorTheme(bg: "#526525", fg: "#FFFFFF", name: "Camo Green"),
            ColorTheme(bg: "#C94CBE", fg: "#FFFFFF", name: "Pinky Purple"),
            ColorTheme(bg: "#DB4BDA", fg: "#FFFFFF", name: "Pink Purple"),
            ColorTheme(bg: "#9E3623", fg: "#FFFFFF", name: "Brownish Red"),
            ColorTheme(bg: "#B5485D", fg: "#FFFFFF", name: "Dark Rose"),
            ColorTheme(bg: "#735C12", fg: "#FFFFFF", name: "Mud"),
            ColorTheme(bg: "#9C6D57", fg: "#FFFFFF", name: "Brownish"),
            ColorTheme(bg: "#028F1E", fg: "#FFFFFF", name: "Emerald Green"),
            ColorTheme(bg: "#B1916E", fg: "#FFFFFF", name: "Pale Brown"),
            ColorTheme(bg: "#49759C", fg: "#FFFFFF", name: "Dull Blue"),
            ColorTheme(bg: "#A0450E", fg: "#FFFFFF", name: "Burnt Umber"),
            ColorTheme(bg: "#39AD48", fg: "#FFFFFF", name: "Medium Green"),
            ColorTheme(bg: "#B66A50", fg: "#FFFFFF", name: "Clay"),
            ColorTheme(bg: "#8CFFDB", fg: "#000000", name: "Light Aqua"),
            ColorTheme(bg: "#A4BE5C", fg: "#FFFFFF", name: "Light Olive Green"),
            ColorTheme(bg: "#CB7723", fg: "#FFFFFF", name: "Brownish Orange"),
            ColorTheme(bg: "#05696B", fg: "#FFFFFF", name: "Dark Aqua"),
            ColorTheme(bg: "#CE5DAE", fg: "#FFFFFF", name: "Purplish Pink"),
            ColorTheme(bg: "#C85A53", fg: "#FFFFFF", name: "Dark Salmon"),
            ColorTheme(bg: "#96AE8D", fg: "#FFFFFF", name: "Greenish Grey"),
            ColorTheme(bg: "#1FA774", fg: "#FFFFFF", name: "Jade"),
            ColorTheme(bg: "#7A9703", fg: "#FFFFFF", name: "Ugly Green"),
            ColorTheme(bg: "#AC9362", fg: "#FFFFFF", name: "Dark Beige"),
            ColorTheme(bg: "#01A049", fg: "#FFFFFF", name: "Emerald"),
            ColorTheme(bg: "#D9544D", fg: "#FFFFFF", name: "Pale Red"),
            ColorTheme(bg: "#FA5FF7", fg: "#FFFFFF", name: "Light Magenta"),
            ColorTheme(bg: "#82CAFC", fg: "#FFFFFF", name: "Sky"),
            ColorTheme(bg: "#ACFFFC", fg: "#000000", name: "Light Cyan"),
            ColorTheme(bg: "#FCB001", fg: "#FFFFFF", name: "Yellow Orange"),
            ColorTheme(bg: "#910951", fg: "#FFFFFF", name: "Reddish Purple"),
            ColorTheme(bg: "#FE2C54", fg: "#FFFFFF", name: "Reddish Pink"),
            ColorTheme(bg: "#C875C4", fg: "#FFFFFF", name: "Orchid"),
            ColorTheme(bg: "#CDC50A", fg: "#FFFFFF", name: "Dirty Yellow"),
            ColorTheme(bg: "#FD411E", fg: "#FFFFFF", name: "Orange Red"),
            ColorTheme(bg: "#9A0200", fg: "#FFFFFF", name: "Deep Red"),
            ColorTheme(bg: "#BE6400", fg: "#FFFFFF", name: "Orange Brown"),
            ColorTheme(bg: "#030AA7", fg: "#FFFFFF", name: "Cobalt Blue"),
            ColorTheme(bg: "#FE019A", fg: "#FFFFFF", name: "Neon Pink"),
            ColorTheme(bg: "#F7879A", fg: "#FFFFFF", name: "Rose Pink"),
            ColorTheme(bg: "#887191", fg: "#FFFFFF", name: "Greyish Purple"),
            ColorTheme(bg: "#B00149", fg: "#FFFFFF", name: "Raspberry"),
            ColorTheme(bg: "#12E193", fg: "#FFFFFF", name: "Aqua Green"),
            ColorTheme(bg: "#FE7B7C", fg: "#FFFFFF", name: "Salmon Pink"),
            ColorTheme(bg: "#FF9408", fg: "#FFFFFF", name: "Tangerine"),
            ColorTheme(bg: "#6A6E09", fg: "#FFFFFF", name: "Brownish Green"),
            ColorTheme(bg: "#8B2E16", fg: "#FFFFFF", name: "Red Brown"),
            ColorTheme(bg: "#696112", fg: "#FFFFFF", name: "Greenish Brown"),
            ColorTheme(bg: "#E17701", fg: "#FFFFFF", name: "Pumpkin"),
            ColorTheme(bg: "#0A481E", fg: "#FFFFFF", name: "Pine Green"),
            ColorTheme(bg: "#343837", fg: "#FFFFFF", name: "Charcoal"),
            ColorTheme(bg: "#FFB7CE", fg: "#000000", name: "Baby Pink"),
            ColorTheme(bg: "#6A79F7", fg: "#FFFFFF", name: "Cornflower"),
            ColorTheme(bg: "#5D06E9", fg: "#FFFFFF", name: "Blue Violet"),
            ColorTheme(bg: "#3D1C02", fg: "#FFFFFF", name: "Chocolate"),
            ColorTheme(bg: "#82A67D", fg: "#FFFFFF", name: "Greyish Green"),
            ColorTheme(bg: "#BE0119", fg: "#FFFFFF", name: "Scarlet"),
            ColorTheme(bg: "#C9FF27", fg: "#000000", name: "Green Yellow"),
            ColorTheme(bg: "#373E02", fg: "#FFFFFF", name: "Dark Olive"),
            ColorTheme(bg: "#A9561E", fg: "#FFFFFF", name: "Sienna"),
            ColorTheme(bg: "#CAA0FF", fg: "#FFFFFF", name: "Pastel Purple"),
            ColorTheme(bg: "#CA6641", fg: "#FFFFFF", name: "Terracotta"),
            ColorTheme(bg: "#02D8E9", fg: "#FFFFFF", name: "Aqua Blue"),
            ColorTheme(bg: "#88B378", fg: "#FFFFFF", name: "Sage Green"),
            ColorTheme(bg: "#980002", fg: "#FFFFFF", name: "Blood Red"),
            ColorTheme(bg: "#CB0162", fg: "#FFFFFF", name: "Deep Pink"),
            ColorTheme(bg: "#5CAC2D", fg: "#FFFFFF", name: "Grass"),
            ColorTheme(bg: "#769958", fg: "#FFFFFF", name: "Moss"),
            ColorTheme(bg: "#A2BFFE", fg: "#FFFFFF", name: "Pastel Blue"),
            ColorTheme(bg: "#10A674", fg: "#FFFFFF", name: "Bluish Green"),
            ColorTheme(bg: "#06B48B", fg: "#FFFFFF", name: "Green Blue"),
            ColorTheme(bg: "#AF884A", fg: "#FFFFFF", name: "Dark Tan"),
            ColorTheme(bg: "#0B8B87", fg: "#FFFFFF", name: "Greenish Blue"),
            ColorTheme(bg: "#FFA756", fg: "#FFFFFF", name: "Pale Orange"),
            ColorTheme(bg: "#A2A415", fg: "#FFFFFF", name: "Vomit"),
            ColorTheme(bg: "#154406", fg: "#FFFFFF", name: "Forrest Green"),
            ColorTheme(bg: "#856798", fg: "#FFFFFF", name: "Dark Lavender"),
            ColorTheme(bg: "#34013F", fg: "#FFFFFF", name: "Dark Violet"),
            ColorTheme(bg: "#632DE9", fg: "#FFFFFF", name: "Purple Blue"),
            ColorTheme(bg: "#0A888A", fg: "#FFFFFF", name: "Dark Cyan"),
            ColorTheme(bg: "#6F7632", fg: "#FFFFFF", name: "Olive Drab"),
            ColorTheme(bg: "#D46A7E", fg: "#FFFFFF", name: "Pinkish"),
            ColorTheme(bg: "#1E488F", fg: "#FFFFFF", name: "Cobalt"),
            ColorTheme(bg: "#BC13FE", fg: "#FFFFFF", name: "Neon Purple"),
            ColorTheme(bg: "#7EF4CC", fg: "#000000", name: "Light Turquoise"),
            ColorTheme(bg: "#76CD26", fg: "#FFFFFF", name: "Apple Green"),
            ColorTheme(bg: "#74A662", fg: "#FFFFFF", name: "Dull Green"),
            ColorTheme(bg: "#80013F", fg: "#FFFFFF", name: "Wine"),
            ColorTheme(bg: "#B1D1FC", fg: "#000000", name: "Powder Blue"),
            ColorTheme(bg: "#0652FF", fg: "#FFFFFF", name: "Electric Blue"),
            ColorTheme(bg: "#045C5A", fg: "#FFFFFF", name: "Dark Turquoise"),
            ColorTheme(bg: "#5729CE", fg: "#FFFFFF", name: "Blue Purple"),
            ColorTheme(bg: "#069AF3", fg: "#FFFFFF", name: "Azure"),
            ColorTheme(bg: "#FF000D", fg: "#FFFFFF", name: "Bright Red"),
            ColorTheme(bg: "#F10C45", fg: "#FFFFFF", name: "Pinkish Red"),
            ColorTheme(bg: "#5170D7", fg: "#FFFFFF", name: "Cornflower Blue"),
            ColorTheme(bg: "#ACBF69", fg: "#FFFFFF", name: "Light Olive"),
            ColorTheme(bg: "#6C3461", fg: "#FFFFFF", name: "Grape"),
            ColorTheme(bg: "#5E819D", fg: "#FFFFFF", name: "Greyish Blue"),
            ColorTheme(bg: "#601EF9", fg: "#FFFFFF", name: "Purplish Blue"),
            ColorTheme(bg: "#B0DD16", fg: "#FFFFFF", name: "Yellowish Green"),
            ColorTheme(bg: "#CDFD02", fg: "#000000", name: "Greenish Yellow"),
            ColorTheme(bg: "#2C6FBB", fg: "#FFFFFF", name: "Medium Blue"),
            ColorTheme(bg: "#C0737A", fg: "#FFFFFF", name: "Dusty Rose"),
            ColorTheme(bg: "#D6B4FC", fg: "#FFFFFF", name: "Light Violet"),
            ColorTheme(bg: "#703BE7", fg: "#FFFFFF", name: "Bluish Purple"),
            ColorTheme(bg: "#FD3C06", fg: "#FFFFFF", name: "Red Orange"),
            ColorTheme(bg: "#960056", fg: "#FFFFFF", name: "Dark Magenta"),
            ColorTheme(bg: "#40A368", fg: "#FFFFFF", name: "Greenish"),
            ColorTheme(bg: "#03719C", fg: "#FFFFFF", name: "Ocean Blue"),
            ColorTheme(bg: "#FC5A50", fg: "#FFFFFF", name: "Coral"),
            ColorTheme(bg: "#7F2B0A", fg: "#FFFFFF", name: "Reddish Brown"),
            ColorTheme(bg: "#B04E0F", fg: "#FFFFFF", name: "Burnt Sienna"),
            ColorTheme(bg: "#A03623", fg: "#FFFFFF", name: "Brick"),
            ColorTheme(bg: "#87AE73", fg: "#FFFFFF", name: "Sage"),
            ColorTheme(bg: "#789B73", fg: "#FFFFFF", name: "Grey Green"),
            ColorTheme(bg: "#98EFF9", fg: "#000000", name: "robins Egg Blue"),
            ColorTheme(bg: "#658B38", fg: "#FFFFFF", name: "Moss Green"),
            ColorTheme(bg: "#5A7D9A", fg: "#FFFFFF", name: "Steel Blue"),
            ColorTheme(bg: "#380835", fg: "#FFFFFF", name: "Eggplant"),
            ColorTheme(bg: "#FFFE7A", fg: "#000000", name: "Light Yellow"),
            ColorTheme(bg: "#5CA904", fg: "#FFFFFF", name: "Leaf Green"),
            ColorTheme(bg: "#D8DCD6", fg: "#000000", name: "Light Grey"),
            ColorTheme(bg: "#A5A502", fg: "#FFFFFF", name: "Puke"),
            ColorTheme(bg: "#D648D7", fg: "#FFFFFF", name: "Pinkish Purple"),
            ColorTheme(bg: "#047495", fg: "#FFFFFF", name: "Sea Blue"),
            ColorTheme(bg: "#B790D4", fg: "#FFFFFF", name: "Pale Purple"),
            ColorTheme(bg: "#5B7C99", fg: "#FFFFFF", name: "Slate Blue"),
            ColorTheme(bg: "#607C8E", fg: "#FFFFFF", name: "Blue Grey"),
            ColorTheme(bg: "#0B4008", fg: "#FFFFFF", name: "Hunter Green"),
            ColorTheme(bg: "#ED0DD9", fg: "#FFFFFF", name: "Fuchsia"),
            ColorTheme(bg: "#8C000F", fg: "#FFFFFF", name: "Crimson"),
            ColorTheme(bg: "#FFFF84", fg: "#000000", name: "Pale Yellow"),
            ColorTheme(bg: "#BF9005", fg: "#FFFFFF", name: "Ochre"),
            ColorTheme(bg: "#D2BD0A", fg: "#FFFFFF", name: "Mustard Yellow"),
            ColorTheme(bg: "#FF474C", fg: "#FFFFFF", name: "Light Red"),
            ColorTheme(bg: "#0485D1", fg: "#FFFFFF", name: "Cerulean"),
            ColorTheme(bg: "#FFCFDC", fg: "#000000", name: "Pale Pink"),
            ColorTheme(bg: "#040273", fg: "#FFFFFF", name: "Deep Blue"),
            ColorTheme(bg: "#A83C09", fg: "#FFFFFF", name: "Rust"),
            ColorTheme(bg: "#90E4C1", fg: "#FFFFFF", name: "Light Teal"),
            ColorTheme(bg: "#516572", fg: "#FFFFFF", name: "Slate"),
            ColorTheme(bg: "#FAC205", fg: "#FFFFFF", name: "Goldenrod"),
            ColorTheme(bg: "#D5B60A", fg: "#FFFFFF", name: "Dark Yellow"),
            ColorTheme(bg: "#363737", fg: "#FFFFFF", name: "Dark Grey"),
            ColorTheme(bg: "#4B5D16", fg: "#FFFFFF", name: "Army Green"),
            ColorTheme(bg: "#6B8BA4", fg: "#FFFFFF", name: "Grey Blue"),
            ColorTheme(bg: "#80F9AD", fg: "#000000", name: "Seafoam"),
            ColorTheme(bg: "#A57E52", fg: "#FFFFFF", name: "Puce"),
            ColorTheme(bg: "#A9F971", fg: "#000000", name: "Spring Green"),
            ColorTheme(bg: "#C65102", fg: "#FFFFFF", name: "Dark Orange"),
            ColorTheme(bg: "#E2CA76", fg: "#FFFFFF", name: "Sand"),
            ColorTheme(bg: "#B0FF9D", fg: "#000000", name: "Pastel Green"),
            ColorTheme(bg: "#9FFEB0", fg: "#000000", name: "Mint"),
            ColorTheme(bg: "#FDAA48", fg: "#FFFFFF", name: "Light Orange"),
            ColorTheme(bg: "#FE01B1", fg: "#FFFFFF", name: "Bright Pink"),
            ColorTheme(bg: "#C1F80A", fg: "#000000", name: "Chartreuse"),
            ColorTheme(bg: "#36013F", fg: "#FFFFFF", name: "Deep Purple"),
            ColorTheme(bg: "#341C02", fg: "#FFFFFF", name: "Dark Brown"),
            ColorTheme(bg: "#B9A281", fg: "#FFFFFF", name: "Taupe"),
            ColorTheme(bg: "#8EAB12", fg: "#FFFFFF", name: "Pea Green"),
            ColorTheme(bg: "#9AAE07", fg: "#FFFFFF", name: "Puke Green"),
            ColorTheme(bg: "#02AB2E", fg: "#FFFFFF", name: "Kelly Green"),
            ColorTheme(bg: "#7AF9AB", fg: "#000000", name: "Seafoam Green"),
            ColorTheme(bg: "#137E6D", fg: "#FFFFFF", name: "Blue Green"),
            ColorTheme(bg: "#AAA662", fg: "#FFFFFF", name: "Khaki"),
            ColorTheme(bg: "#610023", fg: "#FFFFFF", name: "Burgundy"),
            ColorTheme(bg: "#014D4E", fg: "#FFFFFF", name: "Dark Teal"),
            ColorTheme(bg: "#8F1402", fg: "#FFFFFF", name: "Brick Red"),
            ColorTheme(bg: "#4B006E", fg: "#FFFFFF", name: "Royal Purple"),
            ColorTheme(bg: "#580F41", fg: "#FFFFFF", name: "Plum"),
            ColorTheme(bg: "#8FFF9F", fg: "#000000", name: "Mint Green"),
            ColorTheme(bg: "#DBB40C", fg: "#FFFFFF", name: "Gold"),
            ColorTheme(bg: "#A2CFFE", fg: "#FFFFFF", name: "Baby Blue"),
            ColorTheme(bg: "#C0FB2D", fg: "#000000", name: "Yellow Green"),
            ColorTheme(bg: "#BE03FD", fg: "#FFFFFF", name: "Bright Purple"),
            ColorTheme(bg: "#840000", fg: "#FFFFFF", name: "Dark Red"),
            ColorTheme(bg: "#D0FEFE", fg: "#000000", name: "Pale Blue"),
            ColorTheme(bg: "#3F9B0B", fg: "#FFFFFF", name: "Grass Green"),
            ColorTheme(bg: "#01153E", fg: "#FFFFFF", name: "Navy"),
            ColorTheme(bg: "#04D8B2", fg: "#FFFFFF", name: "Aquamarine"),
            ColorTheme(bg: "#C04E01", fg: "#FFFFFF", name: "Burnt Orange"),
            ColorTheme(bg: "#0CFF0C", fg: "#FFFFFF", name: "Neon Green"),
            ColorTheme(bg: "#0165FC", fg: "#FFFFFF", name: "Bright Blue"),
            ColorTheme(bg: "#CF6275", fg: "#FFFFFF", name: "Rose"),
            ColorTheme(bg: "#FFD1DF", fg: "#000000", name: "Light Pink"),
            ColorTheme(bg: "#CEB301", fg: "#FFFFFF", name: "Mustard"),
            ColorTheme(bg: "#380282", fg: "#FFFFFF", name: "Indigo"),
            ColorTheme(bg: "#AAFF32", fg: "#000000", name: "Lime"),
            ColorTheme(bg: "#53FCA1", fg: "#FFFFFF", name: "Sea Green"),
            ColorTheme(bg: "#8E82FE", fg: "#FFFFFF", name: "Periwinkle"),
            ColorTheme(bg: "#CB416B", fg: "#FFFFFF", name: "Dark Pink"),
            ColorTheme(bg: "#677A04", fg: "#FFFFFF", name: "Olive Green"),
            ColorTheme(bg: "#FFB07C", fg: "#FFFFFF", name: "Peach"),
            ColorTheme(bg: "#C7FDB5", fg: "#000000", name: "Pale Green"),
            ColorTheme(bg: "#AD8150", fg: "#FFFFFF", name: "Light Brown"),
            ColorTheme(bg: "#CEA2FD", fg: "#FFFFFF", name: "Lilac"),
            ColorTheme(bg: "#001146", fg: "#FFFFFF", name: "Navy Blue"),
            ColorTheme(bg: "#0504AA", fg: "#FFFFFF", name: "Royal Blue"),
            ColorTheme(bg: "#E6DAA6", fg: "#000000", name: "Beige"),
            ColorTheme(bg: "#FF796C", fg: "#FFFFFF", name: "Salmon"),
            ColorTheme(bg: "#6E750E", fg: "#FFFFFF", name: "Olive"),
            ColorTheme(bg: "#650021", fg: "#FFFFFF", name: "Maroon"),
            ColorTheme(bg: "#01FF07", fg: "#FFFFFF", name: "Bright Green"),
            ColorTheme(bg: "#35063E", fg: "#FFFFFF", name: "Dark Purple"),
            ColorTheme(bg: "#AE7181", fg: "#FFFFFF", name: "Mauve"),
            ColorTheme(bg: "#06470C", fg: "#FFFFFF", name: "Forest Green"),
            ColorTheme(bg: "#13EAC9", fg: "#FFFFFF", name: "Aqua"),
            ColorTheme(bg: "#D1B26F", fg: "#FFFFFF", name: "Tan"),
            ColorTheme(bg: "#00035B", fg: "#FFFFFF", name: "Dark Blue"),
            ColorTheme(bg: "#C79FEF", fg: "#FFFFFF", name: "Lavender"),
            ColorTheme(bg: "#06C2AC", fg: "#FFFFFF", name: "Turquoise"),
            ColorTheme(bg: "#033500", fg: "#FFFFFF", name: "Dark Green"),
            ColorTheme(bg: "#9A0EEA", fg: "#FFFFFF", name: "Violet"),
            ColorTheme(bg: "#BF77F6", fg: "#FFFFFF", name: "Light Purple"),
            ColorTheme(bg: "#89FE05", fg: "#FFFFFF", name: "Lime Green"),
            ColorTheme(bg: "#929591", fg: "#FFFFFF", name: "Grey"),
            ColorTheme(bg: "#75BBFD", fg: "#FFFFFF", name: "Sky Blue"),
            ColorTheme(bg: "#FFFF14", fg: "#000000", name: "Yellow"),
            ColorTheme(bg: "#C20078", fg: "#FFFFFF", name: "Magenta"),
            ColorTheme(bg: "#96F97B", fg: "#000000", name: "Light Green"),
            ColorTheme(bg: "#F97306", fg: "#FFFFFF", name: "Orange"),
            ColorTheme(bg: "#029386", fg: "#FFFFFF", name: "Teal"),
            ColorTheme(bg: "#95D0FC", fg: "#FFFFFF", name: "Light Blue"),
            ColorTheme(bg: "#E50000", fg: "#FFFFFF", name: "Red"),
            ColorTheme(bg: "#653700", fg: "#FFFFFF", name: "Brown"),
            ColorTheme(bg: "#FF81C0", fg: "#FFFFFF", name: "Pink"),
            ColorTheme(bg: "#0343DF", fg: "#FFFFFF", name: "Blue"),
            ColorTheme(bg: "#15B01A", fg: "#FFFFFF", name: "Green"),
            ColorTheme(bg: "#7E1E9C", fg: "#FFFFFF", name: "Purple"),
    ]
    
    /// Get a random color theme
    static func random() -> ColorTheme {
        all.randomElement() ?? all[0]
    }
    
    /// Get a random vibrant color (suitable for borders/accents)
    static func randomVibrant() -> Color {
        let theme = random()
        return theme.background
    }
}
